### ISSUE TITLE
org.xutils.sample A/libc: Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1)

### ISSUE THREAD

**Issue by shenzhijun** [wyouflf/xUtils3#10]
摩托罗拉  ME865 Android 4.04 下载案例执行【db.saveBindingId(downloadInfo);】报错。
org.xutils.sample A/libc: Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1)

**Comment by wyouflf** [comment]
确定是 db.saveBindingId(downloadInfo); 报的错?

这个方法只是调用系统的sqlite执行保存和查询.

**Comment by wyouflf** [comment]
试试更新xUtils
