### ISSUE TITLE
新版本仍然有几率出现EOFException

### ISSUE THREAD

**Issue by aixinaxc** [wyouflf/xUtils3#102]
根据这个http://stackoverflow.com/questions/20655317/eofexception-getresponsecode
是还缺少httpUrlConn.setRequestProperty( "Accept-Encoding", "" );的原因吗

**Comment by wyouflf** [comment]
根据这个http://stackoverflow.com/questions/20655317/eofexception-getresponsecode
是还缺少httpUrlConn.setRequestProperty( "Accept-Encoding", "" );的原因吗

和这个没有关系, 这个是GZIP支持的问题.

**Comment by wyouflf** [comment]
更新到3.1.26以彻底解决这个问题
