### ISSUE TITLE
3.1.24版本，在项目编译环境是19时，仍然会是出现java.io.EOFException

### ISSUE THREAD

**Issue by aixinaxc** [wyouflf/xUtils3#104]
我的项目时Android的19的编辑，在对数据加载时仍然会出现java.io.EOFException错误
补充：在22的编译版本，在红米1s上仍然会出现eof错误，从而导致程序页面崩溃

**Comment by wyouflf** [comment]
eof不会导致应用崩溃的, 你的onError方法实现的有问题?

**Comment by aixinaxc** [comment]
onError中只有这几个
 mTextRightTop.setClickable(true);
            Toast.makeText(EditShowMsgActivity.this,R.string.code_500,Toast.LENGTH_SHORT).show();
            Log.e("ExamPeopleActivity",ex.getMessage());
并没有做什么操作啊

**Comment by wyouflf** [comment]
尝试更新到3.1.26
