### ISSUE TITLE
怎么自己设置硬盘缓存？

### ISSUE THREAD

**Issue by sundxing** [wyouflf/xUtils3#107]
比如设置开启关闭/存储大小/存放路径 有公开处理的接口或方法吗？

**Comment by wyouflf** [comment]
看这个示例代码中最后一个点击事件方法: https://github.com/wyouflf/xUtils3/blob/master/sample/src/main/java/org/xutils/sample/HttpFragment.java

缓存相关的设置在params里, 使用onCache的规则来清除或覆盖缓存文件.

**Comment by sundxing** [comment]
多谢，这里是选择不使用缓存，所以缓存动作是一直发生的？怎么不用缓存？比如在下载图片时候，每次图片都不一样所以，缓存完全不需要了，我想应该在ImageOptions有对应的设置比较好吧。

**Comment by wyouflf** [comment]
什么业务url不变化但是, 图片会变化?

最好图片更新时, 对应的url也是被更新的, 这样多个用户查看同一个View时不需要每次都清理缓存, 就能得到最新的图片信息. 

应该也没有什么好的方式通知全部用户更新或清除某一个图片文件的缓存吧, 每次都清理或弃用之前的缓存, 浪费多少带宽和用户的流量. (PS: xUtils支持expriy, max-age和Etag, 除非你的服务端做了该策略的支持, 就能更好的支持缓存生命周期的控制, 要支持Etag必须使Callback.CacheCallback#onCache返回false)

最近不常被使用的缓存图片会根据LRU算法自动清理. 所以不在ImageOptions提供这样的参数, 特殊场景请通过Callback.CacheCallback扩展.

**Comment by taixjgg** [comment]
更换头像，地址不换，图片换了，怎么办？

**Comment by wyouflf** [comment]
x.image().loadFile(...., new CacheCallback(){ onCache(){ ... return false;} })

x.image()里的任何加载图片的方法(loadDrawable, bind...), 加上CacheCallback, onCache返回false就会重新下载, 表示不信任缓存.
