### ISSUE TITLE
发现一个bug，view注入时，使用LinearLayoutCompat,SwipeRefreshLayout等嵌套的布局会找不到控件，是在API19的情况下发生的，InvocationTargetException

### ISSUE THREAD

**Issue by GREENFOREST19** [wyouflf/xUtils3#109]
setContentViewMethod.invoke(activity, viewId);执行到这里就会报invocationtargetexception

**Comment by GREENFOREST19** [comment]
是在API19的情况下发生的

**Comment by wyouflf** [comment]
测试未发现有此问题, 贴出你的错误栈信息.

**Comment by GREENFOREST19** [comment]
已解决，是属于在drawable中引用了?actionBarSize属性的原因，找死人的节奏

**Comment by wyouflf** [comment]
升级到最新版注入时会打印更明确的错误信息

2016-01-04 11:22 GMT+08:00 GREENFOREST19 <notifications@github.com>:
