### ISSUE TITLE
不知道是不是我的问题

### ISSUE THREAD

**Issue by winnershili** [wyouflf/xUtils3#110]
使用的时候发现了一些提示, 不知道是不是我代码的问题!

01-04 13:50:29.017: D/x_log:HttpTask.doBackground(L:231)(16836): load: http://www.baidu.com
01-04 13:50:29.027: D/x_log:ColumnUtils.findGetMethod(L:73)(16836): getComment not exist
01-04 13:50:29.027: D/x_log:ColumnUtils.findSetMethod(L:98)(16836): setComment not exist
01-04 13:50:29.037: D/x_log:ColumnUtils.findGetMethod(L:73)(16836): getCommentURL not exist
01-04 13:50:29.037: D/x_log:ColumnUtils.findSetMethod(L:98)(16836): setCommentURL not exist
01-04 13:50:29.037: D/x_log:ColumnUtils.findGetMethod(L:73)(16836): getValue not exist
01-04 13:50:29.037: D/x_log:ColumnUtils.findSetMethod(L:98)(16836): setValue not exist
01-04 13:50:29.037: D/x_log:ColumnUtils.findGetMethod(L:73)(16836): getDomain not exist
01-04 13:50:29.037: D/x_log:ColumnUtils.findSetMethod(L:98)(16836): setDomain not exist

求解答啦 谢谢各位大神!

**Comment by wyouflf** [comment]
不是你的问题, debug信息不用管.

**Comment by winnershili** [comment]
谢谢大神!
