### ISSUE TITLE
addQueryStringParameter乱码

### ISSUE THREAD

**Issue by wishkity** [wyouflf/xUtils3#111]
你好，我想问下addQueryStringParameter和addBodyParameter这两个有什么区别。使用addQueryStringParameter传中文就是乱码，使用addBodyParameter就没问题。

**Comment by wyouflf** [comment]
Query参数在url后面, Body参数在消息体.
Query乱码, Body不乱码可以肯定是你们服务端接受这两种参数是使用了不同的编码, 找你们服务端调试修改.

**Comment by 247321453** [comment]
服务端一定是gbk，哈哈哈

**Comment by Androidshilei** [comment]
我用post的form表单，传中文的时候服务端读取就会出现乱码，服务端的问题？

**Comment by sunbird89629** [comment]
服务器端和客户端都用u8最好。
