### ISSUE TITLE
DbManager.update问题

### ISSUE THREAD

**Issue by 494739635** [wyouflf/xUtils3#114]
WhereBuilder wb = WhereBuilder.b("jid", "=", bean.getjId()).b("subapp_id", "=", bean.getSubappId()); 
dbManager.update(bean, wb, null);
这样的一个语句，以前的第三个参数可传null,现在必须要传一个KeyValue,条件不都已经写在WhereBuilder里了吗,而且即便传了keyvalue对象编译还是不通过,这里改如何处理

**Comment by wyouflf** [comment]
int update(Class<?> entityType, WhereBuilder whereBuilder, KeyValue... nameValuePairs) throws DbException;

第一个参数是要更新的表类型.

dbManager.update(Bean.class, wb, new KeyValue("name1","xxx"), new KeyValue("name2","xxx"));

**Comment by 494739635** [comment]
![Uploading QQ图片20160107140741.png…]()
我给的参数都是对的，也加try了,还是编译不通过,能指点下吗

**Comment by 494739635** [comment]
![qq 20160107140741](https://cloud.githubusercontent.com/assets/12248420/12163431/805659ea-b548-11e5-9373-634a03ce544a.png)
我给的参数都是对的，也加try了,还是编译不通过,能指点下吗
