### ISSUE TITLE
DB执行onUpgrade之后增加了几个列，结果后面执行该对象的保存就不能成功了！

### ISSUE THREAD

**Issue by CatchZeng** [wyouflf/xUtils3#115]
.setDbUpgradeListener(new DbManager.DbUpgradeListener() {
                    @Override
                    public void onUpgrade(DbManager db, int oldVersion, int newVersion) {
                        try {
                            db.addColumn(HHMediaEntity.class, "resourceId");
                            db.addColumn(HHMediaEntity.class, "activityId");
                        } catch (DbException e) {
                            e.printStackTrace();
                        }
                    }
                });
更新后无法保存HHMediaEntity实体了！

**Comment by 2639949627** [comment]
怎么关闭了？不说下解决方法吗？嘿嘿
