### ISSUE TITLE
NetworkOnMainThreadException 问题

### ISSUE THREAD

**Issue by lgfng** [wyouflf/xUtils3#116]
Android API 11 之后添加了 ```NetworkOnMainThreadException ``` 异常，不允许在主线程中访问网络。

所以， 对于语句 ```x.http().getSync(RequestParams params, Class<T> type)```，
 当 ``` false == param.isCancelFast()``` 便会抛出```NetworkOnMainThreadException ``` 异常。
因为 从  ```x.task().startSync()``` 到 ``` HttpTask.doBackground()``` 一直在main 线程执行。 在构建了 一个RequestWorker 实例之后， **因为  ``` false == param.isCancelFast()``` ,  所以 直接调用了 worker 的run() 方法，而不是 start()**, 所以一直到最后，都还在main线程中， 便会引发异常。

因为对于 ``` RequestParams.isCancelFast()``` 的作用不是很清楚，所以还是留给作者来修改了。

**Comment by wyouflf** [comment]
getSync 是同步访问的 必须在非UI线程调用.
UI线程只能用不带Sync后缀的方法.

**Comment by lgfng** [comment]
哦哦， 明白了。谢谢。
