### ISSUE TITLE
在x86的gif加载失败

### ISSUE THREAD

**Issue by 247321453** [wyouflf/xUtils3#121]
01-08 13:48:59.954 20620-21091/com.cool.browser W/System.err: java.io.IOException: Mark has been invalidated.
01-08 13:48:59.954 20620-21091/com.cool.browser W/System.err:     at java.io.BufferedInputStream.reset(BufferedInputStream.java:350)
01-08 13:48:59.954 20620-21091/com.cool.browser W/System.err:     at android.graphics.Movie.decodeStream(Native Method)
01-08 13:48:59.954 20620-21091/com.cool.browser W/System.err:     at org.xutils.image.ImageDecoder.decodeGif(ImageDecoder.java)
01-08 13:48:59.954 20620-21091/com.cool.browser W/System.err:     at org.xutils.image.ImageDecoder.a(ImageDecoder.java)
01-08 13:48:59.954 20620-21091/com.cool.browser W/System.err:     at org.xutils.image.a.prepare(ImageLoader.java)
01-08 13:48:59.954 20620-21091/com.cool.browser W/System.err:     at org.xutils.image.a.prepare(ImageLoader.java)
01-08 13:48:59.954 20620-21091/com.cool.browser W/System.err:     at org.xutils.http.HttpTask.doBackground(HttpTask.java)
01-08 13:48:59.954 20620-21091/com.cool.browser W/System.err:     at org.xutils.common.task.b$1.run(TaskProxy.java)
01-08 13:48:59.954 20620-21091/com.cool.browser W/System.err:     at org.xutils.common.task.a.run(PriorityRunnable.java)
01-08 13:48:59.954 20620-21091/com.cool.browser W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
01-08 13:48:59.954 20620-21091/com.cool.browser W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
01-08 13:48:59.954 20620-21091/com.cool.browser W/System.err:     at java.lang.Thread.run(Thread.java:856)
```
org.xutils.image.ImageDecoder.decodeGif

  in = new BufferedInputStream(new FileInputStream(file));
//添加下面的就没问题了。
  in.mark(1024);
  Movie movie = Movie.decodeStream(in);
```

**Comment by wyouflf** [comment]
感谢反馈, 今晚更新.
