### ISSUE TITLE
下载不支持多监听

### ISSUE THREAD

**Issue by emile0010** [wyouflf/xUtils3#123]
按照smaple里面的下载管理器的定义，下载不支持设置多个监听，多个界面都需要监听下载管理的时候使用起来不方便，这个有计划解决吗？

**Comment by emile0010** [comment]
是否只是将DownloadCallback里面的DownloadViewHolder改成List的方式就可以解决这个问题呢

**Comment by wyouflf** [comment]
可以啊, 修改demo就可以了.

**Comment by emile0010** [comment]
demo的还是略简陋，没有暂停恢复等功能，行吧，大体接口都有的情况下自己想想办法

**Comment by lenzols** [comment]
下载进度监听我这边目前使用的是eventbus进行分发的,需要监听的页面注册eventbus即可.

**Comment by emile0010** [comment]
eventbus是可以的，之前我也是使用的eventbus，只是用eventbus的话相关的说明要写清楚，感觉接手的人容易摸瞎
