### ISSUE TITLE
自定义parser实现了ResponseParser，其中checkResponse()函数如何使用？

### ISSUE THREAD

**Issue by hymanme** [wyouflf/xUtils3#124]
还有public Object parse(Type resultType, Class<?> resultClass, String result)的第一二参数意思，sample过于sample，希望不吝赐教，谢谢。

**Comment by delphi6** [comment]
我也是自己看了看，实践中看出来的。答案如下
假设我们使用Gson做JSON解析
请求中我们写到
x.http().get(XXX, new Callback.CommonCallback<T>(){
  // implement method
} )


这里的XXX 当然是自己构造的request Paramters，不做赘述。
回调中的T 可能是只是一个普通的ResponBean  ，那么世界的请求会写成如下
x.http().get(XXX, new Callback.CommonCallback<MyBean>(){
  // implement method
} )
那么再你的那个方法中就是resultClass


如果回调中的T 是针对解析JSON是Array的这种情况，呢么实际的请求会写成入如下
x.http().get(XXX, new Callback.CommonCallback<List<MyBean>>(){
  // implement method
} )
那么就是resultType。  注意这里的回调里一定是List。而不能写成ArrayList等其他，否则错误

    public Object parse(Type resultType, Class<?> resultClass, String result) throws Throwable {
        if (resultClass == List.class) {
            return new Gson().fromJson(result, resultType);
             //////////////////////
//    TypeToken t = new TypeToken<List<MyBean>>(){}.getType();
//    new Gson.fromJson(result, t)
            ///////////////////////
        } else {
            return new Gson().fromJson(result, resultClass);
        }
    }

**Comment by songhaonangit** [comment]
我也正在看这个问题，想封装下更高效使用
