### ISSUE TITLE
xUtils 使用get方式访问淘宝网站时，出现HttpRetryHandler.retryRequest(L:54): Found错误

### ISSUE THREAD

**Issue by xiejianchao** [wyouflf/xUtils3#126]
版本：3.1.3和3.2.2

使用x.http().get访问淘宝主域名（http：//www.taobao.com）时出现错误，其他网站没发现，原因未知。

-------------------异常信息-----------------

![09fbf7f1-cc92-4ad0-9a37-ec4b1916e28b](https://cloud.githubusercontent.com/assets/3115981/12226438/f44dace8-b856-11e5-8c36-6f83182d56ef.png)

**Comment by wyouflf** [comment]
更新版本试试, 有没有被服务端拒绝访问
