### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by lyqaiym** [wyouflf/xUtils3#129]
RequestParams params = new RequestParams(url);
params.setConnectTimeout(Integer.MAX_VALUE);
params.addHeader("Connection", "Keep-Alive");
x.http().post(params, requestCallBack)
然后在requestCallBack的onError出现异常
重试一下又好了
E/LiveBllLog(31569): java.lang.NullPointerException: Attempt to invoke interface method 'void com.android.okhttp
.internal.http.Transport.writeRequestHeaders(com.android.okhttp.Request)' on a null object reference
E/LiveBllLog(31569):    at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:766)
E/LiveBllLog(31569):    at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.
java:379)
E/LiveBllLog(31569):    at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionI
mpl.java:323)
E/LiveBllLog(31569):    at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnect
ionImpl.java:491)
E/LiveBllLog(31569):    at org.xutils.http.request.HttpRequest.sendRequest(HttpRequest.java:222)
E/LiveBllLog(31569):    at org.xutils.http.loader.StringLoader.load(StringLoader.java:44)
E/LiveBllLog(31569):    at org.xutils.http.loader.StringLoader.load(StringLoader.java:1)
E/LiveBllLog(31569):    at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:81)
E/LiveBllLog(31569):    at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:257)
E/LiveBllLog(31569):    at org.xutils.http.HttpTask$RequestWorker.run(HttpTask.java:517)
E/LiveBllLog(31569):    at org.xutils.http.HttpTask.doBackground(HttpTask.java:239)
E/LiveBllLog(31569):    at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
E/LiveBllLog(31569):    at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21)
E/LiveBllLog(31569):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/LiveBllLog(31569):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/LiveBllLog(31569):    at java.lang.Thread.run(Thread.java:818)

**Comment by wyouflf** [comment]
okhttp的问题或者服务端返回数据的问题, 建议提示用户重试
