### ISSUE TITLE
DB的Column注解问题

### ISSUE THREAD

**Issue by ehaahe** [wyouflf/xUtils3#130]
Column注解支持arraylist、list或者数组属性么？如果支持该怎么写？

**Comment by wyouflf** [comment]
不支持, 看示例代码 37行:

https://github.com/wyouflf/xUtils3/blob/master/sample/src/main/java/org/xutils/sample/db/Parent.java

**Comment by ehaahe** [comment]
那如果是List<String>类型的呢？该怎么操作

**Comment by ehaahe** [comment]
List<String>

**Comment by ehaahe** [comment]
List[String]
