### ISSUE TITLE
下载进度间隔时间能否开放设置？

### ISSUE THREAD

**Issue by emile0010** [wyouflf/xUtils3#132]
现在的下载刷新间隔时间是固定写死的300ms，在使用过程中发现如果是下载小文件的话，进度的跳跃性还是太大了，能否开放这个刷新间隔修改或者更改刷新机制（系统原生下载的判断是双重判断，当时间间隔满足要求或者下载的数据量超过一定量的阈值的时候进行刷新的）？

**Comment by wyouflf** [comment]
下版加上这属性的设置

**Comment by emile0010** [comment]
新版本已经使用了，很完美，3Q
