### ISSUE TITLE
布局文件注解问题

### ISSUE THREAD

**Issue by wfs3006** [wyouflf/xUtils3#134]
我在activity中用注解绑定布局的时候提示，id无效，如下log:
ViewInjectorImpl.injectObject(L:167): Invalid id(2131492871) for @ViewInject!TeacherPaiHangBangListActivity java.lang.RuntimeException: Invalid id(2131492871) for @ViewInject!TeacherPaiHangBangListActivity at org.xutils.view.ViewInjectorImpl.injectObject(ViewInjectorImpl.java:164) at org.xutils.view.ViewInjectorImpl.inject(ViewInjectorImpl.java:89)at com.yzs.fangce.controllers.activicy.BaseActivity.onCreate(BaseActivity.java:38) at com.yzs.fangce.controllers.activicy.TeacherPaiHangBangListActivity.onCreate(TeacherPaiHangBangListActivity.java:30)

代码如下：

@ContentView(R.layout.activity_wen_juan_list)
public class TeacherPaiHangBangListActivity extends BaseActivity {
    private MVCHelper<List<Teacher>> listViewHelper;
    @ViewInject(R.id.tv_topTittle)TextView tittle;
    @ViewInject(R.id.swipeRefreshLayout)SwipeRefreshLayout swipeRefreshLayout;
    @ViewInject(R.id.listView)ListView listView;
    String ids;
        boolean isNormal = false;
        @Override
        protected void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            ids = getIntent().getStringExtra("id");
}
}

public abstract class BaseActivity extends AppCompatActivity implements OnClickListener, MyHttpRequestCallBack.HttpCallbackResult {

```
@Override
protected void onCreate(Bundle arg0) {
    super.onCreate(arg0);
    x.view().inject(this);
}
```

}

**Comment by wyouflf** [comment]
view类型不对应? 升级到新版, 优化了错误提示.

**Comment by wfs3006** [comment]
有些页面没事，不太清楚问题，是不是布局多个地方使用，我更新下试试

**Comment by wfs3006** [comment]
找到问题了，activity的样式设置成这样 android:theme="@android:style/Theme.NoTitleBar"就报错了
