### ISSUE TITLE
x.image().bind设置options图片会重新载入的问题

### ISSUE THREAD

**Issue by wslqm123** [wyouflf/xUtils3#135]
在用recyleview制作图片瀑布流时出了个问题，x.image().bind不设置options的时候一切正常，在设置了options以后一旦触发notifyDataSetChanged界面上的大部分图片会重新载入一次。虽然这个不影响正常的浏览，但每次都闪一下让我看着很难受，大神们有没有解决办法？

**Comment by wyouflf** [comment]
设置size属性, 不设置crop, 图片最大为size指定的宽高.

**Comment by wslqm123** [comment]
可以了，谢谢！
