### ISSUE TITLE
怎么判断一个图片的URL在本地是否有缓存呢

### ISSUE THREAD

**Issue by wishkity** [wyouflf/xUtils3#136]
作者你好，怎么判断一个图片的URL在本地是否有缓存呢？

**Comment by wyouflf** [comment]
请求参数添加CacheCallback, onCache方法有返回就有缓存. 下一版本会加上一个参数控制是否只从缓存获取.

图片的话用x.image().loadFile(...)或x.image().loadDrawable(...)
