### ISSUE TITLE
怎么给请求参数加密

### ISSUE THREAD

**Issue by Jungchen** [wyouflf/xUtils3#137]
感谢 XUTILS 很方便 
RequestParams params = new RequestParams(URL); 
请求参数添加后  
按照示例 可以获取一般的请求信息 
现在需要对请求的参数进行公钥加密 请问应该怎么去实现
RSAUtil2.encryptString(RSAUtil2.getPublicKey(key);, myurl);
url = url.split("\?")[0] + "?data="+decurl;
不通过
params.addBodyParameter(data, decurl);
这种方式  
 能不能通过传入公钥  直接可以加密    

见谅 
再问下  XUTILS3 对比之前的版本改动那么大

**Comment by wyouflf** [comment]
可以自定义ParamsBuilder实现, 参考示例代码
