### ISSUE TITLE
DB读取数据库问题

### ISSUE THREAD

**Issue by huigesv123** [wyouflf/xUtils3#138]
DbManager.DaoConfig daoConfig = new DbManager.DaoConfig()
            .setDbName("test")
            .setDbDir(new File("/sdcard"))
            .setDbVersion(2)
            .setDbUpgradeListener(new DbManager.DbUpgradeListener() {
                @Override
                public void onUpgrade(DbManager db, int oldVersion, int newVersion) {
                    // TODO: ...
                    // db.addColumn(...);
                    // db.dropTable(...);
                    // ...
                }
            });

这是sample中的代码，创建一个数据库进行CRUD操作

但问题是，我本身自己已经创建好数据库了，就读这个数据库就可以了，那我DaoConfig怎样搞呢？

**Comment by Dordong** [comment]
我也碰到了这个问题,网上有说有DbUtils.creat()去操作,但是发现找不到DbUtils这个类.是因为升级到了3.0以后的问题吗?请问现在怎么处理

**Comment by wyouflf** [comment]
配置正确的路径和名称表已存在就不会重复创建
