### ISSUE TITLE
使用Delete方式发起http请求出错

### ISSUE THREAD

**Issue by ehaahe** [wyouflf/xUtils3#139]
使用Delete方式发起http请求时，没有调用onSuccess回调方法，是本来就是这样还是bug？

**Comment by ehaahe** [comment]
打了下断点，测试出来state为ERROR，请求返回的code为204，不知道为什么state为ERROR

**Comment by wyouflf** [comment]
泛型用Boolean试试, 你的泛型是不是用的String, 因为没有result所以没有返回. 
泛型用Boolean返回请求是否成功.
