### ISSUE TITLE
能不能在appliction 里设置一个全局的ImageOptions啊

### ISSUE THREAD

**Issue by reaper12** [wyouflf/xUtils3#142]
能不能在appliction 里设置一个全局的ImageOptions啊

**Comment by wyouflf** [comment]
可以啊

**Comment by reaper12** [comment]
我指的是配置一个默认ImageOptions.并不是用static的方式，就像2.x版本那样

**Comment by wyouflf** [comment]
可以啊, 看看示例项目 ImageFragment

**Comment by reaper12** [comment]
您没明白的我意思，我的意思是可以在application里设置一个自定义的默认ImageOptions，比如x.image().setDefaultImageOptions(imageOptions)。然后在使用的时候如果使用x.image().bind(imageView, url),则使用的是自定义默认的ImageOptions，如果使用x.image().bind(imageView, url, imageOptions)，则使用传入的ImageOptions
