### ISSUE TITLE
x.image()需要优化OOM

### ISSUE THREAD

**Issue by zt80hou** [wyouflf/xUtils3#146]
01-19 14:40:16.725 15745-15891/? E/dalvikvm-heap: Out of memory on a 14920208-byte allocation.
01-19 14:40:16.725 15745-15891/? I/dalvikvm: "xTID#1" prio=5 tid=30 RUNNABLE
01-19 14:40:16.725 15745-15891/? I/dalvikvm:   | group="main" sCount=0 dsCount=0 obj=0x432b08c0 self=0x7729f310
01-19 14:40:16.725 15745-15891/? I/dalvikvm:   | sysTid=15891 nice=0 sched=0/0 cgrp=apps handle=2022044400
01-19 14:40:16.725 15745-15891/? I/dalvikvm:   | state=R schedstat=( 1023705748 133634228 749 ) utm=88 stm=14 core=4
01-19 14:40:16.725 15745-15891/? I/dalvikvm:     at android.graphics.Bitmap.nativeCreate(Native Method)
01-19 14:40:16.725 15745-15891/? I/dalvikvm:     at android.graphics.Bitmap.createBitmap(Bitmap.java:842)
01-19 14:40:16.725 15745-15891/? I/dalvikvm:     at android.graphics.Bitmap.createBitmap(Bitmap.java:810)
01-19 14:40:16.725 15745-15891/? I/dalvikvm:     at android.graphics.Bitmap.createBitmap(Bitmap.java:777)
01-19 14:40:16.725 15745-15891/? I/dalvikvm:     at android.backport.webp.WebPFactory.nativeDecodeFile(Native Method)
01-19 14:40:16.725 15745-15891/? I/dalvikvm:     at android.backport.webp.WebPFactory.decodeFile(WebPFactory.java:58)
01-19 14:40:16.725 15745-15891/? I/dalvikvm:     at org.xutils.image.ImageDecoder.getThumbCache(ImageDecoder.java:659)
01-19 14:40:16.725 15745-15891/? I/dalvikvm:     at org.xutils.image.ImageDecoder.decodeFileWithLock(ImageDecoder.java:114)
01-19 14:40:16.725 15745-15891/? I/dalvikvm:     at org.xutils.image.ImageLoader.prepare(ImageLoader.java:387)
01-19 14:40:16.725 15745-15891/? I/dalvikvm:     at org.xutils.image.ImageLoader.prepare(ImageLoader.java:37)
01-19 14:40:16.725 15745-15891/? I/dalvikvm:     at org.xutils.http.HttpTask.doBackground(HttpTask.java:220)
01-19 14:40:16.725 15745-15891/? I/dalvikvm:     at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
01-19 14:40:16.725 15745-15891/? I/dalvikvm:     at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21)
01-19 14:40:16.725 15745-15891/? I/dalvikvm:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-19 14:40:16.725 15745-15891/? I/dalvikvm:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-19 14:40:16.725 15745-15891/? I/dalvikvm:     at java.lang.Thread.run(Thread.java:841)
01-19 14:40:16.730 15745-15891/? W/dalvikvm: Exception thrown (Ljava/lang/OutOfMemoryError;) while throwing internal exception (Ljava/lang/RuntimeException;)

**Comment by wyouflf** [comment]
imageOption里尽量添加size属性
