### ISSUE TITLE
form 表单 中文乱码

### ISSUE THREAD

**Issue by Sum-sdl** [wyouflf/xUtils3#147]
我用post的form表单，传中文的时候服务端读取就会出现乱码，服务端的问题？

**Comment by wyouflf** [comment]
默认客户端使用utf-8, params.setCharset(...)修改默认值.

**Comment by Androidshilei** [comment]
设置编码后服务的返回的中文变成乱码了~

**Comment by Androidshilei** [comment]
编码可改~Tomcat 没置编码
