### ISSUE TITLE
Db里面把count删了还是移动到别的地方去了？

### ISSUE THREAD

**Issue by DrkCore** [wyouflf/xUtils3#148]
如题，项目准备从原本的2.x的版本迁移到3，但是发现原本DbUtils里面的count方法不见了。
是移动到别的地方，还是直接删了希望我们自己实现呢？

**Comment by wyouflf** [comment]
long count = db.selector(Parent.class).where("name", "LIKE", "w%").and("age", ">", 32).count();

在selector的表达式里面, README里有例子.
