### ISSUE TITLE
xUtils3和之前的2.x版本差异太大了吧

### ISSUE THREAD

**Issue by fly263** [wyouflf/xUtils3#15]
xUtils3和之前的2.x版本差异太大了吧，很多包名都改了，和之前的使用方式有很大的差别，不能沿用之前的方式吗？https://github.com/wyouflf/xUtils 中说“xUtils 2.x对Android 6.0兼容不是很好”，到底是哪些模块、功能兼容有问题呢？

**Comment by wyouflf** [comment]
老版本是我刚学android写的第一个项目,当时为公司项目写的, 鉴于java经验不足, 有些地方确实扩展性不强, xUtils3积累了大量实践和优化, 所以变化较大, 请见谅. 2.x主要是网络模块兼容性不好.

**Comment by cxbiao** [comment]
2.x主要还是affinal吧！
