### ISSUE TITLE
Restful参数的传递

### ISSUE THREAD

**Issue by sunbird89629** [wyouflf/xUtils3#151]
现在的Restful的url样式一般如下：
http://host/persons/15
而15就是id，我感觉有必要支持下这种类型的url的参数传递。
我们可以声明一个url如下：
http://host/persons/:id
然后添加一个addRestfulParameter() 方法，替换url中的参数。

**Comment by wyouflf** [comment]
参考示例项目, 使用@HttpRequest和ParamsBuilder使参数构建模板化.
