### ISSUE TITLE
[Help] Bad Request

### ISSUE THREAD

**Issue by weikao** [wyouflf/xUtils3#152]
第一次请求没问题
第二次出现Bad Request，参数未改变，只是在不同的地方调用。

请问这个是什么原因？谢谢！

-------------Error log----------------
01-21 11:57:34.552: E/x_log:HttpRequest.sendRequest(L:225)(11684): code: 400, msg: Bad Request, result: , url: https://xxx.xxx.xxx.xxx/api-v2/auth/init
01-21 11:57:34.557: W/x_log:HttpRetryHandler.retryRequest(L:54)(11684): Bad Request
01-21 11:57:34.557: W/x_log:HttpRetryHandler.retryRequest(L:54)(11684): code: 400, msg: Bad Request, result: 
01-21 11:57:34.557: W/x_log:HttpRetryHandler.retryRequest(L:54)(11684): 	at org.xutils.http.request.HttpRequest.sendRequest(HttpRequest.java:220)
01-21 11:57:34.557: W/x_log:HttpRetryHandler.retryRequest(L:54)(11684): 	at org.xutils.http.loader.StringLoader.load(StringLoader.java:44)
01-21 11:57:34.557: W/x_log:HttpRetryHandler.retryRequest(L:54)(11684): 	at org.xutils.http.loader.StringLoader.load(StringLoader.java:16)
01-21 11:57:34.557: W/x_log:HttpRetryHandler.retryRequest(L:54)(11684): 	at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:81)
01-21 11:57:34.557: W/x_log:HttpRetryHandler.retryRequest(L:54)(11684): 	at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:253)
01-21 11:57:34.557: W/x_log:HttpRetryHandler.retryRequest(L:54)(11684): 	at org.xutils.http.HttpTask$RequestWorker.run(HttpTask.java:517)
01-21 11:57:34.557: W/x_log:HttpRetryHandler.retryRequest(L:54)(11684): 	at org.xutils.http.HttpTask.doBackground(HttpTask.java:239)
01-21 11:57:34.557: W/x_log:HttpRetryHandler.retryRequest(L:54)(11684): 	at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
01-21 11:57:34.557: W/x_log:HttpRetryHandler.retryRequest(L:54)(11684): 	at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:18)
01-21 11:57:34.557: W/x_log:HttpRetryHandler.retryRequest(L:54)(11684): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-21 11:57:34.557: W/x_log:HttpRetryHandler.retryRequest(L:54)(11684): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-21 11:57:34.557: W/x_log:HttpRetryHandler.retryRequest(L:54)(11684): 	at java.lang.Thread.run(Thread.java:841)
01-21 11:57:34.557: W/x_log:HttpRetryHandler.retryRequest(L:62)(11684): The Request Method can not be retried.

**Comment by wyouflf** [comment]
找你们服务端一起调试
