### ISSUE TITLE
扩展 RequestParams 的问题

### ISSUE THREAD

**Issue by fingerart** [wyouflf/xUtils3#156]
您好, 
我想在RequestParams中进行添加非默认参数进行des3的加密的扩展:

继承RequestParams
``` java
	private transient HashMap<String, String> params = new HashMap<String, String>();
	public FRequestParams addFParameter(String key, String value) {
		params.put(key, value);
		return this;
	}
	private void encryptParams() {
		//some code...
	}
```
我希望在某个时候encryptParams方法能被自动调用, 但是我试过了, 不太好弄, 后来我就做了下面这样的操作
``` java
	public FRequestParams addFParameter(String key, String value) {
		params.put(key, value);
		encryptParams();
		return this;
	}

	private void encryptParams() {
		String jsonData = JSON.toJSONString(params);
		String data = Des3Util.encode(jsonData);
		String hash = encodeData(data);
		addBodyParameter("data", data);
		addBodyParameter("hash", hash);
	}
```
每add一个参数时就encryptParams一次, 我觉得不能忍受, 请问你们有什么更好的办法吗

**Comment by wyouflf** [comment]
参考示例项目使用模板构建参数, 而不是扩展RequestParams:
https://github.com/wyouflf/xUtils3/blob/master/sample/src/main/java/org/xutils/sample/http/JsonDemoParams.java
https://github.com/wyouflf/xUtils3/blob/master/sample/src/main/java/org/xutils/sample/http/JsonDemoParamsBuilder.java

**Comment by fingerart** [comment]
好吧, 怪我没去看sample

**Comment by fingerart** [comment]
难道没个请求都有一个Params类, 并配置上host 和 path 吗?
