### ISSUE TITLE
http 302 再次请求报400错误

### ISSUE THREAD

**Issue by weikao** [wyouflf/xUtils3#157]
1.登录-》 post模式 ，body中是用户名密码，setRequestProperty("Content-Length", 67);
2.登录成功-》返回 302 跳转到另外一个链接 login_success。域不变。
3.在xUtils 请求这个login_success 时。body就变成空的。
但是 setRequestProperty("Content-Length", 67); 依然是67
4.导致服务器400错误。

注解掉 //connection.setRequestProperty("Content-Length", String.valueOf(contentLength));
一切正常。

此情况目前只发生在华为手机上。第一次报400错误，之后再次请求就没有问题了。

**Comment by wyouflf** [comment]
尝试使用自定义 RedirectHandler, params.setRedirectHandler(...).
