### ISSUE TITLE
不带Cookie问题

### ISSUE THREAD

**Issue by Huangzhe** [wyouflf/xUtils3#158]
我们后台服务器在登陆后没有带Cookie去访问，会返回“没有登陆”这个提示信息，但是xUtils3好像是自己就拦截了这个请求，onSucc收不到“没有登陆”这个返回消息，这个怎么修改？

**Comment by wyouflf** [comment]
如果服务返回error, 那么这个文本在onError(ex, isCallbackError)
 ex.getResult()就是返回的文本.
但是最好用返回的responseCode去判断ex.getCode().
