### ISSUE TITLE
http请求无法支持数组类型的参数

### ISSUE THREAD

**Issue by cekowu** [wyouflf/xUtils3#16]
无法支持数组类型的参数

**Comment by wyouflf** [comment]
特殊需求请自己实现:
query参数的话自己在url后面直接加上这个特殊参数: url?p=1&p=2&p=3
body参数模仿源码中BodyRequestBody实现一个可添加List<KeyValuePair>参数的RequestBody, 
然后params.setRequestBody(customBody)

但是最好避免这种设计方法:
简答一点的方式: p=1,2,3
服务端拿到p后: array = p.split(',')
更少的传输字节, 更快的解析速度( p.split(',') 比将 p=1&p=2&p=3 解析为list快),

**Comment by bacy** [comment]
我之前在requestParams的getEntity方法中添加过一个提交json格式的功能。 requestParams可以设置contentType，默认是application/x-www-form-urlencoded，bodyparams转换成key，value形式提交。如果设置成application/json的话，bodyparams会转换成json字符串提交
     else if (TYPE_RAW_JSON.equals(contentType)) {
            try {
                result = new JsonTextEntity(getBodyJsonText(), charset);
            } catch (UnsupportedEncodingException e) {
                e.printStackTrace();
            }
        } else if (bodyParams != null && !bodyParams.isEmpty()) {
            result = new BodyParamsEntity(bodyParams, charset);
        }

**Comment by cekowu** [comment]
谢谢，字符串数组这样拼写是可以的，如果是文件数组的话，有什么好的建议了

**Comment by cekowu** [comment]
文件的话只能再加一种类型

**Comment by cekowu** [comment]
我测试了一下文件上传好像有问题，上传不了文件，还在分析当中

**Comment by cekowu** [comment]
我已经修改源码支持了数组类型

**Comment by wyouflf** [comment]
升级到3.1.0, 开始支持数组参数(重名的参数).

**Comment by cekowu** [comment]
我已经更新到了3.1，正测试中，你们很神速
