### ISSUE TITLE
ViewUtils的@Event注解对v7的ToolBar无效

### ISSUE THREAD

**Issue by sktoozaki** [wyouflf/xUtils3#163]
其他的响应事件用@Event都没问题，唯独这个TooBar，始终无效，代码如下：

@Event(value = R.id.toolbar_main,type = Toolbar.OnMenuItemClickListener.class)
    private boolean onMenuItemClick(MenuItem item){
        switch (item.getItemId())
        {
            case R.id.action_search:
                Toast.makeText(MainActivity.this, "action_search", Toast.LENGTH_SHORT).show();
                break;
            case R.id.action_filter:
                Toast.makeText(MainActivity.this, "action_filter", Toast.LENGTH_SHORT).show();
                break;
            case R.id.action_settings:
                Toast.makeText(MainActivity.this, "action_settings", Toast.LENGTH_SHORT).show();  
                break;
        }
        return true;
    }

之前没用ViewUtils的时候ToolBar在初始化后进行了一些配置：
        mToolbar.setTitle(R.string.main_title);
        mToolbar.setSubtitle(dateTimeNow.toString("yyyy年MM月dd日"));
        mToolbar.setTitleTextColor(R.color.text_main);
        mToolbar.setSubtitleTextColor(R.color.text_main);
        setSupportActionBar(mToolbar);

是否有影响？另外，ViewUtils不支持在方法内使用么？
请查看一下，谢谢。

**Comment by wyouflf** [comment]
过滤x_log看看有没有错误日志

**Comment by sktoozaki** [comment]
已试 添加了 x.Ext.setDebug(true) 到Application 没有打印出来任何日志 - -

**Comment by wyouflf** [comment]
怎么注入的, inject在哪里调用的.

**Comment by sktoozaki** [comment]
在Activity类中，代码结构如下：

@ContentView(R.layout.activity_main)
public class MainActivity extends BaseActivity {

    @ViewInject(R.id.toolbar_main)
    private Toolbar mToolbar;

    @Event(value = R.id.toolbar_main,type = Toolbar.OnMenuItemClickListener.class)
    private void onMenuItemClick(MenuItem item){
        switch (item.getItemId())
        {
           .......
        }
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        initViews();
    }

    private void initViews() {
        ......
        setSupportActionBar(mToolbar);
    }

**Comment by wingsum93** [comment]
in protected void onCreate(Bundle savedInstanceState){
      super.onCreate(savedInstanceState);
       x.view().inject(this);
       initViews();
}


change you code to above should fix you problem
