### ISSUE TITLE
Db是默认开启了事物吗？我写入的数据都存入了db.wal里面。

### ISSUE THREAD

**Issue by l123456789jy** [wyouflf/xUtils3#168]
@wyouflf

**Comment by wyouflf** [comment]
默认开启了事务, 但是没有开启WAL.

是不是你在DaoConfig加了:
.setDbOpenListener(new DbManager.DbOpenListener() {
                @Override
                public void onDbOpened(DbManager db) {
                    db.getDatabase().enableWriteAheadLogging();
                }
            })

**Comment by l123456789jy** [comment]
恩，明白了，我开启了`db.getDatabase().enableWriteAheadLogging();` 这个不就是开启了WAL
