### ISSUE TITLE
@Event(value=???,type=???)

### ISSUE THREAD

**Issue by 28610966** [wyouflf/xUtils3#17]
换成新的版本后, 事件注入直接没用了,什么情况啊?

**Comment by wyouflf** [comment]
/**
 * 1. 方法必须私有限定,
 * 2. 方法以Click或Event结尾, 方便配置混淆编译参数 :
 * -keepattributes *Annotation*
 * -keepclassmembers class * {
 * void *(android.view.View);
 * *** *Click(...);
 * *** *Event(...);
 * }
 * 3. 方法参数形式必须和type对应的Listener接口一致.
 * 4. 注解参数value支持数组: value={id1, id2, id3}
 * 5. 其它参数说明见{@link org.xutils.event.annotation.Event}类的说明.
 **/
@Event(value = R.id.btn_test_baidu1,
        type = View.OnClickListener.class/*可选参数, 默认是View.OnClickListener.class*/)
private void onTestBaidu1Click(View view) {
...
}
