### ISSUE TITLE
老版本升级问题

### ISSUE THREAD

**Issue by xiaowx2010** [wyouflf/xUtils3#172]
有没有简单的一件更新到3.0版本的办法或者脚本呢？多谢

**Comment by DrkCore** [comment]
前不久我刚把公司项目迁移到3，得出的结论是旧版和3之间的差别太大，根本不存在什么一键更新的方法。
不过我迁移的还算顺利，因为在旧版的时代我就将xUtils作为基础封装了一套自己的基类，迁移的时候我只要迁移了基类里面那些基础的代码就好。
希望能够帮助你。

**Comment by wyouflf** [comment]
看sample的示例代码和注释
