### ISSUE TITLE
xUtils3 中 继承RequestParams 后 自定义Params   如何传递多个参数？(dome 中的传递参数没理解  -_-！)

### ISSUE THREAD

**Issue by nut-bin** [wyouflf/xUtils3#174]
RT
 自己断点debug模式下 发现 BaiduParams 的url请求是 https://www.baidu.com/s?bb=a&bb=c&wd=xUtils
  主要是有以下几个问题
1. demo中 public String wd; wd属性是做什么用的？作为key?（url 里也有）
2. demo中 public List<String> bb = new ArrayList<>(); 是用来装载参数的value么？
     要是有多个参数 例如 a=1&b=1&c=1 在BaiduParams里 怎么实现呢？

**Comment by mvpleung** [comment]
RequestParams mParams = new RequestParams("http://www.baidu.com/s");
        mParams.addQueryStringParameter("a", "1");
        mParams.addQueryStringParameter("b", "1");

**Comment by nut-bin** [comment]
谢谢楼上的回答  这个问题 我已经解决了 但是我的实现方式并不是addQueryStringParameter()方式; 

问题解答：
demo中 public String wd; 其实是参数  ，通过看xutils3的源码 其实传递参数是通过java 反射实现的 （已参数名为key,已参数值为value）,所以传递参数可以不用 mParams.addQueryStringParameter("a", "1");方法；可以使用public  String a = "1";  (当然自己必须新建model 并且继承RequestParams，这么做的好处是可以使用@HttpRequest注解)；

下面是自己写的test 测试用的 modle

`package org.xutils.sample.http;

import org.xutils.http.RequestParams;
import org.xutils.http.annotation.HttpRequest;
import org.xutils.http.app.DefaultParamsBuilder;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by wyouflf on 15/11/4.
 */
@HttpRequest(
        host = "https://www.baidu.com",  //请求url
        path = "s",                      //接口名
        builder = DefaultParamsBuilder.class/*可选参数, 控制参数构建过程, 定义参数签名, SSL证书等*/,
        signs = {"signStr",}   // 验签字段
)

public class BaiduParams extends RequestParams {

    public String wd;
    public String a;
    public String b;

    private String test;

    // 数组参数 aa=1&aa=2&aa=4

    public BaiduParams(String test) {
        this.test = test;
        // this.setMultipart(true); // 使用multipart表单
        // this.setAsJsonContent(true); // 请求body将参数转换为json形式发送
    }

    //public long timestamp = System.currentTimeMillis();
    //public File uploadFile; // 上传文件
    //public List<File> files; // 上传文件数组
}
`

下面是自己修改DefaultParamsBuilder.java的 实现
`
package org.xutils.http.app;

import org.xutils.common.util.KeyValue;
import org.xutils.common.util.LogUtil;
import org.xutils.http.RequestParams;
import org.xutils.http.annotation.HttpRequest;

import java.security.cert.X509Certificate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLSocketFactory;
import javax.net.ssl.TrustManager;
import javax.net.ssl.X509TrustManager;

/**
 * Created by wyouflf on 15/8/20.
 * 默认参数构造器
 */
public class DefaultParamsBuilder implements ParamsBuilder {

    public DefaultParamsBuilder() {
    }

    /**
     * 根据@HttpRequest构建请求的url
     *
     * @param params
     * @param httpRequest
     * @return
     */
    @Override
    public String buildUri(RequestParams params, HttpRequest httpRequest) {
        return httpRequest.host() + "/" + httpRequest.path();
    }

    /**
     * 根据注解的cacheKeys构建缓存的自定义key,
     * 如果返回null, 默认使用 url 和整个 query string 组成.
     *
     * @param params
     * @param cacheKeys
     * @return
     */
    @Override
    public String buildCacheKey(RequestParams params, String[] cacheKeys) {
        String cacheKey = null;
        if (cacheKeys != null && cacheKeys.length > 0) {

            cacheKey = params.getUri() + "?";

            // 添加cacheKeys对应的参数
            for (String key : cacheKeys) {
                String value = params.getStringParameter(key);
                if (value != null) {
                    cacheKey += key + "=" + value + "&";
                }
            }
        }
        return cacheKey;
    }

    /**
     * 自定义SSLSocketFactory
     *
     * @return
     */
    @Override
    public SSLSocketFactory getSSLSocketFactory() {
        return getTrustAllSSLSocketFactory();
    }

    /**
     * 为请求添加通用参数等操作
     *
     * @param params
     */
    @Override
    public void buildParams(RequestParams params) {

    }

    /**
     * 自定义参数签名（主要为了实现这个功能，且想使用注解，避免代码冗余）
     *
     * @param params
     * @param signs
     */
    @Override
    public void buildSign(RequestParams params, String[] signs) {
        List<KeyValue> list =  params.getQueryStringParams();
        List<String> keyList = new ArrayList<>();
        if (list == null || list.isEmpty()) {
            return;
        } else {
            for (KeyValue keyValue : list){
                if (keyValue != null && keyValue.key != null){
                    keyList.add(keyValue.key);
                }
            }
            Arrays.sort(keyList.toArray());
            StringBuilder stringBuilder = new StringBuilder();
            for (KeyValue keyValue : list) {
                if (keyValue != null && keyValue.key != null && keyValue.value != null) {
                    for(String key : keyList){
                        if (keyValue.key.equals(key)){
                            stringBuilder.append(keyValue.key)
                                    .append("=")
                                    .append(String.valueOf(keyValue.value))
                                    .append("&");
                        }
                    }
                } else {
                    return;
                }
            }
            String s = stringBuilder.deleteCharAt(stringBuilder.length() - 1).toString();
            params.addParameter("signStr", "s");
        }
    }

    private static SSLSocketFactory trustAllSSlSocketFactory;

    public static SSLSocketFactory getTrustAllSSLSocketFactory() {
        if (trustAllSSlSocketFactory == null) {
            synchronized (DefaultParamsBuilder.class) {
                if (trustAllSSlSocketFactory == null) {

                    // 信任所有证书
                    TrustManager[] trustAllCerts = new TrustManager[]{new X509TrustManager() {
                        @Override
                        public X509Certificate[] getAcceptedIssuers() {
                            return null;
                        }

                        @Override
                        public void checkClientTrusted(X509Certificate[] certs, String authType) {
                        }

                        @Override
                        public void checkServerTrusted(X509Certificate[] certs, String authType) {
                        }
                    }};
                    try {
                        SSLContext sslContext = SSLContext.getInstance("TLS");
                        sslContext.init(null, trustAllCerts, null);
                        trustAllSSlSocketFactory = sslContext.getSocketFactory();
                    } catch (Throwable ex) {
                        LogUtil.e(ex.getMessage(), ex);
                    }
                }
            }
        }

        return trustAllSSlSocketFactory;
    }

}
`
BaiduParams 使用：
`
BaiduParams params = new BaiduParams("test");
        params.wd = "xUtils";
        params.a = "a";
        params.b = "b";
`



希望能帮到其他人 减少代码冗余 ，提高开发效率（留给码农时间找妹子~~~~~~）

**Comment by mvpleung** [comment]
不定义属性一样可以使用 @HttpRequest注解 ， 定义属性适用公参，私有参数，还是要 addQueryStringParameter，除非你为每个接口定义一个自定义的RequestParams，显然不现实，一个公共的BaseRequestParams，添加公参属性，addQueryStringParameter 添加私有参数

**Comment by wyouflf** [comment]
方便理解, demo更新了
