### ISSUE TITLE
Selector.class没有过滤重复数据的distinct参数

### ISSUE THREAD

**Issue by wing2407** [wyouflf/xUtils3#175]
我想从数据库中提取不重复的字段数据,能在Selector.class中sql语句中加入distinct参数方法吗?提取出不重复数据要做循环判断,虽然加入时候也可以判断是否存在(也要循环判断).

**Comment by 247321453** [comment]
sql学好，group by 字段

**Comment by langren1353** [comment]
select函数中可以用distinct参数

**Comment by wyouflf** [comment]
public DbModelSelector select(String... columnExpressions)
