### ISSUE TITLE
请问如何精简Xutils3

### ISSUE THREAD

**Issue by fg2q1q3q** [wyouflf/xUtils3#176]
你好，请问我只想使用Xutils3里面的数据库操作部分，该如何精简？

**Comment by GISirFive** [comment]
我也遇到了同样的问题，我把除数据库之外的代码都删掉了，还剩common.task包下的东西不知道该不该删

**Comment by fg2q1q3q** [comment]
@GISirFive 如果你只是要用数据库的话，可以参考https://github.com/LuckyJayce/DBExecutor，这是在Xutils的基础上精简下来的

**Comment by GISirFive** [comment]
非常感谢！
