### ISSUE TITLE
RequestParams.getBodyParams()会清空请求参数

### ISSUE THREAD

**Issue by DrkCore** [wyouflf/xUtils3#177]
getBodyParams方法会回调checkBodyParams的方法，之中有一些类似下方的代码：

if (!bodyParams.isEmpty() &&(!HttpMethod.permitsRequestBody(method)|| !TextUtils.isEmpty(bodyContent)   || requestBody != null)) {
    queryStringParams.addAll(bodyParams);
    bodyParams.clear();
}

如你所见 ，在部分情况下该方法会清空bodyParams。

我想在自己的基类中通过getBodyParams按照自己的规范输出日志，但是这样又会清空所有的bodyParams参数；最终getBodyParams返回的是一个无用的List对象；而在3中该方法没有在任何地方被调用。

这是getBodyParams设计上的错误，还是只是我使用不当，望赐教。

**Comment by wyouflf** [comment]
params创建后可以先params.setMethod(HttpMethod.POST)

**Comment by DrkCore** [comment]
很高兴得到您的答复，不过现在已经没有这个问题了。我在项目经历推倒重做后自己用 OkHttp 封装了一套框架，目前工作良好。目前仍然在使用 xUtils3 的地方就只有数据库的模块了，我也将之独立抽取出来并封装起来了起来，如果有兴趣的话可以点这里看一下 [xMate3](https://github.com/DrkCore/xMate3)
