### ISSUE TITLE
Callback.ProgressCallback<Drawable>()

### ISSUE THREAD

**Issue by wishkity** [wyouflf/xUtils3#178]
Callback.ProgressCallback<Drawable>加载一个图片url，这个url的图片不存在，这个回调既不会执行onSuccess，也不会执行onError。

02-01 14:50:28.367 10275-10275/ E/TAG: onWaiting
02-01 14:50:28.397 10275-10275/ E/TAG: onStarted
02-01 14:50:28.427 10275-10275/ E/TAG: onLoading
02-01 14:50:28.717 10275-10275/ E/TAG: onLoading
02-01 14:50:28.757 10275-10275/ E/TAG: onLoading
02-01 14:50:28.767 10275-11454/ D/skia: --- SkImageDecoder::Factory returned null
02-01 14:50:28.767 10275-11454/ D/skia: --- SkImageDecoder::Factory returned null
02-01 14:50:28.767 10275-10275/ E/TAG: onFinished

url 值是 http://img2.imgtn.bdimg.com/it/u=.jpg

**Comment by duanchuan** [comment]
url 值是 http://img2.imgtn.bdimg.com/it/u=.jpg

**Comment by wyouflf** [comment]
已修复, 谢谢反馈
