### ISSUE TITLE
x.Ext.init

### ISSUE THREAD

**Issue by cxbiao** [wyouflf/xUtils3#18]
建议参数类型改为context,现在是application，感觉不方便

**Comment by wyouflf** [comment]
context容易误用, 可能传入Activity等, 会影响Activity的生命周期.
插件化工程可能自己包装context, 可能存在不适用的情况.

**Comment by cxbiao** [comment]
那你传application级别context的用意是什么呢？

**Comment by wyouflf** [comment]
* 创建数据库
* 获取屏幕分辨率, 图片采样等使用
* 访问Assets中的图片
* 获取应用内存信息等
* 获取应用私有路径, 创建缓存文件等

**Comment by cxbiao** [comment]
现在版本迭代太快了吧，究竟哪个是稳定版本？
