### ISSUE TITLE
使用过程中有个问题！

### ISSUE THREAD

**Issue by houfukude** [wyouflf/xUtils3#180]
使用event能否对addTextChangedListener进行注册事件呢？
如果能，应该是怎么使用 这是我目前的方法，无效～！

`    
@Event(value = R.id.user_name, type = TextWatcher.class, method = "afterTextChanged")
private void afterTextChanged(Editable s) { LogUtil.d(s.toString())}
`

**Comment by wyouflf** [comment]
@Event(
value = R.id.user_name, 
type = TextWatcher.class, 
method = "afterTextChanged", 
setter = "addTextChangedListener")

加上setter, 默认的setter是 "set" + ListenerClassName
