### ISSUE TITLE
Post请求、文件上传java.net.SocketException: sendto failed: ECONNRESET (Connection reset by peer)

### ISSUE THREAD

**Issue by homebei2** [wyouflf/xUtils3#182]
使用android-async-http 的post方式可以正常提交，但是xutils3不行。

RequestParams params = new RequestParams("http://www.xxxxx.com/iface/receive.php");
params.setMultipart(true);
        params.addBodyParameter(
                "uploadedfile",
                new File("/sdcard/image.jpg")); // 如果文件没有扩展名, 最好设置contentType参数.
        params.addParameter("num", "20150201123");
        params.addParameter("name", "qq");
        params.addParameter("phone", "15102995502");
        params.addParameter("type","10公里");
        params.addParameter("bsdate", "20160204");
        params.addParameter("cscity", "秦皇岛");
        params.addParameter("time", "1:20");
//        params.addBodyParameter(
//                "file2",
//                new FileInputStream(new File("/sdcard/test2.jpg")),
//                "image/jpeg",
//                // 测试中文文件名
//                "你+& \" 好.jpg"); // InputStream参数获取不到文件名, 最好设置, 除非服务端不关心这个参数.
//        x.http().post(
        x.http().request(HttpMethod.POST,
                params, new Callback.CommonCallback<String>() {
            @Override
            public void onSuccess(String result) {
                Toast.makeText(x.app(), result, Toast.LENGTH_LONG).show();
            }

```
        @Override
        public void onError(Throwable ex, boolean isOnCallback) {
            Toast.makeText(x.app(), ex.getMessage(), Toast.LENGTH_LONG).show();
        }

        @Override
        public void onCancelled(CancelledException cex) {
            Toast.makeText(x.app(), "cancelled", Toast.LENGTH_LONG).show();
        }

        @Override
        public void onFinished() {

        }
    });
```

**Comment by whybux** [comment]
我也碰到了这个问题，偶尔的，不过重现了好多次了。

**Comment by chenyingqiao** [comment]
这个是服务器的问题
吧php和服务器的上传文件限制搞大点就好了
