### ISSUE TITLE
xutils3使用Digest验证的方法

### ISSUE THREAD

**Issue by rachelhq** [wyouflf/xUtils3#191]
需要使用digest验证，xutil2使用起来比较方便，可以使用httpclient；
但是xutils3好像用起来比较麻烦，现在使用的方式如下：

1、首先需要使用异步调用方式：
x.http().post(requestParams, new CustomCallback());

2、CustomCallback 需要继承 InterceptRequestListener，才能在afterRequest(UriRequest request)回调中拿到response中header "WWW-Authenticate"的值

3、需要digest验证的请求，第一次post之后会回调onError(Throwable ex, boolean isOnCallback)；
在该回调方法中判断httpcode是否为HTTP_UNAUTHORIZED，是的话自己拼接DigestAuth字符串authString，并且在requestparams中加入新的header：
requestParams.addHeader("Authorization", authString);

4、再一次调用x.http().post(requestParams, new CustomCallback());

这么使用起来有几个限制：必须使用异步方式调用，必须继承InterceptRequestListener，必须在onerror中自己拼接验证heder。。。

请问有没有比较方便的方式？多谢

**Comment by wyouflf** [comment]
自动以ParamsBuilder, 看示例代码:
https://github.com/wyouflf/xUtils3/blob/master/sample/src/main/java/org/xutils/sample/http/JsonDemoParams.java

https://github.com/wyouflf/xUtils3/blob/master/sample/src/main/java/org/xutils/sample/http/JsonDemoParamsBuilder.java

如果需要在HTTP_UNAUTHORIZED的时候重试, 那么在ParamsBuilder#buildParams方法中加入params.setHttpRetryHandler(.....), 自定义重试机制: 加入的验证字段, canRetry返回true. 

这样就不必在callback中关心参数和错误重试的问题, 也不用再次发送请求, 重试是自动的.

**Comment by rachelhq** [comment]
好的，多谢回答。有几个问题：
1.httpurlconnection有比较方便的方式实现digest auth么？

2.如果没有
按照以上方式，digest验证的信息还需要自己去组装吧？
得在第一次请求失败，发送第二次请求之前组装，并在request的header中加header：addHeader("Authorization", authString);
如果直接通过retry来重试， 这种request的修改可以在自动重试的时候使用上吗？

3.JsonResponseParser只有在请求成功的情况下才会调用，失败的情况下是不会调用的，所以如果需要拿到reponse的header，callback还是必须implements InterceptRequestListener？


多谢

**Comment by zoe1623** [comment]
xutils3如何下载文件?好像不支持啊?

**Comment by shengguan** [comment]
刚用，报javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.  查了下是找不到证书错误，但我没用https，求解，谢谢

**Comment by lanaiver** [comment]
x.http().get(....)重复提交多次请求，如果关闭之前请求，只继续最后一个请求

**Comment by kuangqin** [comment]
总是报找不到jar包是怎么回事啊？

**Comment by kuangqin** [comment]
总是报找不到jar包是怎么回事啊？

**Comment by kuangqin** [comment]
总是报找不到jar包是怎么回事啊？

**Comment by kuangqin** [comment]
总是报找不到jar包是怎么回事啊？

**Comment by kuangqin** [comment]
总是报找不到jar包是怎么回事啊？

**Comment by combing520** [comment]
HTTP  请求怎样设置请求超时时间？ 你这边的默认超时时间好像是15秒。

**Comment by xmrkwzw** [comment]
同样用addbodyParamter传file   为什么2的可以3 不行呢？？服务器该怎么接收呢？

**Comment by jicg** [comment]
post的请求有点问题吧，发送参数到服务器，后台接收不到啊。

**Comment by hxkdidi** [comment]
经常出现socketTimeout，我设置超时时间是7s,但是出现这个错误基本在发出请求的1，2s内，比较困惑！

**Comment by wyouflf** [comment]
> 同样用addbodyParamter传file 为什么2的可以3 不行呢？？服务器该怎么接收呢？

setMultipart(true)试试， 默认只有一个body参数，并且是文件类型是使用普通的文件表单上传。

**Comment by xuxueli982** [comment]
x.http().get(params, new Callback.CacheCallback<String>() {}方法连接不到后端服务器有可能是哪里出错了，请问一下
