### ISSUE TITLE
NoClassDefFoundError:org.xutil.http.request.HttpRequest

### ISSUE THREAD

**Issue by Easonzero** [wyouflf/xUtils3#193]
非常悲剧的撞上了这个错误，查了半天无果，只好向你请教了。
在http各种请求都发不出去，返回的异常是NoClassDefFoundError:org.xutil.http.request.HttpRequest。这个类jar包里是存在的，不道为甚运行时找不到这个类。求大神解救。

**Comment by a451114984** [comment]
在这个调用http api的activity里重新调用x.ext.init,就正常了。完全懵b》。。。

**Comment by BlackJackLi** [comment]
会不会是你没有在Applcation类里面初始化xUtils,应该不能在Activity初始化

**Comment by JerrryLiu** [comment]
MayBe是你在Application 类中Oncread 函数没有初始化！

**Comment by TestSmirk** [comment]
我也是这个问题,后来发现在mainfest中没有定义Application的类名...
