### ISSUE TITLE
注入静态view的问题

### ISSUE THREAD

**Issue by JustinChiang123** [wyouflf/xUtils3#194]
extends Fragment，在代码里面有个
`@ViewInject(R.id.f_chat_ptrslv)`
`private static PullToRefreshSwipeListView m_ptrslv;`
结果m_ptrslv是空。
如果删掉static 则非空。

**Comment by TAUnionEd** [comment]
同样是extends Fragment
`    @ViewInject(R.id.debug_step_cache)
    private TextView mDebugStepCache;`
结果mDebugStepCache为空……删了static都没有用囧

**Comment by wyouflf** [comment]
不支持静态view注入
