### ISSUE TITLE
安卓6.0中使用无法显示layout

### ISSUE THREAD

**Issue by XVNYATA** [wyouflf/xUtils3#197]
一进去就是白色一片

APPLICATION已注册
已在application中初始化xutils3
正确语法

**Comment by shanhaojie** [comment]
我的基于6.0开发的也是一片空白

**Comment by Nbility** [comment]
03-09 11:59:48.160 3642-3642/com.zealer.budejie
E/x_log:ViewInjectorImpl.injectObject(L:167): Invalid id(2131493003) for
@ViewInject!BaseInnerPager

                  java.lang.RuntimeException: Invalid id(2131493003) for
@ViewInject!BaseInnerPager

请问这个问题怎么解决呢

2016-02-26 13:52 GMT+08:00 shanhaojie <notifications@github.com>:

**Comment by wyouflf** [comment]
试试新版本， 示例是基于Android 9.0
