### ISSUE TITLE
BaseParams的toString方法拼接的字符串不正确

### ISSUE THREAD

**Issue by BlackJackLi** [wyouflf/xUtils3#198]
在发布版3.3.16的源码中,BaseParams的toString方法有以下语句
      for (KeyValue kv : queryStringParams) {
                sb.append("&").append(kv.key).append("=").append(kv.value);

            }
            sb.deleteCharAt(sb.length() - 1);
其中  sb.deleteCharAt(sb.length() - 1);会把最后一个字符删;这样的错误在toString里面有两处地方,当我想打印出日志又不想自己拼接参数的时候发现的T-T.
我想作者应该是想删最后一个多出来&,但是实际上你写的拼接语法会让字符串第一个字符是&,这个才是多余的;应该删除第一个;

**Comment by wyouflf** [comment]
谢谢反馈, 已修复

**Comment by BlackJackLi** [comment]
辛苦了,看来大家都是夜行动物啊^_^ 




coderblackjack@foxmail.com
 
发件人： wyouflf
发送时间： 2016-02-24 01:02
收件人： wyouflf/xUtils3
抄送： BlackJackLi
主题： Re: [xUtils3] BaseParams的toString方法拼接的字符串不正确 (#198)
谢谢反馈, 已修复
