### ISSUE TITLE
当服务器返回的图片URL带有时间戳时，缓存会失效

### ISSUE THREAD

**Issue by ju5t4fun** [wyouflf/xUtils3#199]
服务器返回的图片链接后面带着时间戳，形如：
`http://img.xxxxxx.com/xx/xxxx.jpg?t=1456231864`
每请求一次，后面的`?t=1456231864`都会变化，导致缓存失效
请问这种情况怎么解决，或者有什么方法可以自定义缓存时的key吗？

**Comment by mvpleung** [comment]
带上时间戳就表示是一个新的URL地址

1.服务端不要携带时间戳返回
2.自己过滤URL地址

还是建议服务端来处理，携带时间戳已经改变了URL
