### ISSUE TITLE
建议修改一下ViewUtils的注入异常检测

### ISSUE THREAD

**Issue by lyx32** [wyouflf/xUtils3#2]
因为用ViewUtils注入的时候，加入注入内容有误，或者找不到。他的提示很不友好，很不容易定位到有问题的某个属性。
下面是我自己修改的代码，望有帮助。
View findView = finder.findViewById(viewInject.value());
				if (findView != null) {
					field.setAccessible(true);
					try {
						field.set(object, findView);
					} catch (Throwable e) {
						String modifier = Modifier.toString(field.getModifiers());
						String genericString[] = field.toGenericString().split(" ");
						String type = genericString[1];
						String name = field.getName();
						String injectViewName = findView.getClass().toString().replaceFirst("class", "");
						LogUtils.e(modifier + " " + type + " " + name + " 将要注入" + injectViewName);
					}
				} else {
					String modifier = Modifier.toString(field.getModifiers());
					String genericString[] = field.toGenericString().split(" ");
					String type = genericString[1];
					String name = field.getName();
					LogUtils.e(modifier + " " + type + " " + name + " 注入id无效");
				}

**Comment by wyouflf** [comment]
谢谢反馈, 已处理 https://github.com/wyouflf/xUtils3/commit/ac4a343f30038793476cbac90de66d459a3c5a02
