### ISSUE TITLE
downloadcallback 弱引用带来的问题

### ISSUE THREAD

**Issue by zhimin115200** [wyouflf/xUtils3#20]
我看源码里面，将回调设置成了弱引用，而弱引用随时可能被gc回收，所以可能导致接收不到回调信息？在下载大文件时，下载一段时间前台就接受不到回调信息了。小文件还好，我改成强引用就行了，请问为啥设计成弱引用呢？新人求教
private WeakReference<DownloadViewHolder> viewHolderRef;

**Comment by wyouflf** [comment]
UI组件被销毁时, 不在通知UI, 后台下载就行了.
但是UI组件被重新创建时要再次关联callback.

强引用会使UI组件的引用无法正常销毁.

当然你也可以修改为其他策略, 如果UI组件被销毁用toast提示等.
sample里的代码只是一个简单的api示例, 不代表最佳实践.
