### ISSUE TITLE
3.0post提交问题

### ISSUE THREAD

**Issue by JustinChiang123** [wyouflf/xUtils3#200]
问题再现：
`params.addBodyParameter(key, value);`
`params.addBodyParameter(key, value);`
`..`
`..`
`params.addBodyParameter(key, value);`
`params.addBodyParameter(key, value);`
`x.http().post(params, new Callback.CommonCallback<String>() {...}`
当我满足（一种参数很长，类似小列表的json格式，另外一种params参数特别多）参数的时候，post提交上去的数据，后台解析出来所有的参数都没有放到post的body里面去。而实际上参数放在url上去了。

**Comment by wyouflf** [comment]
只有用get请求时才强制将参数加到url, 如果有问题尝试更新到最新稳定版.

**Comment by chenfei0928** [comment]
问题复现，在请求发出现调用RequestParams的toString方式打印的话，请求的BodyParameter就会被插入到QueryStringParameter里面
