### ISSUE TITLE
xUtils 3 上传文件，怎么监听上传进度？

### ISSUE THREAD

**Issue by Genng** [wyouflf/xUtils3#205]
public interface ProgressCallback<ResultType> extends CommonCallback<ResultType> {
        void onWaiting();

```
    void onStarted();

    void onLoading(long total, long current, boolean isDownloading);
}
```

监听不到呀，这个方法

**Comment by lwjsdsbr** [comment]
new Callback.ProgressCallback<String> 使用这个callback

**Comment by caopeng000** [comment]
请问支持断点上传嘛，比如一开始上传了10%，后来网络断了，等有网络的时候继续从那10%接着上传，求支持，谢谢

**Comment by bacy** [comment]
这个需要服务端支持，每次上传前，先检验文件的md5，确保本地和服务端文件一致，然后让服务端告诉你上次你传到哪了，然后你跳到那个地方开始上传

**Comment by caopeng000** [comment]
意思是现在xUtils支持文件断点上传了吗？怎么使用啊，

**Comment by lion7perlman** [comment]
同问~

**Comment by HelloLollipop** [comment]
没有提供上传的监听

**Comment by wyouflf** [comment]
断点上传需要服务端提供查询进度的接口
