### ISSUE TITLE
x.image().bind

### ISSUE THREAD

**Issue by wm4252** [wyouflf/xUtils3#209]
```
x.image().bind(imageview1, "http://pic.baike.soso.com/p/20090711/20090711101754-314944703.jpg", imageOptions);报java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)错。
```

**Comment by wulijie** [comment]
你加权限了吗？
或者这张图本身就不让下载

在 2016-03-02 09:15:06，"wm4252" <notifications@github.com> 写道：

x.image().bind(imageview1, "http://pic.baike.soso.com/p/20090711/20090711101754-314944703.jpg", imageOptions);报java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)错。

**Comment by wm4252** [comment]
加权限了，图片本身可以下载的。用x.image().bind下载会报错
