### ISSUE TITLE
断点续传策略

### ISSUE THREAD

**Issue by cxbiao** [wyouflf/xUtils3#21]
断点续传策略需要服务器配合吗？比如上传一半失败了，下次可以继续上传？

**Comment by wyouflf** [comment]
断点下载需要服务端支持标准的RANG参数策略.
断点上传没有标准协议, 一般可以这么做:
1. 参数查询: 客户端将要上传的文件的MD5和其他描述信息给服务端, 服务端根据MD5查询已经上传的进度等信息返回给客户端.
2. 开始上传: 客户端再次请求, 根据返回的进度值, 使用文件流跳过已上传部分, 赋给请求参数, 继续上传.
上传中的其他参数根据需求自己定义.
