### ISSUE TITLE
升级到3.3.20后，导包都报错

### ISSUE THREAD

**Issue by FuXiangGit** [wyouflf/xUtils3#210]
Android studio导入compile 'org.xutils:xutils:3.3.20'后，原来所有的XUtils3对应的import都报错
原来版本compile 'org.xutils:xutils:3.1.26'和compile 'org.xutils:xutils:3.2.0'

**Comment by haoweizero** [comment]
我的3.3.2导入也报错，找不到注解包。

**Comment by wooi** [comment]
直接下载jar包也是不能用

**Comment by haoweizero** [comment]
eclipse还需要so文件，我这边用的是as，不知道怎么把项目导入进去。

**Comment by bxfx111** [comment]
把原来的引用替换掉就好

**Comment by JerrryLiu** [comment]
@bxfx111 Clean 下项目

**Comment by xiyangyang8110** [comment]
x.Ext.init(this); x爆红
