### ISSUE TITLE
post请求参数中的“+”“=”等符号的自动转码

### ISSUE THREAD

**Issue by kerry-zhou** [wyouflf/xUtils3#212]
RequestParams params = new RequestParams("http://192.168.0.13:8080/upload");
params.addBodyParameter("xx","+Sdsdf=");
//params.addQueryStringParameter("xx","+Sdsdf=");
x.http().post(params,responseHandler);

params输出为：http://192.168.0.13:8080/upload?&xx=%2Sdsdf%3 

params多出一个&符号，并且+跟=自动转码了，请问要怎么设置才能保持符号不被转换

**Comment by wyouflf** [comment]
升级到最新版, params.toString的格式变了
