### ISSUE TITLE
Selector.groupBy 不解

### ISSUE THREAD

**Issue by JustinChiang123** [wyouflf/xUtils3#215]
从低版本升级到3.0
`Selector<Message> from = getDb().selector(Message.class);`
`from.groupBy("friend_id");`
`ArrayList<String> values = new ArrayList<String>();`
`values.add("2");`
`values.add("4");`
`values.add("5");`
`values.add("88");`
`values.add("19");`
`values.add("20");`
`values.add("15");`
`values.add("86");`
`from.where(WhereBuilder.b("message_type", "IN", values));`
`from.orderBy("id");`
`msglist = from.findAll();`
这段代码groupby 会失效。

简单修改源码：
`public DbModelSelector groupBy(String columnName) {`
`return new DbModelSelector(this, columnName);`
`}`

`public DbModelSelector groupBy(String columnName) {`
`this.groupByColumnName = columnName;`
`return new DbModelSelector(this, columnName);`
`}`

toString()里面加入
`if (!TextUtils.isEmpty(groupByColumnName)) {`
`result.append(" GROUP BY ").append("\"").append(groupByColumnName).append("\"");`
`}`

问题解决。
问下，`DbModelSelector`个人感觉其实并没有 `Selector<T>` 好用，怎么不将groupBy()稍微处理一下呢？

**Comment by wyouflf** [comment]
谢谢反馈, 已经支持
