### ISSUE TITLE
xutils3支持gzip解析吗？

### ISSUE THREAD

**Issue by liubo123** [wyouflf/xUtils3#219]
没有找到xutils3的gzip解析，在线等

**Comment by cyschensitao** [comment]
一直乱码，不知道怎么解决，拿到的head不是1f8b。

**Comment by shxdos** [comment]
同问

**Comment by wingsum93** [comment]
why not use okhttp. it suppor in client slide
[https://github.com/square/okhttp](here)

**Comment by wyouflf** [comment]
默认支持
