### ISSUE TITLE
怎么Post提交 String Json 到后台，非表单那种？

### ISSUE THREAD

**Issue by WZero** [wyouflf/xUtils3#221]
怎么Post提交 String Json 到后台，非表单那种？ 

有 API 吗？

**Comment by janecer** [comment]
同问，而已key是一个String型的data，value是一个Json格式的字符串。试了addBodyPa..,addPa..,setBodyContent都有问题，但换一个AsynHttpClient就可以

**Comment by ehaahe** [comment]
自定义requestParams子类，设置一个值就好

**Comment by 247321453** [comment]
RequestParams.setAsJsonContent(true)

**Comment by JoeWic** [comment]
我遇到和2楼一样的问题了，请问怎么解决

**Comment by JoeWic** [comment]
我遇到和2楼一样的问题了，请问怎么解决

**Comment by wyouflf** [comment]
RequestParams.setAsJsonContent(true)
