### ISSUE TITLE
添加下载失败

### ISSUE THREAD

**Issue by dongyu7136** [wyouflf/xUtils3#224]
try {
                        downloadManager.startDownload(
                                downloadInfo.getUrl(),
                                downloadInfo.getLabel(),
                                downloadInfo.getFileSavePath(),
                                downloadInfo.isAutoResume(),
                                downloadInfo.isAutoRename(),
                                this);
                    } catch (DbException ex) {
                        Toast.makeText(x.app(), "添加下载失败", Toast.LENGTH_LONG).show();
                    }

**Comment by wyouflf** [comment]
请提供错误日志
