### ISSUE TITLE
怎么方便的拿到response header？

### ISSUE THREAD

**Issue by jyh149129** [wyouflf/xUtils3#227]
怎么方便的拿到response header？

**Comment by wyouflf** [comment]
callback参数实现实现RequestInterceptLintener接口

**Comment by yaobaohua** [comment]
@wyouflf 能提供怎么拿到Response header这些东西的方法吗？

**Comment by ZoroYouth** [comment]
@wyouflf  RequestInterceptLintener这个不是拦截请求么，怎么获取到response？UriRequest中貌似没看到有response

**Comment by ZoroYouth** [comment]
哦，抱歉，UriRequest中确实有ResponseHeader
