### ISSUE TITLE
服务器返回http状态码204，文件还是会被下载的问题

### ISSUE THREAD

**Issue by jyh149129** [wyouflf/xUtils3#228]
我们需要下载个图片文件到手机sd上存储起来，服务器端是通过返回200和204来控制是否需要重新下载，如果200服务器端直接输出图片流，204输出流就为空，但发现xutils不会根据response code，来控制下载流程，服务器即使返回204状态码，下载动作还是会被执行，导致已有文件被覆盖为0字节，原来的2.x版本是正确的

**Comment by wyouflf** [comment]
204错误已处理
