### ISSUE TITLE
java.lang.NoClassDefFoundError: 

### ISSUE THREAD

**Issue by hellosilence** [wyouflf/xUtils3#23]
x.http().get(requestParams, new Callback.CommonCallback<String>() ，使用这个方法时会报错：
java.lang.NoClassDefFoundError: org/xutils/http/request/HttpRequest

**Comment by wyouflf** [comment]
在application里初始化了吗, 调试一下.

**Comment by hellosilence** [comment]
@wyouflf 今天重新试了一下正常了，感谢作者！
