### ISSUE TITLE
NoClassDefFoundError: org.xutils.http.request.HttpRequest

### ISSUE THREAD

**Issue by Armyoftheworld** [wyouflf/xUtils3#230]
我在Android 2.3的模拟器上用这个网路框架，报这个错误，请问怎么解决？我直接吧项目下载下来把minSdkVersion改成10.

**Comment by linilq** [comment]
你可以试试把源码弄到android studio中，修改一下HttpRequest里面初始化CookieManager为null；我之前也遇到这样的问题，一开始报你说的这个错误，后来重新clean跟踪发现是那个manager初始化有异常。当然这样修改只是权宜之计，还看作者怎么弄，毕竟我还没看懂代码.......

**Comment by 247321453** [comment]
作者说了支持api14之后

**Comment by Armyoftheworld** [comment]
我发邮件给作者了，他说以后不再支持2.3了
