### ISSUE TITLE
文件上传

### ISSUE THREAD

**Issue by macyer** [wyouflf/xUtils3#231]
上传代码：
`RequestParams params  = new RequestParams(“http://d.bjyijiequ.com/qpi/rest/yjqtest/testUploadImageFile”);
File file = new File(Environment.getExternalStorageDirectory()+"/shared/Image");
mFiles = file.listFiles();
params.addParameter("content", mFiles[0]);
params.setMultipart(true);
params.setAutoResume(true);
x.http().post(params, new Callback.ProgressCallback<String>()`
服务器端代码：
`@POST
    @Path("testUploadImageFile")
    @Produces(MediaType.APPLICATION_JSON)
    public String uploadImageFile(@FormParam("content") String content) {
        String result = "0";
        FileOutputStream out = null;
        try {
            logger.info("接收参数：" + content);
            String filepath = "/home/tomcat/logs/" + UUID.randomUUID().toString() + ".jpg";
            InputStream inStream = request.getInputStream();
            byte[] data = readInputStream(inStream);
            File imageFile = new File(filepath);
            FileOutputStream outStream = new FileOutputStream(imageFile);// 创建输出流
            outStream.write(data);// 写入数据
            outStream.close();
            logger.error("写入图片文件完成：" + filepath);
            result = "1";
        } catch (Exception e) {
            logger.error("写入图片文件出错！" + e.toString());
        } finally {
            try {
                out.close();
            } catch (Exception e) {
                logger.error("关闭对象文件出错！" + e.toString());
            }
        }
        return result;
    }
`
返回结果：
`03-18 18:17:34.928: E/x_log:HttpRequest.sendRequest(L:219)(27690): code: 400, msg: Bad Request, result: , url: http://d.bjyijiequ.com/qpi/rest/yjqtest/testUploadImageFile`
然后使用你提供的工具类提示为下：
`代码：//图片上传地址
        String url="http://d.bjyijiequ.com/qpi/rest/yjqtest/testUploadImageFile";
        File file = new File(Environment.getExternalStorageDirectory()+"/shared/Image");
        mFiles = file.listFiles();
        Map<String,Object> map=new HashMap<>();
        //传入自己的相应参数
        //map.put(key, value);
        map.put("content", mFiles[0]);
        XUtil.UpLoadFile(MainActivity.this ,url, map, new MyCallBack<String>()`
结果为：
`03-18 18:29:11.019: E/x_log:HttpRequest.sendRequest(L:219)(31059): code: 405, msg: Method Not Allowed, result: , url: http://d.bjyijiequ.com/qpi/rest/yjqtest/testUploadImageFile`

请大神看一下怎么回事，刚接触安卓，服务端代码是同事写的我拷贝过来的
另外，各位大神如果有什么要发送的话请发邮箱：43453186@qq.com

**Comment by wyouflf** [comment]
setmultipart(false)也试试
