### ISSUE TITLE
 x.image().bind 能否设置只读缓存里的，不请求网络

### ISSUE THREAD

**Issue by tigerphz** [wyouflf/xUtils3#232]
x.image().bind 能否设置只读缓存里的，不请求网络，因为正在滑动RecyclerView的时候，如果有缓存图片就显示，不需要请求网络，如果在滑动中请求网络图片有点卡

**Comment by 247321453** [comment]
使用内存缓存，options设置一下

**Comment by xanaduo** [comment]
默认就使用了的

**Comment by wyouflf** [comment]
试试新版本, 丝般顺滑
