### ISSUE TITLE
请问xUtils 3.+ 是怎么混淆的？

### ISSUE THREAD

**Issue by SmileChen007** [wyouflf/xUtils3#236]
请问xUtils 3.+ 是怎么混淆的？

**Comment by ghordonn** [comment]
-keep public class org.xutils.** {
      public protected *;
  }
  -keep public interface org.xutils.** {
      public protected *;
  }
  -keepclassmembers class * extends org.xutils.** {
      public protected *;
  }
  -keepclassmembers @org.xutils.db.annotation.* class * {*;}
  -keepclassmembers @org.xutils.http.annotation.* class * {*;}
  -keepclassmembers class * {
      @org.xutils.view.annotation.Event <methods>;
  }
