### ISSUE TITLE
添加下xUtils3 之后, 导致项目无法 load jni 库

### ISSUE THREAD

**Issue by lixingmao** [wyouflf/xUtils3#238]
添加xUtils 的依赖之后, 项目 jni 库加载一直失败, 报异常, 多方排查, 发现是 xUtils 的依赖导致, 请问是什么请, 有办法解决吗? 

// 导入本地函数库
	static {
		try {
			System.loadLibrary("hzx_pinyin");
		} catch (UnsatisfiedLinkError ule) {
			Log.e(TAG, "WARNING: Could not load hzx_pinyin natives");
		}
	}

**Comment by wyouflf** [comment]
xUtils中的so怎么会和hzx_pinyin冲突, 很奇怪

**Comment by lixingmao** [comment]
已经解决了, 项目中没有添加 armeabi-v7a 的 so 包, 但是 Xutils 里边有对应的 so 包, 因此 v7a 的机型, 到对应的目录无法找到自己的 hzx_pin.so. 添加对应armeabi-v7a 的 so 包即可.
