### ISSUE TITLE
还是cancel问题

### ISSUE THREAD

**Issue by cr1944** [wyouflf/xUtils3#24]
请问：
1.setCancelFast的作用是什么？
2.setCancelFast设为true，设置线程池的max size为1，当A下载任务在执行中，B下载任务等待中，cancel B任务时，并不会立即执行B任务回调，等到A任务执行完后或cancel A任务后才回调，如何优化？
补充：
取消下载时，cancel会调用两次
E/x_log:DownloadManager.stopDownload(L:156): stopDownload
E/x_log:DownloadCallback.cancel(L:106): cancel
E/x_log:DownloadCallback.cancel(L:106): cancel

**Comment by wyouflf** [comment]
谢谢反馈, 以优化, 更新到v3.0.4
