### ISSUE TITLE
图片加载时乱码  errorCode: 206, 

### ISSUE THREAD

**Issue by SmileChen007** [wyouflf/xUtils3#241]
E/x_log:ImageLoader.onError(L:440): errorCode: 206, msg: Partial Content, result: PNG
![Uploading QQ图片20160325104356.png…]()

**Comment by Kerwin92** [comment]
+1
������0Exif����MM��*��������1����������������������www.meitu.com������C��
                                                                                        
                                                                                        
                                                                                        �����������}��!1AQa"q2���#B��R��$3br�	
                                                                                        %&'()*456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz�������������������������������������������������������������������������������������������	
                                                                                        ���������w��!1AQaq"2�B����	#3R�br�
                                                                                        ����":,���)�⟵]G�b94�������Hw�r�Zʽca�Us���i���'�ɣ�����j|�by/�G2��)��c/l�{��e��@�fޫ�`�۞�� A����@��s�2@:P�hx���K܂6���Ra�ݘ�M�pP��<)3o�&�h%�SH��LcB�EX]��X]�Ҥ��H����f������Sq1qJ�Ǥe���'b����Fcޡ+�6B��P��c�v"oj�@�֩���i�GTX�����E,�fW�P�z
                                                                                        �����!f9
                                                                                        /b�k�I�2 =����s<%H��"��q��{0��kER���*�!}#N�$���MB55M�V����+^��C��"�C�����V*��Gݕ��������6X��Dk�;��+}I����oK�!}"��ʴn1�Jr+�t��6�zsWL�+uۇ�������W3�G}ɧ�������SM�������	�H��<֊L�������g�T���*��2]QZO	ݯ�� �4�ͣ���l�6�uw[��\��M���b��e�3u8���_J|��YezUs1�'�)���ٞ���U�0ۑڝ�i��)�

**Comment by SimplySu** [comment]
+1
感觉和最新的修改有关。
目前网络图片成功获取有时候会返回206的返回码，但是被当成了错误码。
HttpRequest.java

// check response code
responseCode = connection.getResponseCode();
if (responseCode >200)//以前这里为>0=300
{
……
throw httpException;
}

**Comment by pickyourself** [comment]
我的也出现这个错误了

**Comment by pickyourself** [comment]
请求类似于这种地址是会出现这种错误 http://ww2.sinaimg.cn/large/a15b4afegw1f2ckrf0p24j20ku082q5k

**Comment by SmileChen007** [comment]
貌似是版本的问题 ，我将到3.3.22就行了
