### ISSUE TITLE
断点续传进度问题99%

### ISSUE THREAD

**Issue by myqhit** [wyouflf/xUtils3#248]
断点续传暂停后下一次请求的后续的数据会多请求CHECK_SIZE个字节，
在匹配是否是同一个文件后，真正写入文件的字节数应该减去CHECK_SIZE，否则后面的total计算有误，始终比真实文件大CHECK_SIZE个字节。
建议修改：
     byte[] fileCheckBuffer = IOUtil.readBytes(fis, filePos, CHECK_SIZE);
     byte[] checkBuffer = IOUtil.readBytes(in, 0, CHECK_SIZE);
     contentLength=contentLength-CHECK_SIZE; //在这里加这一行，保证文件大小计算一致。

**Comment by wyouflf** [comment]
好的, 谢谢反馈
