### ISSUE TITLE
xutil网络请求怎么封装进一个方法,直接返或  onSuccess里的result

### ISSUE THREAD

**Issue by liupeng110** [wyouflf/xUtils3#253]

**Comment by liupeng110** [comment]
同步请求   怎么封装一下.

**Comment by ehaahe** [comment]
同步版本用带Sync后缀的请求方式就行，具体看例子

**Comment by liupeng110** [comment]
同步请求是不是搞的太麻烦了啊   还必须要传进去  一个Class<T>  
还要继承response  还要实现个什么parser
洪杨有篇博客 把okhttp  同步请求封装了一下 直接返回一个response类 直接取body就可以
我上代码，你们一看就知道了
                  Response  response = OkHttpUtils
					.post()
					.url("http://127.0.0.1:8001/aa/UserLogin/")
					.addParams("mobile", "13937113477")
					.addParams("password", "123456789123")
					.build().execute();

**Comment by liupeng110** [comment]
sample例子里没见同步请求啊

**Comment by wyouflf** [comment]
ReturnType ret = x.http().postSync(params, ReturnType.class)
