### ISSUE TITLE
onEvent覆盖问题

### ISSUE THREAD

**Issue by zhzephi** [wyouflf/xUtils3#255]
A类继承B类，A类绑定了组件（R.id.btn）onEvent方法，B类也绑定了组件（R.id.btn）onEvent方法。为什么起作用的是B类，不是子类要重写父类的方法吗？怎么父类覆盖了子类？

**Comment by wyouflf** [comment]
父类绑定了事件的方法, 调用一个可重写的方法给子类重写.
