### ISSUE TITLE
关于获取图片验证码cookie的问题

### ISSUE THREAD

**Issue by whybux** [wyouflf/xUtils3#259]
我们的获取图片验证码需要使用cookie。
我看了下图片的加载在创建createRequestParams(url, options)里面设置了params.setUseCookie(false);禁用了cookie，我需要怎么弄才能在加载图片验证码的时候使用cookie呢？

**Comment by whybux** [comment]
我的解决方案是以下载文件的方式下载图片，然后加载图片

**Comment by androidxiaobai** [comment]
final ImageOptions.ParamsBuilder builder = new ImageOptions.ParamsBuilder() {
            @Override
            public RequestParams buildParams(RequestParams params, ImageOptions options) {
                params.setUseCookie(true);
                return params;
            }
        };
        ImageOptions options = new ImageOptions.Builder()
                .setParamsBuilder(builder)
                .build();
这样就能使用cookie了
