### ISSUE TITLE
x.image().bind();加载图片不显示

### ISSUE THREAD

**Issue by modoxie** [wyouflf/xUtils3#262]
x.image().bind();加载图片不显示，debug进不去回调断点，出现时间2016-4-8 18:26:47
I/dalvikvm: Could not find method java.net.HttpURLConnection.setFixedLengthStreamingMode, referenced from method org.xutils.http.request.HttpRequest.sendRequest
W/dalvikvm: VFY: unable to resolve virtual method 49406: Ljava/net/HttpURLConnection;.setFixedLengthStreamingMode (J)V
D/dalvikvm: VFY: replacing opcode 0x6e at 0x02af
D/dalvikvm: GC_CONCURRENT freed 1412K, 7% free 21290K/22852K, paused 1ms+15ms, total 30ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 6ms
D/dalvikvm: Trying to load lib /data/app-lib/com.wine-1/libwebpbackport.so 0xa6a98cd8
D/dalvikvm: Added shared lib /data/app-lib/com.wine-1/libwebpbackport.so 0xa6a98cd8
I/android.backport.webp:native: JNI_OnLoad completed
D/skia: --- SkImageDecoder::Factory returned null

**Comment by modoxie** [comment]
x.image().bind(iv,"http://img2.imgtn.bdimg.com/it/u=1457437487,655486635&fm=11&gp=0.jpg");
找了一张百度上的图片写了个dome也不显示，建议周五下午4点后复现

**Comment by wyouflf** [comment]
已修复
