### ISSUE TITLE
建议在ImageOptions添加控制是否使用cookie的参数

### ISSUE THREAD

**Issue by youzai001** [wyouflf/xUtils3#263]
目前xutils3在加载图片时禁用了cookie,但是有时候是确实是需要cookie的.建议可以通过设置ImageOptions启用.

**Comment by wyouflf** [comment]
可以使用ImageOptions.Buidler#setParamsBuilder自定义

**Comment by youzai001** [comment]
谢谢，可以了

**Comment by androidxiaobai** [comment]
我想问一下如何设置

**Comment by androidxiaobai** [comment]
final ImageOptions.ParamsBuilder builder = new ImageOptions.ParamsBuilder() {
            @Override
            public RequestParams buildParams(RequestParams params, ImageOptions options) {
                params.setUseCookie(true);
                return params;
            }
        };
        ImageOptions options = new ImageOptions.Builder()
                .setParamsBuilder(builder)
                .build();
搞定了谢谢，我看源码发现ImageOptions的ParamBuilder是一个接口 用一个匿名内部类实现它，设置使用cookie就搞定了
