### ISSUE TITLE
创建数据库时候就初始化默认数据问题

### ISSUE THREAD

**Issue by hymanme** [wyouflf/xUtils3#264]
向表中添加数据时候才会判断数据表存在与否，然后创建表，
我在监听数据表创建setTableCreateListener里面对表初始化数据，但是只有在我手动添加一条数据进去时候（之前）才创建这个表。导致无法完成初始化。

**Comment by DrkCore** [comment]
之前我也遇到了这个问题，不过在一些Issue中作者说了是故意设计成第一次添加数据时才创建表的的。
所以我的做法是自己魔改了xUtils，把里面的createTableIfNotExists方法暴露出来了，如果有兴趣的话点我的GitHub；

**Comment by wyouflf** [comment]
已经支持TableCreateListener
