### ISSUE TITLE
在sd卡建立数据库，被删除异常

### ISSUE THREAD

**Issue by huizaiyo** [wyouflf/xUtils3#265]
04-12 03:19:30.178: E/AndroidRuntime(5559): Caused by: java.lang.IllegalStateException: Cannot perform this operation because there is no current transaction.
按home键最小化 应用后，若删除了数据库文件，再打开应用添加数据，就会报这个异常。。。

**Comment by wyouflf** [comment]
抛这个异常的时候，根据业务需要做用户提示或其他提醒，然后close，之后再次打开数据库
