### ISSUE TITLE
DB 数据库 create record issue

### ISSUE THREAD

**Issue by wingsum93** [wyouflf/xUtils3#267]
i have insert a row to my db with below stack trace. But i cannot know why it stop before i create the DB table.

04-13 16:58:30.273 W/System.err: org.xutils.ex.DbException
04-13 16:58:30.276 W/System.err:     at org.xutils.db.table.**DbBase.getTable(DbBase.java:32)**
04-13 16:58:30.278 W/System.err:     at org.xutils.db.DbManagerImpl.save(DbManagerImpl.java:182)
04-13 16:58:30.281 W/System.err:     at com.tradelink.wms.MyDao$override.saveYourItemSubs(MyDao.java:316)
04-13 16:58:30.283 W/System.err:     at com.tradelink.wms.MyDao$override.access$dispatch(MyDao.java)
04-13 16:58:30.285 W/System.err:     at com.tradelink.wms.MyDao.saveYourItemSubs(MyDao.java:0)
04-13 16:58:30.288 W/System.err:     at com.tradelink.wms.activity.ReceiveLv3AddItemType3.save_add_new_item(ReceiveLv3AddItemType3.java:215)
04-13 16:58:30.290 W/System.err:     at com.tradelink.wms.activity.ReceiveLv3AddItemType3.onClick(ReceiveLv3AddItemType3.java:235)
04-13 16:58:30.292 W/System.err:     at android.view.View.performClick(View.java:4463)
04-13 16:58:30.295 W/System.err:     at android.view.View$PerformClick.run(View.java:18770)
04-13 16:58:30.297 W/System.err:     at android.os.Handler.handleCallback(Handler.java:808)
04-13 16:58:30.299 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:103)
04-13 16:58:30.301 W/System.err:     at android.os.Looper.loop(Looper.java:193)
04-13 16:58:30.304 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5292)
04-13 16:58:30.305 W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
04-13 16:58:30.306 W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
04-13 16:58:30.307 W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
04-13 16:58:30.308 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
04-13 16:58:30.309 W/System.err:     at dalvik.system.NativeStart.main(Native Method)
04-13 16:58:30.310 W/System.err: Caused by: java.lang.NullPointerException
04-13 16:58:30.312 W/System.err:     at org.xutils.db.table.TableEntity.<init>(TableEntity.java:50)
04-13 16:58:30.314 W/System.err:     at org.xutils.db.table.DbBase.getTable(DbBase.java:30)
04-13 16:58:30.315 W/System.err:    ... 17 more

below are my data model

@Table(name = "your_item_sub")
public class YourItemSub {

```
@Column(name = "id",isId = true,autoGen = true)
private Integer id;
@Column(name ="your_item_id")
private long YourItemId;
@Column(name ="sub_item_id")
private long SubItemId;
@Column(name ="qty")
private int qty;
```

with getter and setter.....

**Comment by wingsum93** [comment]
i post my method in dao for ref

  public void saveYourItemSubs(List<YourItemSub> i){
		try {
			for (YourItemSub itemSub : i) {
				if (itemSub.getId() == null) {
					getDbManager().save(itemSub);
					continue;
				}
				getDbManager().saveOrUpdate(itemSub);

			}
		} catch (DbException e) {
			e.printStackTrace();
		}
	}

**Comment by wingsum93** [comment]
i found a root cost... is i max the @Table annotation with other so it cannot run....

**Comment by awq14789** [comment]
你好，我这边有了一样的问题，请问你那边找到解决办法了吗？？？

**Comment by wingsum93** [comment]
seee my upper stack trace

    04-13 16:58:30.276 W/System.err: at org.xutils.db.table.DbBase.getTable(DbBase.java:32)
check your table or column in yur model class .
use ctrl + Q to see it should be org.xutil.XXXX

**Comment by owen8877** [comment]
Maybe caused by #271 ?
