### ISSUE TITLE
RecyclerView支持

### ISSUE THREAD

**Issue by chenwulue** [wyouflf/xUtils3#268]
希望下载管理可以加入RecyclerView支持的Demo

**Comment by wulijie** [comment]
不太明白你的意思撒，骚年。你可以自己写啊

**Comment by Kerwin92** [comment]
@wulijie ，使用swipetoloadlayout库（https://github.com/Aspsine/SwipeToLoadLayout）会挂，***on a null object reference

**Comment by Kerwin92** [comment]
@wulijie ，已解决，自己的问题，抱歉
