### ISSUE TITLE
比较严重的bug--打印参数导致post请求方式变成get方式

### ISSUE THREAD

**Issue by wulijie** [wyouflf/xUtils3#269]
RequestParams params = new RequestParams(url);
 Log.i("参数“,"params="+params.toString);//导致bug发生的关键句子
x.http().post(params, new Callback.CommonCallback<String>() {}
打印了下参数，这个请求就变成get的方式了。

**Comment by Qiu800820** [comment]
@wulijie 他只是将你所有的参数拼接成url?key=value&key1=value1的形式方便log查看， 其实并没有改变HttpMethod方式

**Comment by 247321453** [comment]
你需要设置params.setMethod(HttpMethod.POST);

**Comment by 247321453** [comment]
@Qiu800820  一楼那样做，最后是url变成了get形式。

**Comment by wulijie** [comment]
@Qiu80020 额 你自己再设置一遍访问方式的话 我不知道 我只知道 我子啊这爱玲个方法中间打印一下就出现bug了 这个不应该的 所以建议作者改下哦

**Comment by Qiu800820** [comment]
@wulijie 确实复现了   把RequestParams中super.toString 换成super.toJSONString()就可以了   参数还在body中 还是POST方式

**Comment by 247321453** [comment]
@Qiu800820 @wulijie 我不想说什么了，

**Comment by wulijie** [comment]
恩 哈哈

**Comment by BillZhaoZ** [comment]
![image](https://user-images.githubusercontent.com/17405716/27907318-c69b4278-6279-11e7-8b49-b432e13c1006.png)

**Comment by BillZhaoZ** [comment]
和楼主表达的  应该是一个问题

**Comment by wyouflf** [comment]
已优化此问题, 谢谢反馈
