### ISSUE TITLE
使用xUtils3 get数据的问题

### ISSUE THREAD

**Issue by wancho** [wyouflf/xUtils3#27]
11-24 19:43:28.230 24229-24446/? W/dalvikvm: Exception Ljava/lang/RuntimeException; thrown while initializing Lorg/xutils/http/cookie/DbCookieStore;
11-24 19:43:28.230 24229-24446/? W/dalvikvm: Exception Ljava/lang/ExceptionInInitializerError; thrown while initializing Lorg/xutils/http/request/HttpRequest;
11-24 19:43:28.255 24229-24229/? I/hehe: onErrornull
11-24 19:43:28.255 24229-24229/? I/hehe: onFinished

**Comment by wyouflf** [comment]
需要初始化, 看readme: https://github.com/wyouflf/xUtils3#初始化
别忘了注册你的Application.
