### ISSUE TITLE
通过缓存获取文件

### ISSUE THREAD

**Issue by myqhit** [wyouflf/xUtils3#272]
我通过接口中的缓存机制保存下载文件，然后下一次下载的时候能够从缓存中拿文件，但是在调试的过程发现这一行    processLock = ProcessLock.tryLock(destPath, true, LOCK_WAIT); 老是返回空，结果就是会报异常，导致文件既无法下载，也无法从缓存中获取，请问下如何调整

**Comment by myqhit** [comment]
while (System.currentTimeMillis() < expiryTime)  通过这一行判断 结果当前时间大于expiryTime，返回null，请问是什么原因，可以说下我本地解决，项目中急需用到

**Comment by wyouflf** [comment]
使用cachecallback，泛型用File，不建议自己取缓存文件

**Comment by wyouflf** [comment]
建议使用封装好的LruDiskCache类来管理缓存, 参考源码中对LruDiskCache的使用
