### ISSUE TITLE
大神，没有put与delete请求啊。。。

### ISSUE THREAD

**Issue by zhengjiaai2008** [wyouflf/xUtils3#274]
大神，没有put与delete请求啊。。。

**Comment by chen2174471** [comment]
可以通过setMethod(HttpMethod.PUT)设置

**Comment by zhengjiaai2008** [comment]
谢谢大神，已经解决了。。

**Comment by wyouflf** [comment]
Callback.Cancelable request(HttpMethod method, RequestParams entity, Callback.CommonCallback<T> callback);

使用request方法就可以了
