### ISSUE TITLE
xutils3---postsync同步网络请求问题

### ISSUE THREAD

**Issue by ximencx** [wyouflf/xUtils3#275]
返回的class<t>是什么？？服务器返回的是json字符串，求用法

**Comment by wingsum93** [comment]
suggest you use okhttp which have full documents for usage.
[https://github.com/square/okhttp](url)

**Comment by Qiu800820** [comment]
@ximencx 
`try {
            JSONObject jsonObject = x.http().postSync(params, JSONObject.class);
        } catch (Throwable throwable) {
            throwable.printStackTrace();
}`

**Comment by liupeng110** [comment]
这样耦合度太大了啊,

**Comment by ximencx** [comment]
谢谢  最后改成String.class就可以解析字符串了，，

**Comment by wyouflf** [comment]
JSONObject jsonObject = x.http().postSync(params, JSONObject.class);
String str = x.http().postSync(params, String.class);

**Comment by liupeng110** [comment]
JSONObject jsonObject = x.http().postSync(params, JSONObject.class);
String str = x.http().postSync(params, String.class);
这两行 必须要try一下,能不能封装下  搞个不用try的

**Comment by ximencx** [comment]
没想都还能收到3年前的issue提示=-=
