### ISSUE TITLE
post 一个Image之后，返回的结果并不是一个json

### ISSUE THREAD

**Issue by LDayDream** [wyouflf/xUtils3#279]
请问一下，上传图片之后，服务器返回的结果并不是一个json，而是一下的字符串，是不是没有设置什么参数？

post代码：
 requestParams.setMultipart(true);
requestParams.addBodyParameter(parameter.getKey(), file, getMimeType(file));

返回的结果：
--MultipartDataMediaFormatterBoundary1q2w3e
Content-Disposition: form-data; name="Msg"

图片修改成功
--MultipartDataMediaFormatterBoundary1q2w3e
Content-Disposition: form-data; name="Stat"

1
--MultipartDataMediaFormatterBoundary1q2w3e
Content-Disposition: form-data; name="Data.State"

True
--MultipartDataMediaFormatterBoundary1q2w3e--

**Comment by bacy** [comment]
服务器返回不对，你问服务器去啊。。。

**Comment by LDayDream** [comment]
但是ios那边他们使用的框架可以获取到正确的json，所以我想是不是没有设置什么东西

**Comment by bacy** [comment]
你抓包对比下你跟ios发送请求有啥不同的。xutils上传默认用的muti-part
