### ISSUE TITLE
recvfrom failed: ETIMEDOUT (Connection timed out)

### ISSUE THREAD

**Issue by JustinChiang123** [wyouflf/xUtils3#280]
'''
04-25 17:33:40.108: E/XXX:Base_R.postBaseParam(L:146)(20528): Base_A.mBase_Config_O.getTokenkey() == null
04-25 17:33:40.138: D/XXX:HttpTask.doBackground(L:300)(20528): load: http://192.168.1.120/v1.4.4/user-login
04-25 17:33:40.608: D/PushConnection(20558): Receive err,errno:110
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528): recvfrom failed: ETIMEDOUT (Connection timed out)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528): java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:550)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at libcore.io.IoBridge.recvfrom(IoBridge.java:514)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at java.net.PlainSocketImpl.read(PlainSocketImpl.java:489)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:241)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at java.io.InputStream.read(InputStream.java:162)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:142)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at java.io.BufferedInputStream.read(BufferedInputStream.java:227)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at com.android.okhttp.internal.Util.readAsciiLine(Util.java:316)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at com.android.okhttp.internal.http.RawHeaders.fromBytes(RawHeaders.java:308)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:135)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:644)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at com.android.okhttp.internal.http.HttpURLConnectionImpl.getHeaderFields(HttpURLConnectionImpl.java:160)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at org.xutils.http.request.HttpRequest.sendRequest(HttpRequest.java:220)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at org.xutils.http.loader.StringLoader.load(StringLoader.java:44)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at org.xutils.http.loader.StringLoader.load(StringLoader.java:1)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:76)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:265)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at org.xutils.http.HttpTask$RequestWorker.run(HttpTask.java:607)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at org.xutils.http.HttpTask.doBackground(HttpTask.java:306)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at java.lang.Thread.run(Thread.java:841)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528): Caused by: libcore.io.ErrnoException: recvfrom failed: ETIMEDOUT (Connection timed out)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at libcore.io.Posix.recvfromBytes(Native Method)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at libcore.io.Posix.recvfrom(Posix.java:144)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:164)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at libcore.io.IoBridge.recvfrom(IoBridge.java:511)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   ... 25 more
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:63)(20528): http://192.168.1.120/v1.4.4/system-info
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:64)(20528): The Request Method can not be retried.
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528): failed to connect to 192.168.1.120/192.168.1.120 (port 80) after 15000ms: isConnected failed: ETIMEDOUT (Connection timed out)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528): java.net.SocketTimeoutException: failed to connect to 192.168.1.120/192.168.1.120 (port 80) after 15000ms: isConnected failed: ETIMEDOUT (Connection timed out)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at libcore.io.IoBridge.isConnected(IoBridge.java:221)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at libcore.io.IoBridge.connectErrno(IoBridge.java:161)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at libcore.io.IoBridge.connect(IoBridge.java:112)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:460)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at java.net.Socket.connect(Socket.java:866)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at com.android.okhttp.internal.Platform.connectSocket(Platform.java:152)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at com.android.okhttp.Connection.connect(Connection.java:101)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:197)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at org.xutils.http.request.HttpRequest.sendRequest(HttpRequest.java:213)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at org.xutils.http.loader.StringLoader.load(StringLoader.java:44)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at org.xutils.http.loader.StringLoader.load(StringLoader.java:1)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:76)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:265)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at org.xutils.http.HttpTask$RequestWorker.run(HttpTask.java:607)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at org.xutils.http.HttpTask.doBackground(HttpTask.java:306)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at java.lang.Thread.run(Thread.java:841)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528): Caused by: libcore.io.ErrnoException: isConnected failed: ETIMEDOUT (Connection timed out)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   at libcore.io.IoBridge.isConnected(IoBridge.java:208)
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:54)(20528):   ... 25 more
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:63)(20528): http://192.168.1.120/v1.4.4/user-login
04-25 17:33:40.618: W/XXX:HttpRetryHandler.canRetry(L:64)(20528): The Request Method can not be retried.
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528): recvfrom failed: ETIMEDOUT (Connection timed out)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528): java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:550)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at libcore.io.IoBridge.recvfrom(IoBridge.java:514)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at java.net.PlainSocketImpl.read(PlainSocketImpl.java:489)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:241)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at java.io.InputStream.read(InputStream.java:162)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:142)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at java.io.BufferedInputStream.read(BufferedInputStream.java:227)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at com.android.okhttp.internal.Util.readAsciiLine(Util.java:316)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at com.android.okhttp.internal.http.RawHeaders.fromBytes(RawHeaders.java:308)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:135)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:644)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at com.android.okhttp.internal.http.HttpURLConnectionImpl.getHeaderFields(HttpURLConnectionImpl.java:160)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at org.xutils.http.request.HttpRequest.sendRequest(HttpRequest.java:220)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at org.xutils.http.loader.StringLoader.load(StringLoader.java:44)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at org.xutils.http.loader.StringLoader.load(StringLoader.java:1)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:76)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:265)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at org.xutils.http.HttpTask$RequestWorker.run(HttpTask.java:607)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at org.xutils.http.HttpTask.doBackground(HttpTask.java:306)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at java.lang.Thread.run(Thread.java:841)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528): Caused by: libcore.io.ErrnoException: recvfrom failed: ETIMEDOUT (Connection timed out)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at libcore.io.Posix.recvfromBytes(Native Method)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at libcore.io.Posix.recvfrom(Posix.java:144)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:164)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at libcore.io.IoBridge.recvfrom(IoBridge.java:511)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    ... 25 more
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528): failed to connect to 192.168.1.120/192.168.1.120 (port 80) after 15000ms: isConnected failed: ETIMEDOUT (Connection timed out)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528): java.net.SocketTimeoutException: failed to connect to 192.168.1.120/192.168.1.120 (port 80) after 15000ms: isConnected failed: ETIMEDOUT (Connection timed out)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at libcore.io.IoBridge.isConnected(IoBridge.java:221)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at libcore.io.IoBridge.connectErrno(IoBridge.java:161)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at libcore.io.IoBridge.connect(IoBridge.java:112)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:460)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at java.net.Socket.connect(Socket.java:866)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at com.android.okhttp.internal.Platform.connectSocket(Platform.java:152)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at com.android.okhttp.Connection.connect(Connection.java:101)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:197)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at org.xutils.http.request.HttpRequest.sendRequest(HttpRequest.java:213)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at org.xutils.http.loader.StringLoader.load(StringLoader.java:44)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at org.xutils.http.loader.StringLoader.load(StringLoader.java:1)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:76)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:265)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at org.xutils.http.HttpTask$RequestWorker.run(HttpTask.java:607)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at org.xutils.http.HttpTask.doBackground(HttpTask.java:306)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at java.lang.Thread.run(Thread.java:841)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528): Caused by: libcore.io.ErrnoException: isConnected failed: ETIMEDOUT (Connection timed out)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    at libcore.io.IoBridge.isConnected(IoBridge.java:208)
04-25 17:33:40.628: D/XXX:TaskProxy$InternalHandler.handleMessage(L:204)(20528):    ... 25 more
'''

这到底是什么问题？服务端的问题还是客户端的问题，wifi环境下。

**Comment by wyouflf** [comment]
服务端问题
