### ISSUE TITLE
混淆后加载不了图片

### ISSUE THREAD

**Issue by Ryokooo** [wyouflf/xUtils3#285]

**Comment by godmarvin** [comment]
问题解决了吗？我也遇到了这个问题

**Comment by strugglekid** [comment]
混淆之后x.http就只返回error响应是怎么回事啊。。

**Comment by alvinyan** [comment]
能说的详细点吗？



alvin.yan@163.com
 
发件人： jianyuyouhun
发送时间： 2016-07-15 13:11
收件人： wyouflf/xUtils3
主题： Re: [wyouflf/xUtils3] 混淆后加载不了图片 (#285)
混淆之后x.http就只返回error响应是怎么回事啊。。

**Comment by strugglekid** [comment]
我按照你sample里面的混淆代码对项目进行混淆，混淆没有报任何错误，但是请求后台数据老是出错，不混淆的话是可以的，访问目标url是https的，但是证书还没有弄好，会不会是这个问题。之前也没有做过混淆，希望大神给点指导啊

**Comment by Huangbin1234** [comment]
我也是遇到这个问题，混淆之后x.http就只返回error响应

**Comment by ypf168326** [comment]
代码混淆之后，http直接无法调用了。

**Comment by Huangbin1234** [comment]
经过排查发现xutils混淆没问题，是butterknife版本的问题导致库里面的资源ID找不到造成的。

**Comment by wyouflf** [comment]
源码里sample工程有混淆的示例
