### ISSUE TITLE
高德地图so库和xUtils里面的armV7中的libwebpbackport.so不兼容！

### ISSUE THREAD

**Issue by haikuowuya** [wyouflf/xUtils3#288]
高德地图so库中只提供了armeabi 和arm64-v8a两种动态库， 没有提供armeabi-v7a的动态库， 
而 xUtils里面有armV7 libwebpbackport.so 导致运行到地图展示时报错！

**Comment by liupeng110** [comment]
webpbackport.so我都直接去掉了,项目有个莫名其妙的报错 去掉就好了非常奇怪

**Comment by smay1227** [comment]
可以只保留一个armeabi 高德地图也是的

**Comment by wyouflf** [comment]
已经移除这个so
