### ISSUE TITLE
加载图片 异常信息

### ISSUE THREAD

**Issue by cekowu** [wyouflf/xUtils3#29]
11-26 09:57:12.436: W/x_log:ImageDecoder.saveThumbCache(L:508)(7486): Unsupported Bitmap configuration. Currently only RGBA_8888 and RGB_565 are supported
11-26 09:57:12.436: W/x_log:ImageDecoder.saveThumbCache(L:508)(7486): java.lang.RuntimeException: Unsupported Bitmap configuration. Currently only RGBA_8888 and RGB_565 are supported
11-26 09:57:12.436: W/x_log:ImageDecoder.saveThumbCache(L:508)(7486): 	at android.backport.webp.WebPFactory.nativeEncodeBitmap(Native Method)
11-26 09:57:12.436: W/x_log:ImageDecoder.saveThumbCache(L:508)(7486): 	at org.xutils.image.ImageDecoder.saveThumbCache(ImageDecoder.java:501)
11-26 09:57:12.436: W/x_log:ImageDecoder.saveThumbCache(L:508)(7486): 	at org.xutils.image.ImageDecoder.access$0(ImageDecoder.java:491)
11-26 09:57:12.436: W/x_log:ImageDecoder.saveThumbCache(L:508)(7486): 	at org.xutils.image.ImageDecoder$1.run(ImageDecoder.java:131)
11-26 09:57:12.436: W/x_log:ImageDecoder.saveThumbCache(L:508)(7486): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-26 09:57:12.436: W/x_log:ImageDecoder.saveThumbCache(L:508)(7486): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-26 09:57:12.436: W/x_log:ImageDecoder.saveThumbCache(L:508)(7486): 	at java.lang.Thread.run(Thread.java:818)
11-26 09:57:12.501: W/x_log:ImageDecoder.saveThumbCache(L:508)(7486): Unsupported Bitmap configuration. Currently only RGBA_8888 and RGB_565 are supported
11-26 09:57:12.501: W/x_log:ImageDecoder.saveThumbCache(L:508)(7486): java.lang.RuntimeException: Unsupported Bitmap configuration. Currently only RGBA_8888 and RGB_565 are supported
11-26 09:57:12.501: W/x_log:ImageDecoder.saveThumbCache(L:508)(7486): 	at android.backport.webp.WebPFactory.nativeEncodeBitmap(Native Method)
11-26 09:57:12.501: W/x_log:ImageDecoder.saveThumbCache(L:508)(7486): 	at org.xutils.image.ImageDecoder.saveThumbCache(ImageDecoder.java:501)
11-26 09:57:12.501: W/x_log:ImageDecoder.saveThumbCache(L:508)(7486): 	at org.xutils.image.ImageDecoder.access$0(ImageDecoder.java:491)
11-26 09:57:12.501: W/x_log:ImageDecoder.saveThumbCache(L:508)(7486): 	at org.xutils.image.ImageDecoder$1.run(ImageDecoder.java:131)
11-26 09:57:12.501: W/x_log:ImageDecoder.saveThumbCache(L:508)(7486): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-26 09:57:12.501: W/x_log:ImageDecoder.saveThumbCache(L:508)(7486): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-26 09:57:12.501: W/x_log:ImageDecoder.saveThumbCache(L:508)(7486): 	at java.lang.Thread.run(Thread.java:818)

**Comment by wyouflf** [comment]
忽略这个警告, libwebp暂不支持.
