### ISSUE TITLE
gif 无效

### ISSUE THREAD

**Issue by jimdaxu** [wyouflf/xUtils3#291]
setLoadingDrawableId 设置gif图片没有效果

**Comment by jimdaxu** [comment]
setLoadingDrawableId 设置动画也没有效果

**Comment by wyouflf** [comment]
loadingDrawable参数暂不支持gif, 如果gif文件在本地 或res 或assets里, 可以先x.image().bind(view, gif_url, options); 在x.image().bind(view, url, options);
