### ISSUE TITLE
nexus5 4.4.4 post请求超时，error回调异常类型错误的问题

### ISSUE THREAD

**Issue by wenwen0904** [wyouflf/xUtils3#294]
error回调的类型不是xutils中的httpexception，返回的是SocketTimeoutException，UnknownHostException这样的，拿不到状态码，有时还会是空指针异常

调试到HttpRequest类中的这段代码
if (params.isUseCookie()) { // save cookies
            try {
                Map<String, List<String>> headers = connection.getHeaderFields();
                if (headers != null) {
                    COOKIE_MANAGER.put(url.toURI(), headers);
                }
            } catch (Throwable ex) {
                LogUtil.e(ex.getMessage(), ex);
            }
        }

```
    // check response code
    responseCode = connection.getResponseCode();
```

connection.getHeaderFields();和connection.getResponseCode();执行的是okhttp的源码，看不到源码，调试到这就断了。
这个问题能否查看一下？

**Comment by wyouflf** [comment]
更新最新版本
