### ISSUE TITLE
图片加载不支持中文路径

### ISSUE THREAD

**Issue by jimdaxu** [wyouflf/xUtils3#296]
图片加载不支持中文路径

**Comment by gaoyan10** [comment]
嗯，不止是图片加载，文件下载也一样。可能是没有对下载的Url里的path进行URLEncode的原因

**Comment by xiaobaDev** [comment]
对url进行base64转下就好了

**Comment by wyouflf** [comment]
提供符合URL规范的地址，URLEncode处理下
