### ISSUE TITLE
CacheCallback.onCache()返回false后会重新加载，但并不覆盖缓存文件？

### ISSUE THREAD

**Issue by DrkCore** [wyouflf/xUtils3#298]
如题，比方说有一张图片路径为path。

bind(imgView,path)是图片A；
替换path指向的位置为图片B并设置CacheCallback.onCache()为false，此时bind显示了图片B；
但是再次使用普通的bind(imgView,path)时得到的图片仍然是A；

退出重进应用问题依旧，但是结束进程后重启应用终于显示了图片B，感觉问题应该在内存缓存这块。

逻辑上而言当我在onCache()返回false时已经表明我不信任当前的cache，重新加载后应当覆盖掉旧的缓存才对吧？

**Comment by wyouflf** [comment]
两次imageOptions参数不一致?

**Comment by DrkCore** [comment]
1. 当时的需求是用固定路径保存用户选取的封面，使得用户可以在外部存储中自行操作这个文件

2. 很遗憾当时具体的细节已经回忆不起来了，之后项目经历了推倒重做，很难找到当时的记录

3. 推倒重做后技术选型走了另外的方向解决了这个问题
