### ISSUE TITLE
能否针对数据库模块单独出一个库

### ISSUE THREAD

**Issue by AndSync** [wyouflf/xUtils3#299]
Xutils使用了很长时间 但是 基本上只使用数据库模块，其他模块由于各种原因并未使用
如 1、图片加载 更多的还是会使用ImageLoader
2、findviewByid注解的方式还是不喜欢用 有种被强奸的感觉
3、网络请求更是有很多成熟的框架 volley AsyncHttp okhttp等

我的建议就是 应该每个模块单独出一个库 这样用户有选择性的来使用 虽然都加进来包也不会大多少
这样可以每个模块单独来维护 本身这几个模块相关性也不大

**Comment by wyouflf** [comment]
参考 https://github.com/wyouflf/xUtils3/issues/512
