### ISSUE TITLE
希望能像volley一样可以取消某个链接

### ISSUE THREAD

**Issue by yhsj0919** [wyouflf/xUtils3#3]
很多时候网络请求会引起空指针等异常，希望能在关闭activity的时候同时取消当前页面的请求

**Comment by wyouflf** [comment]
添加自定义Callback, 由Callback决定是否取消链接:

public abstract class BindingPageCallback<ResultType>
            implements Callback.CommonCallback<ResultType>, Callback.Cancelable {

        private boolean cancelled = false;
        private final WeakReference<Object> pageRef;

        public BindingPageCallback(Object page) {
            this.pageRef = new WeakReference<Object>(page);
        }

        @Override
        public void cancel() {
            cancelled = true;
        }

        @Override
        public boolean isCancelled() {
            if (cancelled) {
                return true;
            } else {
                Object page = pageRef.get();
                if (page == null) {
                    return true;
                }

                if (page instanceof Activity) {
                    return ((Activity) page).isFinishing();
                } else if (page instanceof Fragment/* v4? */) {
                    return ((Fragment) page).isDetached();
                } else {
                    .....
                }
            }

            return false;
        }
    }

**Comment by Kerwin92** [comment]
@wyouflf ,您好，这个抽象类在哪儿继承使用呢？自己没想出来，求指教

**Comment by TuWei1992** [comment]
@wyouflf 我想在onError的时候取消这个request应该怎么处理?

**Comment by yuyongxue** [comment]
学习了
