### ISSUE TITLE
数据库表增加字段 能否自动添加到数据库 ？

### ISSUE THREAD

**Issue by AndSync** [wyouflf/xUtils3#300]
其实使用数据库最头疼的问题就是实体类的变更
一般数据库实体会和接口解析的实体是一个
如果接口改变 实体要改变 那么还要在config里面去监听数据库升级
对于app开发 接口改变是太常见的事情 因此对于维护数据库会变的非常恶心
如果xutils能做到帮用户自动添加进去 那是非常非常非常好的 
能够解决很多人都比较恶心的问题

**Comment by wyouflf** [comment]
daoconfig参数里设置升级接口，有addColumn方法方便添加列
