### ISSUE TITLE
xutils3如何下载文件啊，sample根本看不懂

### ISSUE THREAD

**Issue by myadomin** [wyouflf/xUtils3#302]
xutils3如何下载文件啊，原来的xutils一个download方法就可以了，现在这个没有示例，好复杂看不懂

**Comment by doaremon** [comment]
直接调用Http请求方法就好，只是回掉的时候new Callback.ProgressCallback<File>就好。
        //设置断点续传
        params.setAutoResume(true);
        params.setSaveFilePath("下载文件保存倒sd卡的地址");

**Comment by wangdajiu** [comment]
onLoad方法没有执行

**Comment by Duke0323** [comment]
作为菜鸟的我也没找到怎么下载...看蒙了

**Comment by wyouflf** [comment]
最简单的callback泛型填File就可以了
