### ISSUE TITLE
你好，HttpManager里面只有get和Post没有Put等其他的请求呢

### ISSUE THREAD

**Issue by KevinYou128** [wyouflf/xUtils3#303]
你好，HttpManager里面只有get和Post没有Put等其他的请求呢，并且get post请求代码一模一样，，， <T> Callback.Cancelable get(RequestParams entity, Callback.CommonCallback<T> callback);
可以说说这个吗？非常感谢！

**Comment by wyouflf** [comment]
看其他几个方法的定义
