### ISSUE TITLE
delete请求报异常 

### ISSUE THREAD

**Issue by chen2174471** [wyouflf/xUtils3#305]
.doBackground(L:303): load: http://192.168.1.110:8000/SelectCourseService/delete/1049721500313-e1557d66-b25d-408b-8315-908d5f4d7038
05-13 19:00:35.439 14512-14722/com.tpwy.activity W/x_log:HttpRetryHandler.canRetry(L:54): DELETE does not support writing
java.net.ProtocolException: DELETE does not support writing at libcore.net.http.HttpURLConnectionImpl.initHttpEngine(HttpURLConnectionImpl.java:240)
at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:78)
并没有在body体中放入数据，只是一个链接。测试机型 中兴 android4.0
是否应该将delete方法的setDoOutput(true)设置为false

**Comment by TestSmirk** [comment]
DELECT 从 JAVA 就不支持.

**Comment by wyouflf** [comment]
参数都添加到query里，addQueryStringParameter
