### ISSUE TITLE
能不能在image里添加这样一个方法

### ISSUE THREAD

**Issue by reaper12** [wyouflf/xUtils3#311]
x.image().bind(ImageView, ImageOptions,new CallBack(){

```
        @Override
        public String doBackgroud(){
            //doSomething in thread
            return null;
        }

        @Override
        public void onFinish(ImageView imageview,Drawable drawable){
            //set imageView
        }


    });
```

类似的方法

**Comment by reaper12** [comment]
或者是可以实现加载视频缩略图吗？

**Comment by xiaobaDev** [comment]
加载url，返回的drawable自己处理下就好了。
` Callback.Cancelable loadDrawable(String url, ImageOptions options, Callback.CommonCallback<Drawable> callback);`

缩略图如果是远程的，让服务端提供呗
如果是本地的，使用sdk的`ThumbnailUtils.createVideoThumbnail(localPath, MediaStore.Images.Thumbnails.MINI_KIND);`
注意上面的方法是io密集型的，所以需要放到异步线程中执行

**Comment by wyouflf** [comment]
可以使用prepareCallback，prepare方法在后台线程执行
