### ISSUE TITLE
关于http模块的一点建议

### ISSUE THREAD

**Issue by JustinChiang123** [wyouflf/xUtils3#314]
首先，感谢作者提供优秀的xutils。能一直维护相当不容易。

下面是我使用xutils的一些疑问和一些理解，如果说错了欢迎指出，互帮互助，共同进步。

现在http有两种方式：
1、同步请求
2、异步请求（最终返回值会出现在UI线程）

希望能提供另外的方式，例如：
1、异步请求（后台线程A调用，后台线程A执行请求逻辑，返回值在后台线程A）
2、异步请求（UI线程调用，后台线程A执行请求逻辑，返回值在后台线程A）
3、异步请求（UI线程调用，后台线程A执行请求逻辑，返回值在后台线程B）

为什么这么考虑？
列举一个简单的例子，用户登录（需要请求两个接口）：
我想的：UI线程调用-->登陆1（后台线程1），并且成功后-->登陆2（后台线程2）-->UI线程取得返回值。
实际我使用xutils：UI线程调用-->登陆1（后台线程1），并且成功-->UI线程调用登陆2（后台线程2）-->UI线程取得返回值。
如果第2种处理的逻辑比较多，就会出现潜在的卡UI线程问题。so，如果这里能直接回到后台线程就应该不会卡UI了？

**Comment by bacy** [comment]
让我想到了Rx，哈哈

**Comment by ehaahe** [comment]
1.2可以在线程中开启同步请求达到这种效果，3这种效果好像有点困难

**Comment by wyouflf** [comment]
起一个线程x.task().startxx/run，调用2个同步接口
