### ISSUE TITLE
HttpMethod.permitsRequestBody(HttpMethod) 一直为false

### ISSUE THREAD

**Issue by ifinver** [wyouflf/xUtils3#316]
在x.http().post之前，如果RequestParams没有setMethod，在请求的过程中bodyParams都会跑到queryStringParams里面去。
虽然作者在post方法内部设置了entity.setMethod，但是无效。
目前避免这个问题的方式是在x.http().post之前，对params手动设置setMethod(HttpMethod.Post)

**Comment by BillZhaoZ** [comment]
同样的问题   同样的处理方法   期待作者解决

**Comment by wyouflf** [comment]
3.6.7之后的版本已经优化
