### ISSUE TITLE
网络请求和数据库操作在4.0.4上闪退

### ISSUE THREAD

**Issue by FreeezingKing** [wyouflf/xUtils3#317]
xutils3 不是最低支持4.0么  现在项目做到一半发现在4.0.4的机制上网络请求和数据库操作都会闪退啊 楼主怎么解决？

**Comment by FreeezingKing** [comment]
检测后发现是数据库封装模块保存的时候在4.0.4的系统上会出现Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1)

**Comment by wyouflf** [comment]
未复现你的问题，试试新版本
