### ISSUE TITLE
OnSuccess回调有点问题

### ISSUE THREAD

**Issue by Msnzz** [wyouflf/xUtils3#320]
![coyb1oc6hk1z3s rp_ 5 q](https://cloud.githubusercontent.com/assets/19198048/15563095/ff7b0146-2337-11e6-9afc-7b5af7a2940b.png)
onSuccess之后result无法被 Log出来

**Comment by MoJimmy** [comment]
我使用 x.http() 在onSuccess中无法Log 出来，makeToast 就可以显示result，这是什么问题

**Comment by wyouflf** [comment]
log内容超长了
