### ISSUE TITLE
circleimageview不支持bind

### ISSUE THREAD

**Issue by tianqing2117** [wyouflf/xUtils3#321]
xutils3在bind使用的circleimageview请求网络图片时 报错。
java.lang.IllegalArgumentException: ScaleType CENTER_INSIDE not supported.

而Picasso可以正常使用。

**Comment by xiaobaDev** [comment]
你用的是github上那个CircleImageView吗？
如果是的话，按照下面的样子修改代码
`    @Override
    public ScaleType getScaleType() {
        return SCALE_TYPE;
    }

    @Override
    public void setScaleType(ScaleType scaleType) {
        return;
    }
`
另外我感觉xUtils问题比较多，正在尝试用新的一套方案，你可以参考下
`
compile 'com.jakewharton:butterknife:7.0.1'  
  compile 'com.squareup:otto:1.3.8'   
 compile 'com.squareup.retrofit2:retrofit:2.0.0'             // 会引用 okHttp   
 compile 'com.squareup.retrofit2:converter-gson:2.0.0'       // 会引用 Gson 
  compile 'com.squareup.retrofit2:adapter-rxjava:2.0.0'       // 会引用 RxJava   
 compile 'io.reactivex:rxandroid:1.1.0'   
 compile 'com.github.bumptech.glide:glide:3.7.0'`

**Comment by tianqing2117** [comment]
OK 谢谢

**Comment by djgzhiyong** [comment]
同问，也遇到了这个问题，很多第三方的圆形组件在bind时只支持 CENTER_CROP
我在绑定时，这样指定也不行
ImageOptions.Builder().setFailureDrawableId(R.mipmap.ic_empty_head).setImageScaleType(ImageView.ScaleType.CENTER_CROP).build();

**Comment by tianqing2117** [comment]
如xiaobaDev 所说 ，并不是要修改你在xutil的用法 而是修改第三方的圆形组件的代码 把圆形组件的ScaleType 置为你需要的。
我现在也是使用的xiaobaDev所建议的那一套第三方库了。使用起来确实好很多，可定制性、解耦性、可操作性高很多。

**Comment by tianqing2117** [comment]
我之所以在Xutil这里问，是因为 其它图片加载库 如glide、picaso、fresco都没问题。我感觉应该是xutil本身的问题。由于我从未在项目中使用xutil所以没有深入去研究。
