### ISSUE TITLE
图片崩溃

### ISSUE THREAD

**Issue by wulijie** [wyouflf/xUtils3#322]
in call to ThrowNew
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]     from android.graphics.Bitmap android.backport.webp.WebPFactory.nativeDecodeFile(java.lang.String, android.graphics.BitmapFactory$Options)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410] "xTID#20" prio=5 tid=61 Runnable
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   | group="main" sCount=0 dsCount=0 obj=0x12f8f700 self=0x9cfda800
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   | sysTid=16406 nice=0 cgrp=default sched=0/0 handle=0x980c9930
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   | state=R schedstat=( 176824156 28341888 170 ) utm=15 stm=2 core=3 HZ=100
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   | stack=0x97fc7000-0x97fc9000 stackSize=1038KB
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   | held mutexes= "mutator lock"(shared held)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   native: #00 pc 00370e89  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const_, art::ArtMethod_, void_)+160)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   native: #01 pc 003504f7  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+150)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   native: #02 pc 0025a735  /system/lib/libart.so (art::JavaVMExt::JniAbort(char const_, char const_)+740)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   native: #03 pc 0025ae0d  /system/lib/libart.so (art::JavaVMExt::JniAbortV(char const_, char const_, std::__va_list)+64)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   native: #04 pc 000fd1e1  /system/lib/libart.so (art::ScopedCheck::AbortF(char const_, ...)+32)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   native: #05 pc 001022f5  /system/lib/libart.so (art::ScopedCheck::Check(art::ScopedObjectAccess&, bool, char const_, art::JniValueType_) (.constprop.95)+5072)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   native: #06 pc 00105fcb  /system/lib/libart.so (art::CheckJNI::ThrowNew(_JNIEnv_, _jclass_, char const_)+438)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   native: #07 pc 000075e3  /data/app/com.superfish.jtv-1/lib/arm/libwebpbackport.so (_JNIEnv::ThrowNew(_jclass_, char const*)+6)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   native: #08 pc 000079b9  /data/app/com.superfish.jtv-1/lib/arm/libwebpbackport.so (Java_android_backport_webp_WebPFactory_nativeDecodeFile+332)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   native: #09 pc 000004ed  /data/data/com.superfish.jtv/cache/slice-org.xutils-xutils-3.3.32_cf12d924902857be7105b0cdb8d18b41f5899a25-classes.dex (android.graphics.Bitmap android.backport.webp.WebPFactory.nativeDecodeFile(java.lang.String, android.graphics.BitmapFactory$Options)+112)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   native: #10 pc 00000229  /data/data/com.superfish.jtv/cache/slice-org.xutils-xutils-3.3.32_cf12d924902857be7105b0cdb8d18b41f5899a25-classes.dex (android.graphics.Bitmap android.backport.webp.WebPFactory.decodeFile(java.lang.String, android.graphics.BitmapFactory$Options)+76)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   native: #11 pc 000536d3  /data/data/com.superfish.jtv/cache/slice-org.xutils-xutils-3.3.32_cf12d924902857be7105b0cdb8d18b41f5899a25-classes.dex (android.graphics.Bitmap org.xutils.image.ImageDecoder.getThumbCache(java.io.File, org.xutils.image.ImageOptions)+718)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   native: #12 pc 00052acb  /data/data/com.superfish.jtv/cache/slice-org.xutils-xutils-3.3.32_cf12d924902857be7105b0cdb8d18b41f5899a25-classes.dex (android.graphics.drawable.Drawable org.xutils.image.ImageDecoder.decodeFileWithLock(java.io.File, org.xutils.image.ImageOptions, org.xutils.common.Callback$Cancelable)+1302)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   native: #13 pc 00058f5d  /data/data/com.superfish.jtv/cache/slice-org.xutils-xutils-3.3.32_cf12d924902857be7105b0cdb8d18b41f5899a25-classes.dex (android.graphics.drawable.Drawable org.xutils.image.ImageLoader.prepare(java.io.File)+320)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   native: #14 pc 000591fb  /data/data/com.superfish.jtv/cache/slice-org.xutils-xutils-3.3.32_cf12d924902857be7105b0cdb8d18b41f5899a25-classes.dex (java.lang.Object org.xutils.image.ImageLoader.prepare(java.lang.Object)+94)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   native: #15 pc 00033ab7  /data/data/com.superfish.jtv/cache/slice-org.xutils-xutils-3.3.32_cf12d924902857be7105b0cdb8d18b41f5899a25-classes.dex (java.lang.Object org.xutils.http.HttpTask.doBackground()+4274)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   native: #16 pc 0000bc9f  /data/data/com.superfish.jtv/cache/slice-org.xutils-xutils-3.3.32_cf12d924902857be7105b0cdb8d18b41f5899a25-classes.dex (void org.xutils.common.task.TaskProxy$1.run()+682)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   native: #17 pc 00009373  /data/data/com.superfish.jtv/cache/slice-org.xutils-xutils-3.3.32_cf12d924902857be7105b0cdb8d18b41f5899a25-classes.dex (void org.xutils.common.task.PriorityRunnable.run()+62)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   native: #18 pc 003b3b21  /data/dalvik-cache/arm/system@framework@boot.oat (???)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   at android.backport.webp.WebPFactory.nativeDecodeFile(Native method)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   at android.backport.webp.WebPFactory.decodeFile(WebPFactory.java:58)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   at org.xutils.image.ImageDecoder.getThumbCache(ImageDecoder.java:661)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   at org.xutils.image.ImageDecoder.decodeFileWithLock(ImageDecoder.java:116)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   at org.xutils.image.ImageLoader.prepare(ImageLoader.java:375)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   at org.xutils.image.ImageLoader.prepare(ImageLoader.java:38)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   at org.xutils.http.HttpTask.doBackground(HttpTask.java:331)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-27 15:26:06.063 16010-16406/com.superfish.jtv A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.Thread.run(Thread.java:818)

**Comment by wyouflf** [comment]
更新到新版本已修复此问题
