### ISSUE TITLE
使用xUtils3批量下载文件问题

### ISSUE THREAD

**Issue by coco163** [wyouflf/xUtils3#325]
我使用xUtils3的DownloadManager批量下载文件,设置 
 params.setAutoResume(true);
 params.setAutoRename(true);
但是下载到文件随机文件数就无法继续下去，卡在哪里，找了很久不知道问题出在哪里，个人猜测是多线程的问题。请大神们不惜赐教，谢谢

**Comment by HuShenghai** [comment]
遇到同样问题，排队下载多个文件，下载了几十个(设备不一样，数量不一样)之后就卡在onLoading，没有回调onCancelled 或者 onError。楼主解决了这个问题没有？

**Comment by wyouflf** [comment]
感谢反馈，新版已优化
