### ISSUE TITLE
使用http的post请求方法，出现的诡异问题

### ISSUE THREAD

**Issue by zouyuefen** [wyouflf/xUtils3#327]
/*\* 用户验证接口*/
 RequestParams params = new RequestParams(“http://192.168.199.121:8080/api/i/authenticate”);
        params.addParameter("username", username);
        params.addParameter("password", password);
        params.setAsJsonContent(true);// 将post请求的body参数以json形式提交

//       LogUtils.i("Params:"+params); 20160531  添加打印日志后  出现用户验证失败
        return RequestManager.getInstance().httpRequest(HttpMethod.POST, params, requestListener);
调用的是  ## x.http().request(method, params, new Callback.CacheCallback<String>()

---

加了打印日志这行出现的报错：
 load cache: http://192.168.199.121:8080/api/i/authenticate?username=zou&password=123
05-31 16:53:03.552 28529-15052/com.yoosh.app E/x_log:HttpRequest.sendRequest(L:249): errorCode: 415, msg: Unsupported Media Type, result: {"timestamp":1464684786163,"status":415,"error":"Unsupported Media Type","exception":"org.springframework.web.HttpMediaTypeNotSupportedException","message":"Content type 'application/x-www-form-urlencoded;charset=UTF-8' not supported","path":"/api/i/authenticate"}, url: http://192.168.199.121:8080/api/i/authenticate?username=zou&password=123

---

不加LogUtils这行：
 load cache: http://192.168.199.121:8080/api/i/authenticate
05-31 16:42:42.819 com.yoosh.app I/~~result~~~: authenticate user success
05-31 16:42:42.819 com.yoosh.app I/~exhibition~: 登录成功:result:authenticate user success

**Comment by haozecc** [comment]
我也遇到这种问题了，就是明明发送的post请求，参数都被追加在了url后面
找了各种问题，看到这个issue，把LogUtils注释掉，就没问题了，希望能修复一下

**Comment by LanceCong** [comment]
post请求我这边也遇到问题，经常出现405

**Comment by chenbinzhou** [comment]
是这样解决的吗？何log有什么关系

**Comment by leegh15** [comment]
同问

**Comment by wyouflf** [comment]
params没有setMethod时调用 params.toString引发的问题，新版已经优化，感谢反馈
