### ISSUE TITLE
HTTP get请求 用户匿名访问

### ISSUE THREAD

**Issue by LawsonJin** [wyouflf/xUtils3#328]
params.addHeader("Cookie", sessioname + "=" + sessionid);
  params.addHeader("X-CSRF-Token", token);
表示已经把token cookie 传递过去了 但是返回时报了
访问拒绝匿名 这个问题，请问这是怎么回事？

**Comment by langren1353** [comment]
看看是不是还有其他验证，例如host之类的

**Comment by LawsonJin** [comment]
没有了，就一个验证。去掉就好了，但是我用httpclient工具可以得到返回值。使用xutils3直接返回到error，匿名

________________________________
发件人: langren1353 <notifications@github.com>
发送时间: 2016年6月8日 9:35:02
收件人: wyouflf/xUtils3
抄送: LawsonJin; Author
主题: Re: [wyouflf/xUtils3] HTTP get请求 用户匿名访问 (#328)


看看是不是还有其他验证，例如host之类的

―

**Comment by wyouflf** [comment]
使用setHeader方法添加cookie
