### ISSUE TITLE
项目中使用xUtils还是各种开源库组合好些？

### ISSUE THREAD

**Issue by shenshanlaoyuan** [wyouflf/xUtils3#329]
如题

**Comment by xiaobaDev** [comment]
xutils的优势是一整套的解决方案，很容易改造以应对自己的项目。而现在流行的框架比如okhttp、retofit、glide、butterknife、greendao在性能、功能上表现会更加优异，毕竟作者再强，也精力有限也搞不过那么多开源的组织吧？
对于我而言，目前是用xutils3的代码，修改下拿来自己用了，胜在知根知底，修改、扩展起来也方便
