### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by asstea** [wyouflf/xUtils3#330]
注解可以换成类似Butterknife这种预编译的模式。

**Comment by wyouflf** [comment]
反射在android4.0开始对性能的影响越来越小, 系统还会继续优化, 修改字节码的方式是不被建议的, 而且java被oracle收购后可能不再开源, 字节码兼容(https://stackoverflow.com/questions/49445775/is-java-byte-code-always-forward-compatible)的维护成本和稳定性可能都是问题.
