### ISSUE TITLE
用这个库的话android4.2以下系统也能完美支持透明的无损webp图片吗？比如view的background属性

### ISSUE THREAD

**Issue by zzi2014** [wyouflf/xUtils3#336]
android4.0以上4.2以下的系统原生并没有完美支持webp图片，一些透明的或者无损的webp图片会显示不出来。

我看了一下源码xUtils3好像也只是对ImageView的src相关属性做了兼容？也就是说如果本地view设置background用了不兼容的webp图片的话还是会显示不出来？

那么如果我要设置背景的话要怎么处理呢？

**Comment by wyouflf** [comment]
并不完美, 目前4.2一下机器几乎没有了
