### ISSUE TITLE
java.lang.NoClassDefFoundError: org.xutils.x$Ext$1？这是什么问题？

### ISSUE THREAD

**Issue by yeweicong** [wyouflf/xUtils3#338]
我的应用在我手机启动没问题，但是拿别人的手机就会报这个错，闪退，为什么？

**Comment by maliankun** [comment]
我也遇到了这个问题，解决了吗？

**Comment by MarsToken** [comment]
我也遇到了，这问题很奇怪，现在的原因找到了：我就是加了个类，但是那个类压根就没被调用，错误提示一模一样

**Comment by kehongwei** [comment]
基本确定和机型有关系，请问有解决的吗，希望作者看看！

**Comment by try1991** [comment]
我也想问这个问题啊  一直没有解决

**Comment by try1991** [comment]
求解决了的,回答一下 ,

**Comment by try1991** [comment]
我的问题是  我在5.0以上的手机上运行没有问题  但是在5.0以下就会在Application初始化x的时候报这个错误,网上也找不到解决的方法

**Comment by try1991** [comment]
快来人救救我啊

**Comment by try1991** [comment]
我要崩溃了  救命

**Comment by maliankun** [comment]
我的问题解决了，因为我用到了分包机制，所以导致在初始化的时候报错，解决办法把应用的application 继承的基类换成MultiDexApplication，好坑啊！好久才得到解决

**Comment by try1991** [comment]
感谢楼上这位兄弟

**Comment by dotw** [comment]
郁闷了好久，感谢@maliankun

**Comment by yingwei0831** [comment]
换了楼上兄弟的方式，也无法解决我的问题呢？
