### ISSUE TITLE
使用Delete报错

### ISSUE THREAD

**Issue by zhuzhengxiang** [wyouflf/xUtils3#341]
x.http().request(HttpMethod.DELETE, params, new SimpleRequestListener(context, null) {
            @Override
            public void onSuccess(String result) {
                super.onSuccess("删除动态成功" + result);
                EventBus.getDefault().post(new PushListEvent("刷新列表"));
            }
        });
接口是同的，但是报错：java.net.ProtocolException: DELETE does not support writing。这是什么原因

**Comment by TestSmirk** [comment]
移动端不能用DELETE请求,Microsoft当时约定的时候就有缺陷.

**Comment by ltigers** [comment]
为什么有的手机支持

**Comment by wyouflf** [comment]
新版已修复，谢谢反馈
