### ISSUE TITLE
Image().doLoadDrawable重大逻辑错误

### ISSUE THREAD

**Issue by xiaobaDev** [wyouflf/xUtils3#343]
**_事故重现：**_
图文混排控件，数据`<img src='地址A' /> = <img src='地址A'/>` 图片只要出现url一样的情况，第二个图片必然加载失败。
**_原因排查**_
在ImageLoader的doBind函数里，为了避免重复加载，使用了如下代码块

```
ImageLoader loader = ((AsyncDrawable) oldDrawable).getImageLoader();
            if (loader != null && !loader.stopped) {
                if (key.equals(loader.key)) {
                    // repetitive url and options binding to the same View.
                    // not need callback to ui.
                    return null;
                } else {
                    loader.cancel();
                }
            }
```

嗯，上面代码的意思是：如果你要加载的图片控件已经在加载这个资源了，就取消这次请求。
到目前为止一切都正常。直到看到doLoadDrawable函数是如何模拟一个图片控件的代码。

```
 FakeImageView fakeImageView = null;
        synchronized (FAKE_IMG_MAP) {
            fakeImageView = FAKE_IMG_MAP.get(url);
            if (fakeImageView == null) {
                fakeImageView = new FakeImageView();
            }
        }
```

上面的代码是，如果请求哈希表中有这个url对应的图片控件了，就拿出来复用。
那么问题来了，我第二次相同的url，拿到的是第一次正在加载的图片控件，而此时，该图片控件正在加载中，所以第二次请求就被取消掉了。  

目前我的解决办法是FakeImageView不再从内存中拿，直接创建一个新的，老实说感觉很怪。
`FakeImageView fakeImageView = new FakeImageView();`

**Comment by wyouflf** [comment]
谢谢反馈, 已修复此问题
