### ISSUE TITLE
是否支持https接口

### ISSUE THREAD

**Issue by ZhengTaiChen** [wyouflf/xUtils3#344]

**Comment by TestSmirk** [comment]
默认信任所有的https

**Comment by LongAgoLong** [comment]
有什么特殊配置吗？我在安卓4.4及以上访问https接口是正常的，但是4.2的手机无法访问

**Comment by TestSmirk** [comment]
没有特殊配置,源码里面写的默认信任所有.

**Comment by LongAgoLong** [comment]
但是在4.2的手机上无法访问成功。
  RequestParams requestParams = new RequestParams(Urls.getSlide());
        requestParams.setConnectTimeout(8000);
            requestParams.addBodyParameter("province", GlobalParameters.filter_province);
直接这样写然后发起请求

**Comment by TestSmirk** [comment]
一直都没有4.2的手机.我也是这么写的.

**Comment by wyouflf** [comment]
不需要特殊设置兼容的，有问题贴一下错误信息
