### ISSUE TITLE
org.xutils.ex.FileLockedException 异常信息

### ISSUE THREAD

**Issue by tigerphz** [wyouflf/xUtils3#35]
11-29 15:33:43.449 7130-7130/com.tigeroid E/x_log:ImageLoader.onError(L:409): org.xutils.ex.FileLockedException: /storage/emulated/0/Android/data/com.tigeroid/cache/xUtils_img/8ce22f4362f505df8535f7e3110519f9
11-29 15:33:43.449 7130-7130/com.tigeroid E/x_log:ImageLoader.onError(L:409):     at org.xutils.cache.LruDiskCache.createDiskCacheFile(LruDiskCache.java:164)
11-29 15:33:43.449 7130-7130/com.tigeroid E/x_log:ImageLoader.onError(L:409):     at org.xutils.http.loader.FileLoader.initDiskCacheFile(FileLoader.java:263)
11-29 15:33:43.449 7130-7130/com.tigeroid E/x_log:ImageLoader.onError(L:409):     at org.xutils.http.loader.FileLoader.load(FileLoader.java:176)
11-29 15:33:43.449 7130-7130/com.tigeroid E/x_log:ImageLoader.onError(L:409):     at org.xutils.http.loader.FileLoader.load(FileLoader.java:41)
11-29 15:33:43.449 7130-7130/com.tigeroid E/x_log:ImageLoader.onError(L:409):     at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:81)
11-29 15:33:43.449 7130-7130/com.tigeroid E/x_log:ImageLoader.onError(L:409):     at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:222)
11-29 15:33:43.449 7130-7130/com.tigeroid E/x_log:ImageLoader.onError(L:409):     at org.xutils.http.HttpTask$RequestWorker.run(HttpTask.java:506)

**Comment by tigerphz** [comment]
用的3.0.10最新版本

**Comment by wyouflf** [comment]
这个异常时加载图片时快速重用产生的, 会自动重试. 忽略这个异常日志, 下个版本不在把这个调试日志去掉.
