### ISSUE TITLE
【建议】把四个库分开提供

### ISSUE THREAD

**Issue by natman44** [wyouflf/xUtils3#352]
现在较多的app会遇到方法数限制，建议把四个独立的部分分开提供，分开引入。

**Comment by JerrryLiu** [comment]
四个功能模块在Github上面没有替代品

**Comment by wingsum93** [comment]
network library wh can use okhttp,
for load picture, we can use glide.
for view inject use butterknife.
.
only db part is essential.

**Comment by reaper12** [comment]
同意，把DB提出来

**Comment by Asyncle** [comment]
I  issuesed  this question  early but no response

**Comment by liupeng110** [comment]
okhttp,imageloader,butterknife,ormlite

**Comment by Dordong** [comment]
db can use litepal

**Comment by wyouflf** [comment]
参考 https://github.com/wyouflf/xUtils3/issues/512
