### ISSUE TITLE
listview滑动时不加载图片

### ISSUE THREAD

**Issue by LuoGuoXin** [wyouflf/xUtils3#353]
用x.image().bind加载图片的时候，怎样让滑动的时候不加载图片，不要那么卡？

**Comment by SeekingAlone** [comment]
已醉，卡爆

**Comment by bacy** [comment]
我之前提过 xutils1里面 有个主线程中判断key在diskcache中能否找到对应文件的方法非常耗时，我去掉后就流畅多了，不知道新版本有没有优化这一块

**Comment by wyouflf** [comment]
滑动时会自动停止加载已被listview回收重利用的item对应图片
