### ISSUE TITLE
【疑问】Eclipse 使用，怎样提取xUtils3 jar 包？

### ISSUE THREAD

**Issue by JerrryLiu** [wyouflf/xUtils3#356]
### 【疑问】armeabi、armeabi-v7a、x86三个文件夹中都有**“.so”**文件，使用哪个文件夹**.so**文件？为什么要使用**.so**文件?

xUtils 3 ReadeMe 中写到
如果使用eclipse可以 点击这里下载aar文件, 然后用zip解压, 取出jar包和so文件.

下载aar 文件解压，**jar** 包如下
![image](https://cloud.githubusercontent.com/assets/7981299/16511018/3a3a64cc-3f7e-11e6-9daf-a0ac215380fa.png)

**但 .so文件**

![image](https://cloud.githubusercontent.com/assets/7981299/16511043/7dc11f24-3f7e-11e6-8232-1334f7759902.png)

@wyouflf @yan96in @DonaldGuo

**Comment by yuCharles** [comment]
放弃eclipse吧，用AS痛苦一周，爽一生

**Comment by yuCharles** [comment]
so文件的作用。。。哎，，小白同学，去查查 Android JNI你就知道了
