### ISSUE TITLE
LogUtil 建议

### ISSUE THREAD

**Issue by tang85718** [wyouflf/xUtils3#357]
LogUtil下面的所有方法能加个安全检查不？
像下面这样
public static void d(String content) {
        if (!x.isDebug())
            return;
        if (content == null)
            return;
        String tag = generateTag();

```
    Log.d(tag, content);
}
```

有时候如果不小心传入null的话就会导致crash

**Comment by tang85718** [comment]
用的地方多，如果在外面判断代码不够漂亮了。

**Comment by wyouflf** [comment]
感谢反馈, 3.6.9版本优化了这个接口
