### ISSUE TITLE
数据库加密

### ISSUE THREAD

**Issue by yhsj0919** [wyouflf/xUtils3#36]
希望数据库能进行加密处理，保证数据安全

**Comment by liuy9** [comment]
希望数据库能进行加密处理，保证数据安全

**Comment by zxlmickey** [comment]
同上

**Comment by 247321453** [comment]
static class StringColumnConverter2 extends StringColumnConverter{
        @Override
        public String getFieldValue(Cursor cursor, int i) {
            return StringUtil.de(super.getFieldValue(cursor, i));
        }

        @Override
        public String fieldValue2DbValue(String s) {
            return StringUtil.en(s);
        }
    }
    static {
        ColumnConverterFactory.registerColumnConverter(String.class, new StringColumnConverter2());
    }

加密和解密自己处理

**Comment by zxlmickey** [comment]
static class StringColumnConverter2 extends StringColumnConverter{
    @Override
    public String getFieldValue(Cursor cursor, int i) {
        return StringUtil.de(super.getFieldValue(cursor, i));
    }

    @Override
    public String fieldValue2DbValue(String s) {
        return StringUtil.en(s);
    }
}
static {
    ColumnConverterFactory.registerColumnConverter(String.class, new StringColumnConverter2());
}
加密和解密自己处理
这个东西怎么使用?

**Comment by zxlmickey** [comment]
搞懂了，把要加密的列设置一个自定义数据类型，然后使用ColumnConverter在读写时进行加密和解密

**Comment by zhbzhbzhbz** [comment]
感觉数据库加密的功能很有用

**Comment by zhbzhbzhbz** [comment]
> ColumnConverterFactory

请问这个是在哪儿调用？有更完整的范例么~

**Comment by zhbzhbzhbz** [comment]
因为上述方案只能对列加密，还有一个方案是用SQLCipher来改造XUtils，见：https://blog.csdn.net/Tobi2015/article/details/51077314
