### ISSUE TITLE
在genymotion等第三方模拟器上无法用x.image().bind()加载图片。

### ISSUE THREAD

**Issue by origin005x** [wyouflf/xUtils3#360]
难道没人碰到过用x.image().bind()显示图片的时候，在genymotion模拟器上不行的问题吗？
有的时候加载不出来，但app不崩溃，有的时候会直接导致APP崩溃。崩溃时的日志只有一行，fatal什么什么的，好像是c层的错误。

**Comment by wyouflf** [comment]
更新最新版本, 已经移除依赖c的库
