### ISSUE TITLE
x.image().bind()有个非常危险致命的bug

### ISSUE THREAD

**Issue by origin005x** [wyouflf/xUtils3#361]
当使用x.image().bind()加载图片时，如果给定的url是个文件路径，那么当从此路径加载不到图片时，xutils3就会把此路径干掉。
这个是非常危险的，当图片URL不小心写错，比如写为了sd卡根路径，那么真个SD卡的东西都会被删除。
或者服务器端的图片URL被人恶意配成sd卡根目录，那么所有用户的SD目录的东西都会被清除。
”

**Comment by liaolintao** [comment]
是啊,是啊!我把图片偏移后,加载不出图片,图片文件就不见了,没想到好的解决办法啊!

**Comment by wyouflf** [comment]
新版已修复
