### ISSUE TITLE
xUtils + ViewFlipper 只显示第一张图片

### ISSUE THREAD

**Issue by GodLikeThomas** [wyouflf/xUtils3#364]
xUtils + ViewFlipper 只显示第一张图片，别的都显示空白。求解决
代码如下

ImageView[] imvs ={mPic1,mPic2,mPic3};
ImageOptions options1 = new ImageOptions.Builder().setFailureDrawableId(R.mipmap.ic_launcher).build();

```
    for (int i = 0; i < imvs.length; i++) {
        x.image().bind(imvs[i],mDetail.getImage().get(i),options1);
    }
```

**Comment by langren1353** [comment]
我也遇见了同样的问题，暂时不知道怎么办了

**Comment by wyouflf** [comment]
已优化此逻辑, 更新到新版本
