### ISSUE TITLE
关于drawable引起的内存泄漏问题的疑问

### ISSUE THREAD

**Issue by bacy** [wyouflf/xUtils3#368]
private final static LruCache<MemCacheKey, Drawable> MEM_CACHE
看xUtils3的memCache，存放的是drawable，之前看过很多文章说静态drawable，会导致一直保有View对象，导致View甚至Activity不能回收。
参考这篇文章：http://blog.csdn.net/sunchaoenter/article/details/7209635
我想知道xUtils会不会有这个内存泄漏的问题

**Comment by wyouflf** [comment]
drawable不会和view之前强关联，使用的是WeakReference，这一点可以参考drawable和imageview的源码
