### ISSUE TITLE
Webview 不能重登陆

### ISSUE THREAD

**Issue by cekowu** [wyouflf/xUtils3#37]
Session 超时，重登陆不能重登陆，cookie管理这个版本有更改吗？

**Comment by cekowu** [comment]
发现是3.10上故意取消了cookie 的保存，这个是为什么取消？
 //保存cookie
            try {
                Map<String, List<String>> headers = connection.getHeaderFields();
                if (headers != null) {
                    COOKIE_MANAGER.put(url.toURI(), headers);
                }
            } catch (Throwable ex) {
                LogUtil.e(ex.getMessage(), ex);
            }

**Comment by cekowu** [comment]
以前我们通过DbCookieStore.INSTANCE.get(URI.create(muserDb.getUrl())).toString());方法获取cookie 然后同步到浏览器中，现在好像没有保存cookie 相关的值到数据库

**Comment by cekowu** [comment]
不知道分析的对不对

**Comment by wyouflf** [comment]
没有取消, 添加了设置方法: CookieHandler.setDefault(COOKIE_MANAGER);

**Comment by cekowu** [comment]
好的谢谢，我对比代码的时候发现有些不一样，行谢谢了哈
