### ISSUE TITLE
xutils3 postSync

### ISSUE THREAD

**Issue by cendy2016** [wyouflf/xUtils3#373]
RequestParams params = new RequestParams(url);
params.addParameter("cls", "Reguser");// 检测当前登录状态
params.addParameter("fun", "CheckLogin");
params.addParameter("SessionId", AppConfig.sessionId);
try {
    BaseInfo result = new BaseInfo();
    result = x.http().postSync(params, BaseInfo.class);
    isLogin = result.getStatus().equals("error") ? false : true;
} catch (Throwable throwable) {
    throwable.printStackTrace();
    isLogin = false;
}

error:
java.lang.NullPointerException: Attempt to invoke interface method 'void com.android.okhttp.internal.http.Transport.writeRequestHeaders(com.android.okhttp.Request)' on a null object reference

**Comment by ypf168326** [comment]
执行 x.http().getSync(requestParams,Resp4Base.class);报同样的错

Attempt to invoke interface method 'void com.android.okhttp.internal.http.Transport.writeRequestHeaders(com.android.okhttp.Request)' on a null object reference

**Comment by wyouflf** [comment]
你在主线程执行的，还是没有初始化x.ext.init(app)
