### ISSUE TITLE
快速http请求下(100毫秒一次,纯粹是为了测试极限性能),偶尔报错

### ISSUE THREAD

**Issue by BlackJackLi** [wyouflf/xUtils3#374]
Error By: java.lang.NullPointerException:Attempt to read from field 'java.lang.String org.xutils.common.util.KeyValue.key' on a null object reference
                                                                                                                Error Detail: org.xutils.http.request.HttpRequest.buildQueryUrl(HttpRequest.java:77)
                                                                                                                org.xutils.http.request.UriRequest.<init>(UriRequest.java:34)
                                                                                                                org.xutils.http.request.HttpRequest.<init>(HttpRequest.java:61)
                                                                                                                org.xutils.http.request.UriRequestFactory.getUriRequest(UriRequestFactory.java:48)
                                                                                                                org.xutils.http.HttpTask.createNewRequest(HttpTask.java:139)
                                                                                                                org.xutils.http.HttpTask.doBackground(HttpTask.java:199)
                                                                                                                org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
                                                                                                                org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21)
                                                                                                                java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                                                java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                                                java.lang.Thread.run(Thread.java:818)

使用post请求,带一个jason的参数,以100毫秒一次的速度请求,偶现

**Comment by BlackJackLi** [comment]
问题已经解决,根本原因是多线程调用导致参数的不确定性,具体情况如下:
BaseParams类中的方法
checkBodyParams() 会对内部参数进行整合,这个方法在几个跟参数相关的方法中都被调用,而我在RequestTracker的onStart()中使用了getBodyCotent方法来进行参数打印,结果有可能就是后台线程也使用相关方法获取参数,导致俩线程一起执行checkBodyParams(),参数便有可能丢失.目前能想到的解决方案也相当简单,加上同步关键字:
synchronized void checkBodyParams()
这样就能保证只有一个线程能够执行checkBodyParams()

**Comment by wyouflf** [comment]
问题已修复, 谢谢反馈
