### ISSUE TITLE
http post带上json body参数的情况下有偶现参数丢失的情况,json变成了{}发往服务器

### ISSUE THREAD

**Issue by BlackJackLi** [wyouflf/xUtils3#375]
if (HttpMethod.permitsRequestBody(httpMethod)) {
                xParams.setAsJsonContent(true);
                String JsonParams = xParams.toJSONString();
                xParams.setBodyContent(JsonParams);
            }
这样做手动设置就不会有问题.
但是如果仅仅设置
xParams.setAsJsonContent(true);
就有很低概率的丢失参数的情况,15秒一次的请求大概25分钟会出现一次,偶现,而且让人摸不着头脑.
看作者的源码,有一个检查参数的方法,只要asJsonContent==true就会转化参数成为json的,通常都会有效,但是不知道为什么就有很低的概率出现一次参数丢失,然后下次这样的请求之后又好了

**Comment by BlackJackLi** [comment]
问题已经解决,根本原因是多线程调用导致参数的不确定性,具体情况如下:
BaseParams类中的方法
checkBodyParams() 会对内部参数进行整合,这个方法在几个跟参数相关的方法中都被调用,而我在RequestTracker的onStart()中使用了getBodyCotent方法来进行参数打印,结果有可能就是后台线程也使用相关方法获取参数,导致俩线程一起执行checkBodyParams(),参数便有可能丢失.目前能想到的解决方案也相当简单,加上同步关键字:
synchronized void checkBodyParams()
这样就能保证只有一个线程能够执行checkBodyParams()

**Comment by wyouflf** [comment]
新版本已优化checkbodyparams过程
