### ISSUE TITLE
如何用post方式发送OutputStreamWriter类型数据

### ISSUE THREAD

**Issue by guozhiling** [wyouflf/xUtils3#376]
当Request Headers:
Content-Type:application/json; charset=UTF-8
类型时候
如何使用xutils3 post发送OutputStreamWriter数据

**Comment by BlackJackLi** [comment]
要么把数据写到一个文件上,再使用表单方式上传文件.要么把数据写到ByteArrayOutputStream中,再读出byte[]放到ByteArrayInputStream以InputStream的方式上传.如果数据量大的话推荐第一种,因为节省内存.
