### ISSUE TITLE
viewInject效率问题

### ISSUE THREAD

**Issue by xumengyin** [wyouflf/xUtils3#377]
请教一下，看了xuits的关于viewInject activity的代码后，发现不断递归循环调用 然后通过反射获取的注解，这样处理和ButterKnife 这些注解框架 重写注解处理器的方式， 会不会效率方面 会显得差一些，菜鸟提问，千万别见笑，期待您的回答

**Comment by bacy** [comment]
看你怎么想咯，butterknife效率不也比findviewbyid低，而且生成一堆垃圾代码，容易超过65536限制

**Comment by wyouflf** [comment]
注解的反射的效率系统会不断提高，但是字节码的兼容性和调试的便捷性ButterKnife很难持续保证
