### ISSUE TITLE
x.image().bind(container,uri,callback)    callback 不进  onSuccess 等方法 ，只进 onWaiting

### ISSUE THREAD

**Issue by deeplyloving** [wyouflf/xUtils3#379]
x.image().bind(container,uri,new Callback.ProgressCallback<Drawable>(){
            @Override
            public void onSuccess(Drawable result) {
                callback.onSuccess(result);
            }

```
        @Override
        public void onError(Throwable ex, boolean isOnCallback) {
            callback.onError(ex);
        }
```

问题原因如下
xutils .3.3.36  ImageLoader  validView4Callback 方法 中  
if (view.getVisibility() != View.VISIBLE) {
                            otherLoader.cancel();
                            return false;
                        } else {
                            return true;
                        }

某些时候  隐藏的时候仍需加载。例如 ImageSwitcher 先加载 nextView 完成 再显示 而nextView是隐藏的        建议添加参数支持隐藏。      否则只能用 loadDrawble 或者  loadFile

**Comment by wyouflf** [comment]
新版本已优化此问题, 谢谢反馈
