### ISSUE TITLE
Http问题

### ISSUE THREAD

**Issue by zhangtengchao** [wyouflf/xUtils3#38]
Http请求怎样设置超时？读超时这类的？还是默认已经设置好了？ catch (Throwable throwable)我要怎么来严格区分哪些错误是服务器错误，哪些错误是网络错误？

**Comment by wyouflf** [comment]
超时等设置在RequestParams有对应的属性.

onError返回的错误信息:

                if (ex instanceof HttpException) { // 网络错误
                   HttpException httpEx = (HttpException) ex;
                   int responseCode = httpEx.getCode();
                   String responseMsg = httpEx.getMessage();
                   String errorResult = httpEx.getResult();
                   // ...
               } else { // 其他错误
                   // ...
               }
