### ISSUE TITLE
网络访问中，使用get/post方法，其中的回调参数是一个父接口，是否会导致高耦合的发生，从而背离开闭原则？

### ISSUE THREAD

**Issue by niit-qd** [wyouflf/xUtils3#380]
下面是我的一个想法，不知道是否正确。

以org.xutils.HttpManagerget(RequestParams entity, Callback.CommonCallback<T> callback)为例：

对于get/post方法中的回调参数，xUtils3用了父接口的形式，这样做的结果是，如果需要适配子接口，那么get/set方法必须在内部实现它可以接受哪些子接口。这种设计导致了高度耦合，加大了类型与类型之间的联系，不是一个很好的设计方案。
个人认为，一个比较好的设计方案是，应该设计一个“超级”接口，它提供的接口方法可以解决目前所知的所有的需求。如果该接口提供的方法太多，但是调用者在大多数情况下并不需要，可以使用基于方法适配器模式创建一些适配器，该适配器是一个类（一般是抽象类），它对部分或者全部接口方法进行“空”实现。

**Comment by wyouflf** [comment]
目前的callback可以各种组合，根据需要实现，耦合更少
