### ISSUE TITLE
关于图片缓存

### ISSUE THREAD

**Issue by niit-qd** [wyouflf/xUtils3#381]
能否在ImageOption中添加一个参数，用于表示在获取网络图片识别的时候使用缓存中的image？

我的想法是，远程图片加载失败的时候，设备本地可能已经由之前下载好的文件缓存，这个时候，处理远程图片加载失败的方式可能有以下几种：
1）不处理
2）使用默认是失败图片
3）使用本地缓存中的缓存文件重新加载，如果它存在的话，且加载过程中没有出现失败；如果加载失败，则使用方式2）或者1）。

**Comment by wyouflf** [comment]
callback使用cachecallback可以实现你的逻辑，参考readme的介绍
