### ISSUE TITLE
xUtils3.36版本混淆后Http请求的问题

### ISSUE THREAD

**Issue by Sxxjava** [wyouflf/xUtils3#386]
07-30 21:25:53.040 6445-6445/com.simple.demo W/System.err: java.lang.IllegalArgumentException: FindGenericType:class com.simple.demo.network.user.AccountApi$1, declaredClass: interface org.xutils.common.Callback$CommonCallback, index: 0
07-30 21:25:53.040 6445-6445/com.simple.demo W/System.err:     at org.xutils.common.util.ParameterizedTypeUtil.getParameterizedType(Unknown Source)
07-30 21:25:53.040 6445-6445/com.simple.demo W/System.err:     at org.xutils.http.HttpTask.resolveLoadType(Unknown Source)
07-30 21:25:53.040 6445-6445/com.simple.demo W/System.err:     at org.xutils.http.HttpTask.doBackground(Unknown Source)
07-30 21:25:53.040 6445-6445/com.simple.demo W/System.err:     at org.xutils.common.task.TaskProxy$1.run(Unknown Source)
07-30 21:25:53.040 6445-6445/com.simple.demo W/System.err:     at org.xutils.common.task.PriorityRunnable.run(Unknown Source)
07-30 21:25:53.040 6445-6445/com.simple.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
07-30 21:25:53.040 6445-6445/com.simple.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
07-30 21:25:53.040 6445-6445/com.simple.demo W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by Lerist** [comment]
请问你的问题解决了吗?

**Comment by Sxxjava** [comment]
@Lerist 已经解决了,按照Simple项目中的混淆就不会有这个问题
