### ISSUE TITLE
在使用xutils3加载过多图片时候，发现内存（memory）占用过高，导致OOM

### ISSUE THREAD

**Issue by guozhiling** [wyouflf/xUtils3#390]
最近做了个列表（RecyclerView），列表上有很多很多的图片展示,含分页，每次加载更多后，内存使用量就暴增，当加载了N多页以后就出现OOM现象，通过mat工具分析以后。发现是ImageLoader中MEM_CACHE内存使用量过高导致,请问如何避免这个现象。

**Comment by Leongeneral** [comment]
@guozhiling 请问这个问题解决了吗？

**Comment by wyouflf** [comment]
使用新版本试试, 建议给这是imageOptions的size属性, 而不是完全依靠自动识别.
