### ISSUE TITLE
onLoading不执行

### ISSUE THREAD

**Issue by 925941723** [wyouflf/xUtils3#391]
文件下载的时候，用ProgressCallback<File>的onLoading方法不执行，但是文件有在下载。

**Comment by cywang1984** [comment]
我也遇到这个问题，我这边的原因是file的文件太大，response的header里Content-Length是一个大的float，超过了int范围。
HttpRequest中读取contentLength值用的是getContentLength，里面用到的是getHeaderInt，直接返回了0。

**Comment by 925941723** [comment]
这个问题当时好像不是因为这个int的问题，当时我也改过float。后面是因为那个long型的total返回一直为空，有的时候是负数。后面改了源码解决了

**Comment by sweet2o09** [comment]
能告知下怎么解决么

**Comment by 925941723** [comment]
我记得是在一个叫什么header的头文件里面改的源码，你在那个文件打个断点就知道是哪段代码出问题了

**Comment by wigins** [comment]
改的源码解决的问题？。。这算源码有问题吗？
