### ISSUE TITLE
Event点击事件无效

### ISSUE THREAD

**Issue by UltramanTIGA** [wyouflf/xUtils3#394]
@ContentView(R.layout.login_view)
public class LoginActivity extends BaseActivity{

```
@ViewInject(R.id.btn_login) private Button btnLogin;
@ViewInject(R.id.et_login_phone) private EditText etTelphone;
@ViewInject(R.id.et_login_password) private EditText etPassword;


@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.login_view);
    setTranslucentStatuBar();
}

@Event(value = R.id.btn_login)
private void login(){
    Toast.makeText(this,"登陆",Toast.LENGTH_SHORT).show();
}
```

}
按上面那样写的，为什么btn_login的点击事件一直是无效的，还有demo里写的是@Event(R.id.xxx)，但介绍里是@Event(value = R.id.xxx)，到底哪个是对的

**Comment by chen2174471** [comment]
都对，但你得确认是否在基类中调用了 x.view().inject(this);

**Comment by xionghf** [comment]
private void login(){
    Toast.makeText(this,"登陆",Toast.LENGTH_SHORT).show();
}
改成

private void login(View view){
    Toast.makeText(this,"登陆",Toast.LENGTH_SHORT).show();
}

**Comment by xionghf** [comment]
还有就是必须在setContentView之后调用x.view.inject(this);

**Comment by UltramanTIGA** [comment]
感谢楼上的回答，已经解决了~
