### ISSUE TITLE
动态添加的View的在执行gc后所注册的点击事件失效

### ISSUE THREAD

**Issue by cwjlxh** [wyouflf/xUtils3#395]
private class Holder{
@Event(R.id.ib_shrink)
    private void onShrinkClick(View view){
        Timber.d("onShrinkClick call");
        expandIdx = -1;
        layoutWorkExp(workExpContainer);
    }
}

通过x.view().inject(object,view)方法注册后，如果不进行gc操作，事件可以正常使用，但一旦执行gc操作后，所注册的事件就失效了。

**Comment by wyouflf** [comment]
确保你的object和view参数声明周期足够长的, 不然其他方式添加事件也有可能产生异常.
