### ISSUE TITLE
如何导入xUtils3

### ISSUE THREAD

**Issue by NeighborWang** [wyouflf/xUtils3#399]
如何使用

**Comment by zhview** [comment]
build.gradle里面配置依赖：compile 'org.xutils:xutils:3.3.26'

**Comment by NeighborWang** [comment]
请问  那些文件导入哪一部分  我全部放进去后  所有文件都显示一个 红色的 j

**Comment by songhaonangit** [comment]
build.gradle里面配置依赖：compile 'org.xutils:xutils:3.3.36'

**Comment by JingDeQin** [comment]
有三个build.gradle
你说的是哪个是app、导入的xutils3、这个整个项目的build.gradle
导入xutils3不是就导入下载xutils3-master的xutils，还是导入这完整的解压包

**Comment by JingDeQin** [comment]
只有在app 的 build.gradle能添加compile 'org.xutils:xutils:3.3.36'但是还是报错plugin with id com.github.dcendents.android-maven not found
