### ISSUE TITLE
开启WAL时打包数据库的读取问题

### ISSUE THREAD

**Issue by Hundecim** [wyouflf/xUtils3#403]
在assets文件夹里打包了生成的数据库文件，不开启WAL时只打包db文件，应用启动时把db文件拷贝到指定的数据库目录下，数据库的数据使用没有问题；但是开启WAL时，打包了db和db-wal文件，把这两个文件拷贝到指定的数据库目录下，数据读取不出来了，求教是什么原因，有没有解决办法？

**Comment by wyouflf** [comment]
去掉db-wal文件试试
