### ISSUE TITLE
xUtils3解压Gzip失败

### ISSUE THREAD

**Issue by langren1353** [wyouflf/xUtils3#405]
请求地址：https://sc.ac.10086.cn/loginNew/index.jsp
请求方式：GET
错误log：![图片](http://ww4.sinaimg.cn/large/6a155794gw1f76dtyfnvaj20fp0eggrv.jpg)
描述：只加上了url这个参数，没有加入其它任何参数(Header)
版本：xutils-3.3.25

**Comment by Jay-Y** [comment]
java.io.EOFException:内部类BlockDataInputStream.的方法peekByte抛出的异常，意思就是到达了文件的末尾，程序却没有正常结束读取文件内容，可以单步调试一下看看到达文件末尾之后程序为什么没有停下来
该地方解决方案为:System.setProperty("http.keepAlive", "false");
