### ISSUE TITLE
patch 请求报错

### ISSUE THREAD

**Issue by lzw4540518** [wyouflf/xUtils3#406]
HttpMethod.PATCH 请求时 在4.4的手机上会报错 Unknown method 'PATCH'; must be one of [OPTIONS, GET, HEAD, POST, PUT, DELETE, TRACE]   但是在5.0的手机上没问题.
ex=java.net.ProtocolException: Unknown method 'PATCH'; must be one of [OPTIONS, GET, HEAD, POST, PUT, DELETE, TRACE]
isOnCallback=false
extra=null

**Comment by wyouflf** [comment]
已修复试试新版本
