### ISSUE TITLE
清空线程池线程的功能

### ISSUE THREAD

**Issue by cekowu** [wyouflf/xUtils3#41]
界面切换时需要将上一个页面的所有线程终止掉，没有批量终止线程池线程的功能

**Comment by wyouflf** [comment]
添加自定义Callback, 由Callback决定是否取消链接:

public abstract class BindingPageCallback<ResultType>
            implements Callback.CommonCallback<ResultType>, Callback.Cancelable {

        private boolean cancelled = false;
        private final WeakReference<Object> pageRef;

        public BindingPageCallback(Object page) {
            this.pageRef = new WeakReference<Object>(page);
        }

        @Override
        public void cancel() {
            cancelled = true;
        }

        @Override
        public boolean isCancelled() {
            if (cancelled) {
                return true;
            } else {
                Object page = pageRef.get();
                if (page == null) {
                    return true;
                }

                if (page instanceof Activity) {
                    return ((Activity) page).isFinishing();
                } else if (page instanceof Fragment/* v4? */) {
                    return ((Fragment) page).isDetached();
                } else {
                    .....
                }
            }

            return false;
        }
    }
