### ISSUE TITLE
文档和代码不一样，还请 大神 看下

### ISSUE THREAD

**Issue by Freedomhxb** [wyouflf/xUtils3#415]
文档
       x.image().loadFile(url, imageOptions, new Callback.CommonCallback<File>() {...});
代码
       x.image().loadFile(String url, ImageOptions options, Callback.CacheCallback<File> callback);

这两个callback不一样，是不是文档里写错了？还是我错了？还请大神指导，谢谢。。。

**Comment by Freedomhxb** [comment]
怎么就没人回答呢？ 虽然这两个是callback是继承关系。但是能用cache的地方，不一定能用common吧。

**Comment by Freedomhxb** [comment]
怎么就没人回答的我呢？。。。大家看不见我吗？ 即使我错了，还请你们指出来。(┬＿┬)，谢谢各位了。

**Comment by xionghf** [comment]
使用commomcallback就是启用cache，使用cachecallback，并在oncache中返回false，放弃使用本地缓存

需要本地缓存的话，直接commoncallback就行，毕竟手机端需要缓存才是常态

**Comment by xionghf** [comment]
这些源码里都能看到，研究研究源码吧
