### ISSUE TITLE
点击事件问题

### ISSUE THREAD

**Issue by zhangtengchao** [wyouflf/xUtils3#42]
例如有个button，我要在代码里动态的设置OnClickListener，但是现在点击事件的方法必须是private的，和View.OnClickListener public不一致，必须要搞两套。有什么办法能解决这个问题么？最好是能像xutils之前版本一样，能公用一个点击方法

**Comment by wyouflf** [comment]
解决办法: 实现View.OnClickListener, 在实现的方法里面调用带有注解的私有方法.

事件的方法本身就应该是私有的, public会造成很多误用, 例如public方法可以被其他类直接调用, 最重要的是可以被子类覆盖, 但是@Event是和具体的方法是绑定的, 不支持继承覆盖.

**Comment by zhangtengchao** [comment]
哦哦，3Q

**Comment by xxxifan** [comment]
从ButterKnife转过来，用private是一个不错的想法，但有时候不能public确实不方便，能不能也支持public方法？
