### ISSUE TITLE
android studio2.2导入xutils3报错

### ISSUE THREAD

**Issue by JingDeQin** [wyouflf/xUtils3#420]
http://bbs.csdn.net/topics/392027975?locationNum=2

**Comment by JingDeQin** [comment]
我发的网址是我没有解决的，找了一些没有解决。看到请回消息，谢谢

**Comment by xionghf** [comment]
classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.2'
classpath 'com.github.dcendents:android-maven-gradle-plugin:1.4.1'

xutils module下的build.gradle中:
apply plugin: 'com.github.dcendents.android-maven'
apply plugin: 'com.jfrog.bintray'

确认一下有没有，以及版本号是否一致

**Comment by JingDeQin** [comment]
解决了 不报错了就添加
classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.2'
classpath 'com.github.dcendents:android-maven-gradle-plugin:1.4.1'
就没问题了

**Comment by wyouflf** [comment]
请使用新版Android studio
