### ISSUE TITLE
@Event事件注解问题2，关于RadioButton状态问题

### ISSUE THREAD

**Issue by imyyq-star** [wyouflf/xUtils3#423]
我在旧项目中使用3.1.22，是可以正常使用ViewInject和Event的。然而我发现以下问题：
我想监听RadioButton的Click事件，在回调中，永远将RadioButton的状态设为false。也就是RadioButton在视图中的表现是不会出现true的状态的。
如下：
    @Event(value = R.id.rb_test)
    private void test(View view)
    {
        RadioButton rb = (RadioButton) view;
        rb.setChecked(false);
    }
以上代码当我有时间间隔一下一下点击的时候，是正常的。但是当我快速双击RadioButton的时候，RadioButton的视图状态变成了true。

于是我不使用Event事件注解，使用系统自带的findViewById和setOnClickListener。如下：
        rbTest = (RadioButton) findViewById(R.id.rb_test);
        rbTest.setOnClickListener(new View.OnClickListener()
        {
            @Override
            public void onClick(View view)
            {
                RadioButton rb = (RadioButton) view;
                rb.setChecked(false);
            }
        });
以上代码无论我多快速的点击RadioButton，都不会出现true的状态。

以上，请教下是什么原因造成的？

**Comment by imyyq-star** [comment]
尝试过在ButterKnife是没有这样的问题的

**Comment by xionghf** [comment]
ButterKnife是代码注入框架，xUtils3是反射框架，这是前提，两者不一样，只是看起来一样

至于你说的这个问题，是因为框架里对onClick和onItemClick有防止快速点击的机制（org.xutils.view.EventListenerManager），间隔为300ms，也就是说如果你快速点击的话，第二次点击事件不会走你的这个方法，只会执行RadioButton原本的toggle方法，如下：

android.widget.CompoundButton
```
public void toggle() {
    setChecked(!mChecked);
}

@Override
public boolean performClick() {
    toggle();

    final boolean handled = super.performClick();
    if (!handled) {
        // View only makes a sound effect if the onClickListener was
        // called, so we'll need to make one here instead.
        playSoundEffect(SoundEffectConstants.CLICK);
    }

    return handled;
}
```

如果真的需要写死的话（感觉很奇怪），直接用setOnClickListener吧

**Comment by wyouflf** [comment]
@imyyq-star click事件写了一个防止快速点击的逻辑
