### ISSUE TITLE
关于视图注入和事件监听的建议

### ISSUE THREAD

**Issue by imyyq-star** [wyouflf/xUtils3#424]
Hi，我理解的xUtils中的ViewInject和Event是通过运行时反射的方式实现的对吗？
我觉得xUtils在其他方面都很方便和强大，但是这个注解的能不能不使用反射实现？转而使用编译时生成代码的方式。这样不会影响性能。（参考ButterKnife）。

**Comment by wyouflf** [comment]
反射在android4.0开始对性能的影响越来越小, 系统还会继续优化, 修改字节码的方式是不被建议的, 而且未来java不在开源, 字节码兼容的维护成本和稳定性可能都是问题.
