### ISSUE TITLE
从另外一台电脑拷贝项目过来后，发现请求的url带上了serialVersionUID=0这个参数导致后端验证不通过

### ISSUE THREAD

**Issue by Ignorantforce** [wyouflf/xUtils3#428]
之前都没有出现过这个问题，现在拷贝项目到另外一台机子发现所有请求的url都会前后带上serialVersionUID=0这样，导致请求不正确（后端有加密验证），但原来的电脑上却一切正常
![image](https://cloud.githubusercontent.com/assets/22272002/19418140/9df46960-93f0-11e6-839d-f62e306b9ed4.png)
请问这是怎么了，搞了半天了也没发现问题所在，连手机编译调试的时候就会这样，但是如果单独编译一个包安装却没问题

**Comment by ypf168326** [comment]
我也遇到和你一样的问题，URL参数后面自动加上&serialVersionUID=0，导致接口调用失败，也不知道这个为什么会自动加上去，你这个问题后来解决了没？

**Comment by Ignorantforce** [comment]
@ypf168326 还没解决

**Comment by ypf168326** [comment]
这个问题到现在还没解决，刚自己又尝试了一下，还是存在，我在想是不是框架本身的类实现了序列化，导致默认自动带上ID

**Comment by hjb0924** [comment]
已踩坑，特殊处理了！
new 完之后，先清除一下 requestParams.clearParams();

**Comment by ypf168326** [comment]
好的，我试试。

hjb0924 <notifications@github.com>于2017年9月22日 周五17:03写道：

**Comment by wyouflf** [comment]
新版本自动处理serialVersionUID的问题
