### ISSUE TITLE
按README的提示无法初始化

### ISSUE THREAD

**Issue by sktoozaki** [wyouflf/xUtils3#43]
Hello，
我在gradle中添加依赖后，按照README的提示进行初始化，找不到x所在的包，是人品问题么。。。

**Comment by wyouflf** [comment]
网不好吧, 包没同步下来, 多试几次.

compile 'org.xutils:xutils:3.1.+'
// or
// compile 'org.xutils:xutils:3.1.8'

**Comment by sktoozaki** [comment]
网络没问题的，其他依赖都能用
上面的两种方式都试过了，还是不行，奇了怪了，只有我遇到这问题么
