### ISSUE TITLE
下载大文件卡主

### ISSUE THREAD

**Issue by smallgirl** [wyouflf/xUtils3#430]
xutils2 启动下载方法的时候，在调用post方法，很大几率出现不走成功和失败的回调方法，
xutils3 下载大文件卡主不动没有设置了超时，网络正常
10-18 12:03:58.529 28394-28394/com.kazeik.databaseslib.databaseslib1 E/tag: total=8147126current=6145623pencent75%item.hashCode()437674568
10-18 12:03:58.828 28394-28394/com.kazeik.databaseslib.databaseslib1 E/tag: total=8147126current=6194775pencent76%item.hashCode()437674568
10-18 12:03:59.216 28394-28394/com.kazeik.databaseslib.databaseslib1 E/tag: total=8147126current=6227543pencent76%item.hashCode()437674568
10-18 12:03:59.518 28394-28394/com.kazeik.databaseslib.databaseslib1 E/tag: total=8147126current=6342231pencent77%item.hashCode()437674568
10-18 12:03:59.818 28394-28394/com.kazeik.databaseslib.databaseslib1 E/tag: total=8147126current=6391383pencent78%item.hashCode()437674568
10-18 12:04:00.195 28394-28394/com.kazeik.databaseslib.databaseslib1 E/tag: total=8147126current=6456919pencent79%item.hashCode()437674568

**Comment by wyouflf** [comment]
已优化，更新版本试试
