### ISSUE TITLE
关于post的一个问题？

### ISSUE THREAD

**Issue by yangqi1993** [wyouflf/xUtils3#435]
使用时，post请求一个服务器地址得到json，这个地址是移植pc端的，成功后会在pc上有一个弹窗，但是手机端访问应该只返回json，但是却在onError中返回了一个404 not found，postman模拟请求也是正常，一到真机就出这个问题，换okhttp就好了，不知道是不是pc弹窗引起的

**Comment by yangqi1993** [comment]
作者或者知道麻烦回答下咯，服务器端逻辑可能是接口返回成功后调了一个function方法，所以导致这边404？

**Comment by wyouflf** [comment]
贴出浏览器开发者模式下执行的请求和返回信息
