### ISSUE TITLE
setConnectTimeout第一次请求失效问题。

### ISSUE THREAD

**Issue by KT848802460** [wyouflf/xUtils3#437]
RequestParams params = new RequestParams(url);
params.setConnectTimeout(5000);
params.setMaxRetryCount(0);
params.setPriority(Priority.UI_TOP);
x.http().post(params, callback);
setConnectTimeout为什么第一次请求还是默认的，等了30秒左右才响应失败，后面的都是5秒响应失败

**Comment by wyouflf** [comment]
有一个默认retryCount=2， 设置为0试试
