### ISSUE TITLE
4.0.3的机器请求网络时报错

### ISSUE THREAD

**Issue by LeonJavaAndroid** [wyouflf/xUtils3#44]
Could not find method java.net.HttpURLConnection.setFixedLengthStreamingMode, referenced from method org.xutils.http.request.HttpRequest.sendRequest

VFY: unable to resolve virtual method 35050: Ljava/net/HttpURLConnection;.setFixedLengthStreamingMode (J)V

VFY: replacing opcode 0x6e at 0x0219

Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1)

然后app就挂掉了，但是却没有任何其他的错误输出，app闪退时也不弹窗提示“很抱歉，xx已停止运行”，反正app界面就突然消失了

**Comment by wyouflf** [comment]
最新的策略:

                        if (contentLength < Integer.MAX_VALUE) {
                            connection.setFixedLengthStreamingMode((int) contentLength);
                        } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
                            connection.setFixedLengthStreamingMode(contentLength);
                        } else {
                            connection.setChunkedStreamingMode(256 * 1024);
                        }

如果还有问题就是rom的问题, (setFixedLengthStreamingMode (J)V, 参数J对应java里的long)

**Comment by Jeffery336699** [comment]
请问大神contentLength 和 connection分别是从哪里获得的?
`private void downFromServer() {
        if (Environment.MEDIA_MOUNTED.equals(Environment.getExternalStorageState())){
            String savePath= getFilesDir().getPath()+"/updata.apk";
            Log.i(TAG, "downFromServer: ---savePath:"+savePath);
            //设置请求参数
            RequestParams params = new RequestParams(downloadUrl);
            params.setAutoResume(true);//设置是否在下载是自动断点续传
            params.setAutoRename(false);//设置是否根据头信息自动命名文件
            params.setSaveFilePath("savePath");
            params.setExecutor(new PriorityExecutor(2, true));//自定义线程池,有效的值范围[1, 3], 设置为3时, 可能阻塞图片加载.
            params.setCancelFast(true);//是否可以被立即停止.
            //下面的回调都是在主线程中运行的,这里设置的带进度的回调
            
            cancelable = x.http().get(params, new Callback.ProgressCallback<File>() {
                @Override
                public void onCancelled(CancelledException arg0) {
                    Log.i("tag", "取消"+Thread.currentThread().getName());
                }

                @Override
                public void onError(Throwable arg0, boolean arg1) {
                    Log.i("tag", "onError: 失败"+Thread.currentThread().getName());
                    progressDialog.dismiss();
                }

                @Override
                public void onFinished() {
                    Log.i("tag", "完成,每次取消下载也会执行该方法"+Thread.currentThread().getName());
                    progressDialog.dismiss();
                }

                @Override
                public void onSuccess(File arg0) {
                    Log.i("tag", "下载成功的时候执行"+Thread.currentThread().getName());
                }

                @Override
                public void onLoading(long total, long current, boolean isDownloading) {
                    if (isDownloading) {
                        //                    progressDialog.setProgress((int) (current*100/total));
                        progressDialog.setProgress((int) (current*100/total));
                        Log.i("tag", "下载中,会不断的进行回调:"+Thread.currentThread().getName());
                    }
                }

                @Override
                public void onStarted() {
                    Log.i("tag", "开始下载的时候执行"+Thread.currentThread().getName());
                    progressDialog.show();
                }

                @Override
                public void onWaiting() {
                    Log.i("tag", "等待,在onStarted方法之前执行"+Thread.currentThread().getName());
                }

            });
        }else {
            Toast.makeText(this, "没有sd卡", Toast.LENGTH_SHORT).show();
        }

    }`

报错:Could not find method java.net.HttpURLConnection.setFixedLengthStreamingMode, referenced from method org.xutils.http.request.HttpRequest.sendRequest

![image](https://cloud.githubusercontent.com/assets/16848549/23698284/f93a9984-0425-11e7-8bea-eb8b69f97033.png)请问大神哪里出错了
