### ISSUE TITLE
Post请求提交问题

### ISSUE THREAD

**Issue by yanquanyu** [wyouflf/xUtils3#444]
RequestParams params = new RequestParams( url);
之后在params里面调用addBodyParameter方法添加数据，调用x.http().post()方法之前，如果打印了一次params，System.out.println(params)，这个时候会调用BaseParams类的checkBodyParams方法，导致method属性没有设置，这个时候会导致调用
`if (!HttpMethod.permitsRequestBody(method)
                || !TextUtils.isEmpty(bodyContent)
                || requestBody != null) {
            queryStringParams.addAll(bodyParams);
            bodyParams.clear();
        }`
所有post的内容实际是通过get方式的url上传的。

**Comment by ArenasPan** [comment]
尝试注释掉bodyParams.clear(); 这一行就可以调试打印，但是请求参数仍会拼到url后面，不知道会不会出现其他的问题

**Comment by wyouflf** [comment]
谢谢反馈，已修复，更新最新版本
