### ISSUE TITLE
继承基类的x.view().inject(this)无效

### ISSUE THREAD

**Issue by ypf168326** [wyouflf/xUtils3#449]
在基类中实现了x.view().inject(this)，在子类中无法动态加载布局，目前我的做法是把这行代码放入到每一个具体的子类oncreate()方法中了，也不知道是什么原因导致的？

**Comment by xionghf** [comment]
猜测应该是你代码的问题，x.view().inject(this)必须在setContentView()之后执行，实现的话，有两种方式：
1、在子Activity上使用@ContentView(R.layout.xxx)注解，在基类的onCreate中调用x.view().inject(this)
2、基类中声明int getLayoutResId()抽象方法，子类中实现，并返回布局资源ID，基类的的onCreate()中
```
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(getLayoutResId());
    x.view().inject(this);
}
```
一般用第一种就够了

**Comment by ypf168326** [comment]
之前用的是org.xutils:xutils:3.3.36的版本，现在升级到org.xutils:xutils:3.3.38的版本就好了，代码都没改过，我用的就是第一种方式。

**Comment by wyouflf** [comment]
基类里使用请放在super.onCreate之前， 这样才能保证子类onCreate之后view注入立即可用。
