### ISSUE TITLE
每次请求网络结束后，UI都会卡顿

### ISSUE THREAD

**Issue by LeonJavaAndroid** [wyouflf/xUtils3#45]
I/Choreographer: Skipped 42 frames!  The application may be doing too much work on its main thread.

列表中上拉加载更多时，更是卡得不行，这次使用的机器是nexus4，5.1.1的系统，3.1.8版本

**Comment by LeonJavaAndroid** [comment]
确定是升级了xutils3导致的，使用2.6版本时没问题，加载时不请求网络，直接加载固定数据不卡，请求网络也快，但是问题就出在请求结束后

**Comment by wyouflf** [comment]
更新到 最新版试试

**Comment by LeonJavaAndroid** [comment]
3.1.9了，问题依旧

**Comment by wyouflf** [comment]
能看看你的处理代码吗

**Comment by LeonJavaAndroid** [comment]
运行你的demo也可以看到，HTTP Fragment，点击Test Baidu 1，点击后马上向右滑动页面，可以看到卡顿，同时as里输出，"org.xutils.sample I/Choreographer: Skipped xx frames!The application..."

**Comment by wyouflf** [comment]
系统toast的动画丢帧很正常, 内容太多了.
