### ISSUE TITLE
列表上传！

### ISSUE THREAD

**Issue by marren06** [wyouflf/xUtils3#451]
请问下，我看咱们demo里面有多线程下载功能，以列表的形式展示，而且变下边存贮，非常棒！
我的问题是 能不能仿照您的下载功能  做一个上传呢?  多线程上传 以列表的形式展示！ 

我花好长时间改了 最后总是更新不了UI，总报错：
 java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131558630, class android.widget.ListView) with Adapter

求大神指点迷津！！！

**Comment by wyouflf** [comment]
在demo的基础上改吧😓
