### ISSUE TITLE
上传文件报java.net.ProtocolException: expected 51810 bytes but received 65536"

### ISSUE THREAD

**Issue by lferic** [wyouflf/xUtils3#452]
上传文件报java.net.ProtocolException: expected 51810 bytes but received 65536"
出错率相当高！把  connection.setRequestProperty("Content-Length", String.valueOf(contentLength));这一句去掉就不报这个错了，但是我想知道去掉这个会不会出现其它的问题。请指教！谢谢。。

**Comment by wyouflf** [comment]
更新下新版本试试
