### ISSUE TITLE
xutils3当url为内网（192.168.1.XX）时，不能下载文件。

### ISSUE THREAD

**Issue by HRobbie** [wyouflf/xUtils3#455]
private static final String BASE_PATH = Environment.getExternalStorageDirectory().getPath() + File.separator;
    private String path=BASE_PATH+"recordNote"+"/recodenote_release.apk";

RequestParams requestParams = new RequestParams("http://192.168.1.80:8080/download/recodenote_release.apk");
        requestParams.setAutoRename(true);//断点下载
        requestParams.setSaveFilePath(path);
        x.http().get(requestParams, new Callback.ProgressCallback<File>() {
            @Override
            public void onWaiting() {

            }

            @Override
            public void onStarted() {
            }

            @Override
            public void onLoading(long total, long current, boolean isDownloading) {
                builder.setContentTitle("正在下载"+(int)((double)current/total*100)+"%").setProgress((int)total,(int)current,false);
               send();

            }

            @Override
            public void onSuccess(File result) {
                builder.setContentTitle("下载完成100%").setProgress(100, 100, false);
                send();
                openFile(result);
            }

            @Override
            public void onError(Throwable ex, boolean isOnCallback) {
                CommentUtils.showToast(DownLoadService.this,"下载失败，请检查网络和SD卡");
            }

            @Override
            public void onCancelled(CancelledException cex) {
            }

            @Override
            public void onFinished() {
            }
        });
当url为http://192.168.1.80:8080/download/recodenote_release.apk时，不能下载，这个url没有问题，可以在浏览器上下载成功。这段代码也没有问题,把url换成域名的url就能下载了。

**Comment by q232916067** [comment]
你用的是模拟器吗?192.168.1.80好像会指向模拟器本地.

**Comment by HRobbie** [comment]
不要意思，这个url有问题。跟模拟器没有关系。
