### ISSUE TITLE
 open failed: EROFS (Read-only file system)

### ISSUE THREAD

**Issue by haijiaoqiufeng** [wyouflf/xUtils3#456]
`11-29 10:48:12.434: W/x_log:HttpRetryHandler.canRetry(L:54)(2990): open failed: EROFS (Read-only file system)
11-29 10:48:12.434: W/x_log:HttpRetryHandler.canRetry(L:54)(2990): java.io.IOException: open failed: EROFS (Read-only file system)
11-29 10:48:12.434: W/x_log:HttpRetryHandler.canRetry(L:54)(2990): 	at java.io.File.createNewFile(File.java:939)
11-29 10:48:12.434: W/x_log:HttpRetryHandler.canRetry(L:54)(2990): 	at org.xutils.http.loader.FileLoader.load(FileLoader.java:82)
11-29 10:48:12.434: W/x_log:HttpRetryHandler.canRetry(L:54)(2990): 	at org.xutils.http.loader.FileLoader.load(FileLoader.java:239)
11-29 10:48:12.434: W/x_log:HttpRetryHandler.canRetry(L:54)(2990): 	at org.xutils.http.loader.FileLoader.load(FileLoader.java:1)
11-29 10:48:12.434: W/x_log:HttpRetryHandler.canRetry(L:54)(2990): 	at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:82)
11-29 10:48:12.434: W/x_log:HttpRetryHandler.canRetry(L:54)(2990): 	at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:277)
11-29 10:48:12.434: W/x_log:HttpRetryHandler.canRetry(L:54)(2990): 	at org.xutils.http.HttpTask$RequestWorker.request(HttpTask.java:600)
11-29 10:48:12.434: W/x_log:HttpRetryHandler.canRetry(L:54)(2990): 	at org.xutils.http.HttpTask.doBackground(HttpTask.java:305)
11-29 10:48:12.434: W/x_log:HttpRetryHandler.canRetry(L:54)(2990): 	at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
11-29 10:48:12.434: W/x_log:HttpRetryHandler.canRetry(L:54)(2990): 	at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21)
11-29 10:48:12.434: W/x_log:HttpRetryHandler.canRetry(L:54)(2990): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-29 10:48:12.434: W/x_log:HttpRetryHandler.canRetry(L:54)(2990): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-29 10:48:12.434: W/x_log:HttpRetryHandler.canRetry(L:54)(2990): 	at java.lang.Thread.run(Thread.java:818)
11-29 10:48:12.434: W/x_log:HttpRetryHandler.canRetry(L:54)(2990): Caused by: android.system.ErrnoException: open failed: EROFS (Read-only file system)
11-29 10:48:12.434: W/x_log:HttpRetryHandler.canRetry(L:54)(2990): 	at libcore.io.Posix.open(Native Method)
11-29 10:48:12.434: W/x_log:HttpRetryHandler.canRetry(L:54)(2990): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
11-29 10:48:12.434: W/x_log:HttpRetryHandler.canRetry(L:54)(2990): 	at java.io.File.createNewFile(File.java:932)
11-29 10:48:12.434: W/x_log:HttpRetryHandler.canRetry(L:54)(2990): 	... 12 more
`

**Comment by wyouflf** [comment]
指定的文件保存路径不可用
