### ISSUE TITLE
(请重视并尽快更新！) HostnameVerifier 不安全的问题

### ISSUE THREAD

**Issue by harinlin** [wyouflf/xUtils3#460]
HostnameVerifier 不安全的问题，已经被google play列为规范！！！
具体规范链接：
https://support.google.com/faqs/answer/7188426
具体内容：
## **从 2017 年 3 月 1 日起，只要新应用或应用更新采用的 HostnameVerifier 的实施方式不安全，一律禁止在 Google Play 发布。您已发布的 APK 版本不会受到影响，但是，如果不解决此漏洞，您将无法为应用发布任何更新。**

项目里的具体代码：
x.java
`        static {
            TaskControllerImpl.registerInstance();
            // 默认信任所有https域名
            HttpsURLConnection.setDefaultHostnameVerifier(new HostnameVerifier() {
                @Override
                public boolean verify(String hostname, SSLSession session) {
                    return true;
                }
            });
        }`

**Comment by RuffianZhong** [comment]
强烈+1。。。。。
在线等回应

**Comment by reaper12** [comment]
setDefaultHostnameVerifier不是可以自己去设置吗？HttpsURLConnection.setDefaultHostnameVerifier是个静态方法啊

**Comment by harinlin** [comment]
@reaper12 这是个解决方案，我已经是这样处理的，为了提醒，所以提个issue

**Comment by gaofeng7777** [comment]
@RuffianZhong 
请问你是怎么解决的，具体是怎么实现的？

**Comment by RuffianZhong** [comment]
@gaofeng7777 作者好像已经提交新的版本修复了此问题，你可以下载最新包使用看看能够解决问题，我也是刚刚看到作者更新，这就去使用最新包看看能不能解决问题

**Comment by RuffianZhong** [comment]
@gaofeng7777   看看 #465

**Comment by wyouflf** [comment]
fixed
