### ISSUE TITLE
调用Callback.Cancelable 的cancel方法有时候回调onerror有时候回调oncancel

### ISSUE THREAD

**Issue by 798146512** [wyouflf/xUtils3#461]
new Callback.CommonCallback<String>() {
            @Override
            public void onSuccess(String result) {
                
            }

            @Override
            public void onError(Throwable ex, boolean isOnCallback) {
               
            }

            @Override
            public void onCancelled(CancelledException cex) {
               
            }

            @Override
            public void onFinished() {

            }
        };

如标题所说，调用了cancle后有时候回调onError有时候回调onCancelled，不是应该都回调onCancelled的吗

**Comment by wyouflf** [comment]
打印下 onError得到的错误信息, 看看是不是onCancelled的实现代码有异常.
