### ISSUE TITLE
(请重视并尽快更新！) HostnameVerifier 不安全的问题

### ISSUE THREAD

**Issue by RuffianZhong** [wyouflf/xUtils3#463]
HostnameVerifier 不安全的问题，已经被google play列为规范！！！
具体规范链接：
https://support.google.com/faqs/answer/7188426
具体内容：

从 2017 年 3 月 1 日起，只要新应用或应用更新采用的 HostnameVerifier 的实施方式不安全，一律禁止在 Google Play 发布。您已发布的 APK 版本不会受到影响，但是，如果不解决此漏洞，您将无法为应用发布任何更新。

项目里的具体代码：
x.java
static { TaskControllerImpl.registerInstance(); // 默认信任所有https域名 HttpsURLConnection.setDefaultHostnameVerifier(new HostnameVerifier() { @Override public boolean verify(String hostname, SSLSession session) { return true; } }); }

再不修改我的项目就要下架了。或者我就要换框架了，，，多么痛的领悟

**Comment by reaper12** [comment]
setDefaultHostnameVerifier不是可以自己去设置吗？HttpsURLConnection.setDefaultHostnameVerifier是个静态方法啊,自己重新设置一下覆盖就可以了

**Comment by harinlin** [comment]
@RuffianZhong ，可以参考@reaper12的解决方案。 BTW，@RuffianZhong，你这是一点不变的搬的我的内容啊！！！虽然没有其他坏的影响，但这一个意识问题啊，得多多注意些，避免在其他方法吃亏啊

**Comment by RuffianZhong** [comment]
@reaper12 很抱歉，没有原创意识的直接复用您的ISSUES。
我直接通过直接覆盖那个静态方法返回false，造成了facebook登录出现问题，不过我看到作者已经更新了版本，试试看能不能解决问题。
