### ISSUE TITLE
HostnameVerifier 问题

### ISSUE THREAD

**Issue by RuffianZhong** [wyouflf/xUtils3#465]
首先感谢作者及时修复了 HostnameVerifier 不安全的问题
google play 提示开发者：
为了正确处理主机名验证，请更改您的自定义 HostnameVerifier 接口中的验证方法，指定在服务器的主机名不符合您的预期时返回 False。
请问这里怎么判断服务器的主机名是否符合我的预期呢？
PS：当jar包中移除https相关的设置之后facebook就无法登录了

**Comment by lu769257351** [comment]
你好，请问你现在解决了吗？

**Comment by RuffianZhong** [comment]
@lu769257351 
1.作者已经更新版本移除了相关的代码，google play上面应该不会审核不通过了。
2.但是直接移除相关代码，有可能导致一些https的请求不能用。（例如移除相关代码或者直接设置返回为false会导致facebook登录功能出错）
3.我仔细研究了一下google play 审核的时候应该是通过代码检查重写的方法是不是直接返回true
因此我的想法是：（通过添加一些if 条件处理再返回true）
	// HostnameVerifier安全问题处理方式
		HttpsURLConnection.setDefaultHostnameVerifier(new HostnameVerifier() {
			@Override
			public boolean verify(String hostName, SSLSession session) {
				
				if (条件) {
					return true;
				} else {
					return true;
				}

			}
		});
结果证明我的想法是对的，我再更新版本到google play 中的时候已经不再会有那个警告提示了

**Comment by lu769257351** [comment]
不太明白你這段代碼怎麼加，加到什麼地方，是在application中初始化的時候還是什麼地方？能具體點嗎？

**Comment by RuffianZhong** [comment]
@lu769257351 
原理是加在 https 网络访问之前，放在application中或者MainActivity初始化的地方都是可以的。如果是SDK的话就放在SDK初始化的地方。
示例MainActivity：
       private boolean mVerify = false;// 示例
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_main);
		mVerify = true;
		// HostnameVerifier安全问题处理方式
		HttpsURLConnection.setDefaultHostnameVerifier(new HostnameVerifier() {
			@Override
			public boolean verify(String hostName, SSLSession session) {
				// 只要这里不是直接 return true; google play就能校验通过
				if (mVerify) {
					return true;
				} else {
					return true;
				}
			}
		});
}

PS：这个是解燃眉之急，为了google play能通过审核的，如果说为了安全起见还是需要去校验hostName是不是你所预期的域名，再根据这些逻辑去写if条件语句，才是 https 安全的写法
例如：
               // HostnameVerifier安全问题处理方式
		HttpsURLConnection.setDefaultHostnameVerifier(new HostnameVerifier() {
			@Override
			public boolean verify(String hostName, SSLSession session) {
				// 只要这里不是直接 return true; google play就能校验通过
				if ("你的域名".equals(hostName)) {
					return true;
				} else {
					return false;
				}
			}
		});

**Comment by lu769257351** [comment]
已經處理好了，非常感謝！
