### ISSUE TITLE
Android Studio Library Module中注解不可用？

### ISSUE THREAD

**Issue by antonyw** [wyouflf/xUtils3#470]
R.layout.xx找不到？
有没有人知道怎么解决

**Comment by jiawei-i** [comment]
1）Activity的注解的使用如下：

@ContentView(R.layout.activity_main)
public class MainActivity extends AppCompatActivity {
    @ViewInject(R.id.viewpager)
    ViewPager viewPager;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        x.view().inject(this);
        ...
    }
}

2）Fragment的注解的使用如下：

@ContentView(R.layout.fragment_http)
public class HttpFragment extends Fragment {
    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        return x.view().inject(this, inflater, container);
    }
    @Override
    public void onViewCreated(View v, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(v, savedInstanceState);
    }
}

**Comment by antonyw** [comment]
@jiawei-i 朋友，不是这个原因，是R文件中的属性不是final类型，所以引用不到

**Comment by luxiao0314** [comment]
@antonyw解决了吗盆友

**Comment by antonyw** [comment]
@luxiao0314 不知道有没有更新，我发提问的那个版本是不可用的，要么换注解库要么就不用

**Comment by yangfeng1994** [comment]
同样，如果用ButterKnife 的话，可以用R2

**Comment by wyouflf** [comment]
是不是final没有关系 @antonyw , 检查下是否混淆的问题
