### ISSUE TITLE
 android.database.sqlite.SQLiteDatabaseLockedException: database is locked 

### ISSUE THREAD

**Issue by WuShengXi** [wyouflf/xUtils3#472]
可以参考
http://www.cnblogs.com/xienb/p/3455562.html
并发数高的时候容易出这个问题

##############
by wyouflf:
这个参考中SQLiteConn.Open()未加锁很危险, 如果是高并发, 数据较多时, 这样的操作对性能影响很大.

**Comment by wyouflf** [comment]
如果有高并发操作,参考示例代码, 使用: db.getDatabase().enableWriteAheadLogging();
