### ISSUE TITLE
bug：https请求  带“_”的 异常 java.net.UnknownHostException 类似地址https://appsvcv0_qiye/...

### ISSUE THREAD

**Issue by bayshier** [wyouflf/xUtils3#473]
java.net.UnknownHostException: host == null host == null false host == null

**Comment by bayshier** [comment]
https 下请求带“_”的 java.net.UnknownHostException: host == null host == null false host == null

**Comment by wyouflf** [comment]
域名中不应出现下划线, 这样是不规范的.
