### ISSUE TITLE
在需要验证身份的网络情况下 例如上海花生地铁wifi  未验证状态直接下载文件时

### ISSUE THREAD

**Issue by hazyrain** [wyouflf/xUtils3#477]
如题 会直接下载花生地铁wifi的错误网络html信息。。。 
能否在外部进行 手动设置 网络请求成功的状态码？

**Comment by wyouflf** [comment]
让用户检查网络状态或跳去设置网络, 这个应该有app来实现, xUtils仅处理网络访问流程.
