### ISSUE TITLE
有个BUG

### ISSUE THREAD

**Issue by zqil** [wyouflf/xUtils3#478]
`    private boolean validView4Callback(boolean forceValidAsyncDrawable) {
        final ImageView view = viewRef.get();
        if (view != null) {
            Drawable otherDrawable = view.getDrawable();
            if (otherDrawable instanceof AsyncDrawable) {
                ImageLoader otherLoader = ((AsyncDrawable) otherDrawable).getImageLoader();
                if (otherLoader != null) {
                    if (otherLoader == this) {
                        if (view.getVisibility() != View.VISIBLE) {
                            otherLoader.cancel();
                            return false;
                        } else {
                            return true;
                        }`

当ImageView的visibility不是View.VISIBLE时，x.image.bind()会取消下载图片，显然这种设计是不够准确的，

**Comment by wyouflf** [comment]
谢谢反馈, 已优化这个问题
