### ISSUE TITLE
15s没有请求到数据，会重新发送请求。

### ISSUE THREAD

**Issue by HRobbie** [wyouflf/xUtils3#479]
RequestParams params=new RequestParams(url);
params.setConnectTimeout(60000);
params.setMaxRetryCount(0);//如果只发送一次请求，一定要加上超时时间，否者还是会重复请求

**Comment by wyouflf** [comment]
只有GET请求才会Retry

**Comment by hxkdidi** [comment]
post请求设置请重试次数无效的咯，经常出现socketTimeOut怎么处理呢

**Comment by wyouflf** [comment]
@hxkdidi 提示用户重试, 或者自动重试一次, 可以定义自己的retryhandler, 默认只有get请求会重试

**Comment by hxkdidi** [comment]
谢谢大佬提点哦😄------------------ 原始邮件 ------------------
发件人: "wyouflf"<notifications@github.com>
发送时间: 2019年9月9日(星期一) 中午1:51
收件人: "wyouflf/xUtils3"<xUtils3@noreply.github.com>;
抄送: "hxkdyw"<2281019686@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [wyouflf/xUtils3] 15s没有请求到数据，会重新发送请求。 (#479)



@hxkdidi 提示用户重试, 或者自动重试一次, 可以定义自己的retryhandler, 默认只有get请求会重试
 
&mdash;
