### ISSUE TITLE
android 6.0 下载功能无法使用

### ISSUE THREAD

**Issue by Next123** [wyouflf/xUtils3#480]
在android 5.1上面可以正常下载 ，6.0 无法执行onLoading( ) 方法

**Comment by sweet2o09** [comment]
我也没执行onLoading()你是怎么解决的?

**Comment by Next123** [comment]
Android 6.0 需要运行时权限

**Comment by sweet2o09** [comment]
什么权限,我权限貌似都有开启

**Comment by Next123** [comment]
Android 6.0之后 都需要动态获取权限之后才能使用，单纯的在清单文件声明是不行的

**Comment by sweet2o09** [comment]
我是有设置权限啊
add(Manifest.permission.INTERNET);
            add(Manifest.permission.READ_EXTERNAL_STORAGE);
            add(Manifest.permission.WRITE_EXTERNAL_STORAGE);
            add(Manifest.permission.ACCESS_NETWORK_STATE);
            add(Manifest.permission.CHANGE_NETWORK_STATE);
这几个权限应该够的吧
请问你是用3.5.0版本么

**Comment by Next123** [comment]
http://www.jianshu.com/p/dbe4d37731e6
