### ISSUE TITLE
如何使用gzip

### ISSUE THREAD

**Issue by daidaideha** [wyouflf/xUtils3#482]
如何让请求使用gzip压缩 返回后解压

**Comment by wyouflf** [comment]
默认支持

**Comment by SessionToGitHub** [comment]
你好，我想问下，如果返回的是application/gzip的，如何获取，或者说如何获取响应的消息头

**Comment by wyouflf** [comment]
不需要自己处理URLconnection自动带gzip头，和gzip流的转换
