### ISSUE TITLE
OnTouch事件怎么处理

### ISSUE THREAD

**Issue by liupeng110** [wyouflf/xUtils3#485]
@Event(value = R.id.btn_test_baidu1,
        type = View.OnTouchListener.class)
private void onTestBaidu1Click(View view) { 
....
}
或者 
private void onTestBaidu1Click(View view,Motion motion) { 
....
}
或者 
private void onTestBaidu1Click(Motion motion) { 
....
}

都不行,具体要怎么用有知道的么.......

**Comment by liupeng110** [comment]
要拿到event事件

**Comment by liupeng110** [comment]
跟onClick可以共用么,我的需求是在代码里动态更改按钮背景
想用onTouchListener处理触摸事件,onClick处理按钮事件  .这两个会有冲突 
手写的OnTouchListener事件  xutils注解的onClick  导致OnTouch事件无法响应

**Comment by wyouflf** [comment]
看OnTouchListener的定义, 然后修改函数的返回值类型和参数类型.

**Comment by liupeng110** [comment]
boolea类型     那怎么拿到event呢？

**Comment by liupeng110** [comment]
xutils里不知道怎么写了，demo里没有呀

**Comment by liupeng110** [comment]
哦，原来是 返回值类型问题
