### ISSUE TITLE
保存数据时报错System.err: org.xutils.ex.DbException: <init> []

### ISSUE THREAD

**Issue by brook19** [wyouflf/xUtils3#487]
System.err: org.xutils.ex.DbException: <init> []
W/System.err:     at org.xutils.db.table.DbBase.getTable(DbBase.java:32)

**Comment by chjxidian** [comment]
我也遇到这个问题，请问你是怎么解决的？？？

**Comment by brook19** [comment]
你肯定是表实体类实现了有参构造函数，必须要实现一个默认构造函数

**Comment by chjxidian** [comment]
好像是的, 我是自己定义了构造函数，后来去掉了，搞定了，多谢！
