### ISSUE TITLE
同一个URL图片缓存，不同页面做不同样式的显示的问题

### ISSUE THREAD

**Issue by Dean1990** [wyouflf/xUtils3#488]
同一个URL图片缓存，不同页面做不同样式的显示，当返回前页面时，前页面该图样式发生变化，变成后打开页面的样式。
例如，A页面gridview的item是一个网络加载图片，占二分之一屏幕大小，然后从A跳转到B页面，B页面同样是该图片，显示大小是三分之一屏幕大小，当从B页面返回A页面时，A页面的该图大小变成了三分之一屏幕大小。 @wyouflf

**Comment by Dean1990** [comment]
当不使用ImageOption控制图片时，不存在以上问题 ；ImageOption是new出来的，并没有使用同一个。

**Comment by wyouflf** [comment]
ImageOption里指定大小就可以了
