### ISSUE TITLE
关于多次调用 x.view().inject 的问题

### ISSUE THREAD

**Issue by houfukude** [wyouflf/xUtils3#489]
出错的源码如下
```
@ContentView(R.layout.main)
public class Main extends Activity {

    @ViewInject(R.id.listView)
    ListView listView;
    @ViewInject(value = R.id.textView,parentId = R.id.listView)
    TextView textView;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        x.view().inject(this);  //Error Line
        View headerView = LayoutInflater.from(this).inflate(R.layout.header, null);
        x.view().inject(this, headerView);  //Error Line
        listView.addHeaderView(headerView);
    }
}
```
程序执行的过程种有几率出现崩溃现象

> 02-18 01:01:59.122 15399-15399/? E/x_log:ViewInjectorImpl.injectObject(L:170): Invalid @ViewInject for Main.listView
                                                                               java.lang.RuntimeException: Invalid @ViewInject for Main.listView

> 02-18 01:01:59.140 15399-15399/? E/x_log:ViewInjectorImpl.injectObject(L:170): Invalid @ViewInject for Main.textView
                                                                               java.lang.RuntimeException: Invalid @ViewInject for Main.textView

这种情况应该怎么处理呢？
还是说一次onCreate只能执行一次注入？

**Comment by houfukude** [comment]
Update 貌似不会导致程序崩溃

~~崩溃是我本机的黑域杀进程 Orz~~

**Comment by liupeng110** [comment]
生命周期的问题导致的,demo是继承一个BaseActivity   在BaseActivity中x.view().inject
