### ISSUE TITLE
百度地图不能用

### ISSUE THREAD

**Issue by jimdaxu** [wyouflf/xUtils3#49]
为什么用了xutil3之后，百度地图在有的机子上运行不了啊，百度地图初始化就报错，我的机子是5.0系统的，在4.X系统的机子没有问题。

**Comment by jimdaxu** [comment]
我吧xutil框架去掉之后，5.0的机子的百度地图也可以正常打开

**Comment by jinzw1993** [comment]
我测试了一下没事，地图版本3.6.1,先导入xutils 之后初始化。在导入百度地图。androidstudio

**Comment by jimdaxu** [comment]
我之前初始化顺序也是这样的，也是Androidstudio，也是3.6.1。但不行。现在把百度地图的so文件复制到不同cpu目录下，解决了，不过就是apk文件很大。

**Comment by jinsen1** [comment]
包冲突了

**Comment by jimdaxu** [comment]
除了复制so文件之外，包冲突要怎么解决啊，

**Comment by wyouflf** [comment]
什么包冲突

**Comment by jimdaxu** [comment]
不知道啊，上面jinsen1回复的包冲突 ，我也不知道什么包冲突

**Comment by kimver** [comment]
我的解决方法是这样的，解压aar包里面的jar包，单独导入就可以了，好像高德地图也会起冲突
