### ISSUE TITLE
loaddrawable方法返回的drawable的getIntrinsicWidth()获取的宽度究竟与设备的什么有关？

### ISSUE THREAD

**Issue by MarsToken** [wyouflf/xUtils3#490]
我在不同的手机上测试发现：同一个url：hdpi手机(设备密度是1.5)和夜神模拟器(设备密度是1.5625)，此方法获取的drawable.getIntrinsicWidth()数值有的一样，有的是不一样的，比如这个url是不一样的（亲测：https://test.dfs.fe520.com/group1/M00/94/93/ChIBB1gz8kaASHLVAABeGkxilJQ419.jpg）前者是627px,后者是1254px；
大部分都一样，一样的就不给例子了。
我想知道获取的drawable究竟与设配的什么参数有关系？？

**Comment by MarsToken** [comment]
https://test.dfs.fe520.com/group1/M00/94/93/ChIBB1gz8kaAUHXvAABLkD9H2YU571.jpg
这个url，两个设备获取的都是1336px

**Comment by MarsToken** [comment]
求救！！！

**Comment by wyouflf** [comment]
loadDrawable需要ImageOptions指定大小.

**Comment by MarsToken** [comment]
你好，我的options里没有设置大小，那就是默认的。那我如何获取原图大小呢？

**Comment by MarsToken** [comment]
你好，我的options里没有设置大小，那就是默认的。那我如何获取原图大小呢？

**Comment by wyouflf** [comment]
设置选项里有一个不压缩加载原图的参数
