### ISSUE TITLE
tableid为空导致数据保存失败的问题

### ISSUE THREAD

**Issue by tanghongbin** [wyouflf/xUtils3#491]
楼主你好，使用过程发现如果在没有调用getTable(ChatMode.class).tableIsExist()方法判断是否已经存在的话，然后直接调用save或者saveorupdate方法，在保存数据的过程中创建的表是没有id的，后面一直会报NullPointException,这个地方希望优化一下

**Comment by wyouflf** [comment]
不太明白, 能详细描述下后面什么操作NullPointException, 或者给个示例代码.
