### ISSUE TITLE
是否支持application/x-www-form-urlencoded方式调用？

### ISSUE THREAD

**Issue by ypf168326** [wyouflf/xUtils3#492]
本人在postman调用接口测试成功（）

我用框架中默认的postAsync方法调用失败，我打印出来自己的请求参数

user_id=1553&createDate=1487666479&story_target=&storys=[{"content":"啦啦啦","img_url":"user/1553/image/20170221/14876665063341523.jpg"}]&loc={"add_desc":"","artcity":"杭州市","longitude":"120.19576263427734","add_tel":"","latitude":"30.20988655090332","add_cata":"","add_detail":"","add_name":"浙江省杭州市","add_alias":""}&story_tags=[{"tag_id":"19","tag_name":"美景"},{"tag_id":"20","tag_name":"书香"},{"tag_id":"42","tag_name":"时尚"}]&privace=1&title=啦啦啦&thumb=user/1553/image/20170221/14876665063341523.jpg&type=art_article

如果想指定application/x-www-form-urlencoded方式调用，要如何设置？该框架是否支持这些如下数据提交方式？（form-data,application/x-www-form-urlencoded,raw,binary）

目前框架支持请求参数当中包含数组和JSON数据吗？
最后附上请求代码：

RequestParams requestParams = new RequestParams(Constant.BASE_URL + "/poststory");
        requestParams.addParameter("user_id", mUserid);
        requestParams.addParameter("createDate",mCreateDate);
        requestParams.addParameter("story_target",mStoryTarget);
        requestParams.addParameter("storys",mStorys);
        requestParams.addParameter("loc",mLoc);
        requestParams.addParameter("story_tags",mStoryTags);
        requestParams.addParameter("privace",mPrivace);
        requestParams.addParameter("title",mTitle);
        requestParams.addParameter("thumb",mThumb);
        requestParams.addParameter("type",mType);
       x.http().post(requestParams, commonCallback);

**Comment by wyouflf** [comment]
都支持的, addParameter没有添加文件时默认就是"application/x-www-form-urlencoded",  添加了文件默认multipart/form-data, 这也是浏览器默认的方式. 添加文件并setMuitlpart(false)的话就是原始数据直接提交.

**Comment by ypf168326** [comment]
恩，知道了，我用默认的提交服务端数据解析不出来，服务端用的是PHP，我传输的数据厘米包涵json数组数据，PHP不能解析出来，不能正常把数据转成数组，目前用了okgo框架调用的，服务端可以直接解析。
wyouflf <notifications@github.com>于2017年2月26日 周日20:12写道：

**Comment by jianjue123** [comment]
this issues is sovle? 
I upFile 
RequestParams params = new RequestParams(upToServiceUri);
        params.setMultipart(true);
        params.addBodyParameter("file", new File(filePath));
        x.http().post(params, new Callback.CommonCallback<String>() {。。。。。。
but onError callBack "ex:errorCode:415,msg:unsupported media ype , result:"  why?
