### ISSUE TITLE
当我在Module与app中同时使用xUtils时,出现这个提示?

### ISSUE THREAD

**Issue by xiaodao1990** [wyouflf/xUtils3#493]
Could not change the database journal mode of '/data/data/com.tcl.gamecenter/databases/xUtils_http_cookie.db' from 'wal' to 'PERSIST' because the database is locked.  This usually means that there are other open connections to the database which prevents the database from enabling or disabling write-ahead logging mode.  Proceeding without changing the journal mode.

**Comment by wyouflf** [comment]
你的module可以以类似provided的方式加载xUtils吗?
