### ISSUE TITLE
使用ViewInject注解的View 有时为空

### ISSUE THREAD

**Issue by Dean1990** [wyouflf/xUtils3#496]
使用ViewInject注解的View 有时为空，报空指针异常，可能存在注解失败 @wyouflf

**Comment by xionghf** [comment]
赞同，建议支持@Nullable注解，具体参照butterknife

**Comment by ypf168326** [comment]
我也遇到此问题，百思不得其解，不知楼主如何解决的？

**Comment by Dean1990** [comment]
打算慢慢过渡到butterknife

**Comment by LuoGuoXin** [comment]
我也遇到了，咋办

**Comment by dontBB** [comment]
+1,我临时换回findViewById了....总是偶发性的空指针异常,不敢用了....打算有时间再换成butterknife

**Comment by sksweet** [comment]
昨天刚下，初学中，100%为null,不知道怎么回事呢，请大家分析帮一下？谢谢
1 eclipse放入3.5版本jar包
2 在application的oncreate里加 x.Ext.init(this);
3 在fragment文件头，放入@ContentView(R.layout.×××)
4 在对应控件头部放ViewInject(R.id.×××)
5 编译Ok，
6 安装启动，加载对应fragment,报这个xxx控件是空的

**Comment by ypf168326** [comment]
@dontBB 我现在全部改回原生用法了，现在的原则是能不用第三方库就不用，宁可自己繁琐点，也不想遇到一些奇葩问题，一时半会也找不到，解决不了。

**Comment by wyouflf** [comment]
更新试试, 自测没有复现, 如果Activity子类有用到, 放在super.onCreate之前
