### ISSUE TITLE
如何注解标题栏

### ISSUE THREAD

**Issue by iamZ2z** [wyouflf/xUtils3#497]
原来的标题栏，需要这样设置很麻烦
requestWindowFeature(Window.FEATURE_CUSTOM_TITLE);
getWindow().setFeatureInt(Window.FEATURE_CUSTOM_TITLE,
				R.layout.bar_title);
请问使用注解框架的话，应该怎样设置才能方便调用标题栏里面的组件

**Comment by wyouflf** [comment]
暂不支持，感谢反馈
