### ISSUE TITLE
请教一下这个空指针异常是怎么回事

### ISSUE THREAD

**Issue by Z-Beatles** [wyouflf/xUtils3#500]
RequestParams  params = new RequestParams (apkurl);
params.setAutoRename(true);// 断点下载
params.setSaveFilePath("/mnt/sdcard/");
x.http().get(params, new Callback.ProgressCallback<File>() {
···
｝

x.http().get(params, new Callback.ProgressCallback<File>() 执行到这里就报错了

03-02 01:17:02.908: E/AndroidRuntime(19165): FATAL EXCEPTION: main
03-02 01:17:02.908: E/AndroidRuntime(19165): Process: cn.waynechu.mobilesafe, PID: 19165
03-02 01:17:02.908: E/AndroidRuntime(19165): java.lang.NullPointerException: Attempt to invoke interface method 'org.xutils.common.task.AbsTask org.xutils.common.TaskController.start(org.xutils.common.task.AbsTask)' on a null object reference
03-02 01:17:02.908: E/AndroidRuntime(19165): 	at org.xutils.http.HttpManagerImpl.request(HttpManagerImpl.java:50)
03-02 01:17:02.908: E/AndroidRuntime(19165): 	at org.xutils.http.HttpManagerImpl.get(HttpManagerImpl.java:34)
03-02 01:17:02.908: E/AndroidRuntime(19165): 	at cn.waynechu.mobilesafe.chapter01.utils.VersionUpdateUtils.downloadNewApk(VersionUpdateUtils.java:179)
03-02 01:17:02.908: E/AndroidRuntime(19165): 	at cn.waynechu.mobilesafe.chapter01.utils.VersionUpdateUtils$2.onClick(VersionUpdateUtils.java:143)
03-02 01:17:02.908: E/AndroidRuntime(19165): 	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:162)
03-02 01:17:02.908: E/AndroidRuntime(19165): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-02 01:17:02.908: E/AndroidRuntime(19165): 	at android.os.Looper.loop(Looper.java:135)
03-02 01:17:02.908: E/AndroidRuntime(19165): 	at android.app.ActivityThread.main(ActivityThread.java:5475)
03-02 01:17:02.908: E/AndroidRuntime(19165): 	at java.lang.reflect.Method.invoke(Native Method)
03-02 01:17:02.908: E/AndroidRuntime(19165): 	at java.lang.reflect.Method.invoke(Method.java:372)
03-02 01:17:02.908: E/AndroidRuntime(19165): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:948)
03-02 01:17:02.908: E/AndroidRuntime(19165): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:743)

**Comment by panpan058** [comment]
初始化了没有,然后如果在自定义的Application中初始化记得注册Application,我的异常跟你一样

**Comment by Leechen2014** [comment]
确实是一个经常忽略的问题；
在AndroidManifest.xml里面的<application  android:name=".XX">没有指定自己的Application , 或者是在XXApplication 里面没有写x.Ext.init(this);

**Comment by xfdr0805** [comment]
我在Actyvity里初始化也碰到这种情况了,怎么解决呢 
x.view().inject(this);

**Comment by luffykou** [comment]
三步走：
1、在AndroidManifest.xml里面指定自己的xxxApplication ；
2、在xxxApplication中初始化x.Ext.init(this);
3、在需要注解的activity/fragment中初始化x.view().inject(this)。
