### ISSUE TITLE
多图片上传异常

### ISSUE THREAD

**Issue by HahalongGit** [wyouflf/xUtils3#502]
多图片上传异常
RequestParams requestParams = new RequestParams(uploadUrl);
        requestParams.setMultipart(true);
        for(String filePath:filePaths){
            requestParams.addBodyParameter("upload", new File(filePath),null);
        }
 x.http().post(requestParams, commonCallback);

使用以上代码上传多个图片，有异常，但是没有出来异常信息，求助！！！
还需要设置参数嘛？有知道的小伙伴求demo

**Comment by GreatRoader** [comment]
params.setReadTimeout(20000); 超时时间适当常长一点
