### ISSUE TITLE
下载更新异常

### ISSUE THREAD

**Issue by Jeffery336699** [wyouflf/xUtils3#504]
`private void downFromServer() {
        if (Environment.MEDIA_MOUNTED.equals(Environment.getExternalStorageState())){
            String savePath= getFilesDir().getPath()+"/updata.apk";
            Log.i(TAG, "downFromServer: ---savePath:"+savePath);
            //设置请求参数
            RequestParams params = new RequestParams(downloadUrl);
            params.setAutoResume(true);//设置是否在下载是自动断点续传
            params.setAutoRename(false);//设置是否根据头信息自动命名文件
            params.setSaveFilePath("savePath");
            params.setExecutor(new PriorityExecutor(2, true));//自定义线程池,有效的值范围[1, 3], 设置为3时, 可能阻塞图片加载.
            params.setCancelFast(true);//是否可以被立即停止.
            //下面的回调都是在主线程中运行的,这里设置的带进度的回调
            
            cancelable = x.http().get(params, new Callback.ProgressCallback<File>() {
                @Override
                public void onCancelled(CancelledException arg0) {
                    Log.i("tag", "取消"+Thread.currentThread().getName());
                }

                @Override
                public void onError(Throwable arg0, boolean arg1) {
                    Log.i("tag", "onError: 失败"+Thread.currentThread().getName());
                    progressDialog.dismiss();
                }

                @Override
                public void onFinished() {
                    Log.i("tag", "完成,每次取消下载也会执行该方法"+Thread.currentThread().getName());
                    progressDialog.dismiss();
                }

                @Override
                public void onSuccess(File arg0) {
                    Log.i("tag", "下载成功的时候执行"+Thread.currentThread().getName());
                }

                @Override
                public void onLoading(long total, long current, boolean isDownloading) {
                    if (isDownloading) {
                        //                    progressDialog.setProgress((int) (current*100/total));
                        progressDialog.setProgress((int) (current*100/total));
                        Log.i("tag", "下载中,会不断的进行回调:"+Thread.currentThread().getName());
                    }
                }

                @Override
                public void onStarted() {
                    Log.i("tag", "开始下载的时候执行"+Thread.currentThread().getName());
                    progressDialog.show();
                }

                @Override
                public void onWaiting() {
                    Log.i("tag", "等待,在onStarted方法之前执行"+Thread.currentThread().getName());
                }

            });
        }else {
            Toast.makeText(this, "没有sd卡", Toast.LENGTH_SHORT).show();
        }

    }`

error:Could not find method java.net.HttpURLConnection.setFixedLengthStreamingMode, referenced from method org.xutils.http.request.HttpRequest.sendRequest

![2017-03-08_173659](https://cloud.githubusercontent.com/assets/16848549/23698536/eca0aabe-0426-11e7-8cd3-d96f122e92aa.png)
请问大神这个下载应该如何解决?谢谢啦

**Comment by wyouflf** [comment]
尝试升级新版本
