### ISSUE TITLE
调用 db.update(info); 方法，提示如下错误，修改数据失败

### ISSUE THREAD

**Issue by 18672959660** [wyouflf/xUtils3#507]
org.xutils.ex.DbException: this entity[class com.caojing.websocketapp.entity.FriendDBInfo]'s id value is null
03-13 08:22:56.848 31988-31988/com.caojing.websocketapp W/System.err:     at org.xutils.db.sqlite.SqlInfoBuilder.buildUpdateSqlInfo(SqlInfoBuilder.java:184)
03-13 08:22:56.848 31988-31988/com.caojing.websocketapp W/System.err:     at org.xutils.db.DbManagerImpl.update(DbManagerImpl.java:300)
03-13 08:22:56.848 31988-31988/com.caojing.websocketapp W/System.err:     at com.caojing.websocketapp.db.MessageDB.svaeFriend(MessageDB.java:75)
03-13 08:22:56.848 31988-31988/com.caojing.websocketapp W/System.err:     at com.caojing.websocketapp.service.MyService$1.onTextMessage(MyService.java:114)
03-13 08:22:56.848 31988-31988/com.caojing.websocketapp W/System.err:     at de.tavendo.autobahn.WebSocketConnection$1.handleMessage(WebSocketConnection.java:312)
03-13 08:22:56.848 31988-31988/com.caojing.websocketapp W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
03-13 08:22:56.848 31988-31988/com.caojing.websocketapp W/System.err:     at android.os.Looper.loop(Looper.java:154)
03-13 08:22:56.848 31988-31988/com.caojing.websocketapp W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6077)
03-13 08:22:56.848 31988-31988/com.caojing.websocketapp W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-13 08:22:56.849 31988-31988/com.caojing.websocketapp W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
03-13 08:22:56.849 31988-31988/com.caojing.websocketapp W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by 18672959660** [comment]
可以插入成功 但是不能更新

**Comment by wyouflf** [comment]
update是根据id更新的, 使用saveBindingId之后会自动为对象id赋值, 
另外可以参考replace的用法, 见示例项目的代码.

**Comment by 18672959660** [comment]
已经ok了，非常感谢，先查出要修改数据的id,然后更具id来更新这条数据。
