### ISSUE TITLE
使用post请求，设置为json请求头形式没有用，一直报500的错误

### ISSUE THREAD

**Issue by anhuifix** [wyouflf/xUtils3#508]
String result = null;
        try {
            params.setCacheSize(0);
            params.setUseCookie(true);
            params.setConnectTimeout(20*1000);
            params.setAsJsonContent(true);
            Log.i("test", "postSync" + params.toString());
            result = x.http().postSync(params, String.class);
            return result;
        } catch (Throwable e) {
            e.printStackTrace();
        }
        return result;

**Comment by anhuifix** [comment]
请问作者这个是怎么回事，设置了setAsJsonContent(true);

**Comment by a404318964** [comment]
500是你们后台服务器出问题啊...

**Comment by anhuifix** [comment]
不是的，后来处理了
