### ISSUE TITLE
http 408错误

### ISSUE THREAD

**Issue by a546530845** [wyouflf/xUtils3#509]
发送http请求的时候会发生errorcode 408的情况，请问这是怎么回事

**Comment by wyouflf** [comment]
请求超时?

**Comment by a546530845** [comment]
是的，有时候会出现有时候不出现

**Comment by a546530845** [comment]
不是请求超时，是一点击请求的时候立马就返回了408

**Comment by wyouflf** [comment]
貌似服务端问题

**Comment by metaphor** [comment]
可能存在http connection 没有释放的情况（keep alive）导致服务器端发现（keep alive timeout）时主动返回408，然后释放链接
