### ISSUE TITLE
能否拆分成不同部分分别使用这个库？

### ISSUE THREAD

**Issue by boybeak** [wyouflf/xUtils3#512]
例如分拆成图片缓存，HTTP请求，View，数据库等多个库的形式，分别引用。

**Comment by TimeFisher** [comment]
就像Retrofit2分成converter，adapter，mock等，根据需要组合使用

**Comment by wyouflf** [comment]
总共249k, http(s)依赖db, 合起来200k. 其他view注入和图片合起来几十K.
