### ISSUE TITLE
xutils3 是否解决了android N 7.0 以上系统权限兼容性问题？

### ISSUE THREAD

**Issue by qydq** [wyouflf/xUtils3#513]
xutils3 是否解决了android N 7.0 以上系统权限兼容性问题，
使用xutils3 测试在android6.0以下系统使用数据库，也就是xutil3提供的db.getDbManger()会出现权限问题。

android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database

**Comment by wyouflf** [comment]
权限需要自己在Activity的代码中申请
