### ISSUE TITLE
上传文件,不指定content-type,文件名包含#,上传失败

### ISSUE THREAD

**Issue by liaolintao** [wyouflf/xUtils3#515]
报StringIndex越界异常
---------------------------------------
`
class FileBody{

    public static String getFileContentType(File file) {
        String filename = file.getName();
        String contentType = HttpURLConnection.guessContentTypeFromName(filename);
        if (TextUtils.isEmpty(contentType)) {
            contentType = "application/octet-stream";
        } else {
            contentType = contentType.replaceFirst("\\/jpg$", "/jpeg");
        }
        return contentType;
    }
}`
-------------------------------------------

**Comment by wyouflf** [comment]
HttpURLConnection.guessContentTypeFromName 这里?

**Comment by liaolintao** [comment]
是的

**Comment by wyouflf** [comment]
方便贴出报错信息吗

**Comment by liaolintao** [comment]
测试用例;

String fileName = "001#.jpg";
File file =  new File(fileName );
getFileContentType(file);

结果就是HttpURLConnection.guessContentTypeFromName报StringIndexOutOfRange异常,是HttpURLConnection抛出来的, 我查看了你的源码, 对name进行了编码,解析得到Content-type,解决了.
------------
我修改了你的源码
`    public static String getFileContentType(File file) {
        String filename = file.getName();
        String contentType = null;
        try {
          filename = Uri.encode(filename, "-![.:/,?&=]");
          contentType = HttpURLConnection.guessContentTypeFromName(filename);
        } catch (Exception e) {
          LogUtil.e(e.toString());
        }
        if (TextUtils.isEmpty(contentType)) {
            contentType = "application/octet-stream";
        } else {
            contentType = contentType.replaceFirst("\\/jpg$", "/jpeg");
        }
        return contentType;
    }`

**Comment by wyouflf** [comment]
感谢反馈, 已优化
