### ISSUE TITLE
在Android6.0上下载文件出现了open failed: EACCES (Permission denied)

### ISSUE THREAD

**Issue by fangfengfan** [wyouflf/xUtils3#519]
你好，在Android6.0上下载文件有一个异常java.io.FileNotFoundException: /storage/emulated/0/FFFChat/.tmp: open failed: EACCES (Permission denied)，在5.0上没问题。
代码：
 RequestParams params = new RequestParams(mVersionInfo.getUrl());
        params.setAutoRename(true);//断点下载
        File file = new File(F.t);
        if (!file.exists()) {
            file.mkdirs();
        }
        params.setSaveFilePath(F.t);
        x.http().get(params, new Callback.ProgressCallback<File>() {
// do something
}

F.t是Environment.getExternalStorageDirectory().toString() + File.separator + "FFFChat" + File.separator;

请问怎么解决？

**Comment by wyouflf** [comment]
6.0需要主动申请权限
