### ISSUE TITLE
我现在用xUtils3开始上传100张图片，但是还没上传完，然后我去请求100张，然后可以优先上传我后面这100张吗？

### ISSUE THREAD

**Issue by dreamlivemeng** [wyouflf/xUtils3#521]
我现在用xUtils3开始上传100张图片，但是还没上传完，然后我去请求100张，然后可以优先上传我后面这100张吗？

**Comment by wyouflf** [comment]
可以的params#setExecutor(...)自定义线程池, 或者使用xUtils里面的线程池, 
构造PriorityExecutor(int poolSize, boolean fifo), fifo = false就可以了.
