### ISSUE TITLE
关于sample代码中用Fastjson进行解析的一个问题

### ISSUE THREAD

**Issue by houfukude** [wyouflf/xUtils3#523]
https://github.com/wyouflf/xUtils3/blob/master/sample/src/main/java/org/xutils/sample/http/JsonResponseParser.java#L48
如果是 BaseResult<User> 这类带泛型的参数会解析失败
则应该改为:
` return JSON.parseObject(result, resultType);`

**Comment by wyouflf** [comment]
谢谢反馈, 已经修改
