### ISSUE TITLE
使用xUTils上传图失败，怎么处理

### ISSUE THREAD

**Issue by anhuifix** [wyouflf/xUtils3#524]
RequestParams params = new RequestParams(HttpUtils.URL_ROOT + HttpUtils.uploadUserImage);
            File iamgeFile = new File(file);
            Log.i("test","图片路劲"+file.toString()+"File"+iamgeFile.toString());
            params.addBodyParameter("mobile", AppConfig.getMobile());
            params.addBodyParameter("file",iamgeFile);
            params.addBodyParameter("type", TypeUtils.toString(type))

**Comment by wyouflf** [comment]
params.setMultipart(true)试试
