### ISSUE TITLE
请问下有没有计划，什么时候支持7.0？7.0中x.image()中的bind不能加载本地图片

### ISSUE THREAD

**Issue by galfordliu** [wyouflf/xUtils3#532]
从7.0开始，直接使用本地真实路径的Uri被认为是不安全的，会抛FileUriExposedException异常。只能使用FileProvider封装过的Uri来使用。x,image()中的bind不兼容此类型，没办法通过图片路径加载本地图片了。

**Comment by wyouflf** [comment]
明天更新
