### ISSUE TITLE
某些手机如下操作会导致从手机根目录开始删除

### ISSUE THREAD

**Issue by nideyoyo** [wyouflf/xUtils3#537]
如果这样写的话 
x.image().bind(imageView,"file://");  
在某些手机会触发从根目录开始删除文件夹  导致用户
手机类型
高通8953/8940平台的有问题
OPPO R9s、A57、、vivo X9、三星C7、红米note4x有此现象

![_5v3 mz2zdhu zp20_dkgno](https://cloud.githubusercontent.com/assets/8070044/25300876/e3533916-274b-11e7-85c2-6cf79d6d8a13.png)

**Comment by nideyoyo** [comment]
deleteFileOrDir希望做校验，不然会删除用户的所有信息

**Comment by wyouflf** [comment]
谢谢反馈, 明天更新.
