### ISSUE TITLE
关于https 双向认证 报错

### ISSUE THREAD

**Issue by weikao** [wyouflf/xUtils3#54]
我用 https 双向认证 javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb83067c0: Failure in SSL library, usually a protocol error 报这个错误。

url: 
RequestParams params = new RequestParams("https://xx.xx.xx.xx:8081/auth/login");

KEY File：key.p12（X509）
TRUST File：store.bks （X509）（BKS）
协议：TLS

同样的 SSLSocketFactory 用在HttpsURLConnection上没有问题。

params.setSslSocketFactory(sslSocketFactory); 不行报错
x.http().post(....)

**Comment by wyouflf** [comment]
更新至3.1.13

**Comment by weikao** [comment]
3.1.13还是报错

感觉 setSslSocketFactory 不起作用

但是 在 HttpRequest 类中

connection 只有 是 HttpsURLConnection 才会 setSSLSocketFactory

        if (connection instanceof HttpsURLConnection) {
            SSLSocketFactory sslSocketFactory = params.getSslSocketFactory();
            if (sslSocketFactory != null) {
                ((HttpsURLConnection) connection).setSSLSocketFactory(sslSocketFactory);
            }
        }

**Comment by yang-mr** [comment]
解决了吗？
