### ISSUE TITLE
代码混淆导致http调用失败

### ISSUE THREAD

**Issue by ypf168326** [wyouflf/xUtils3#540]
按照sample项目中的混淆配置文件进行代码混淆，导致网络调用请求直接失败，希望楼主尽早解决这个问题。

**Comment by jackdengchuangliang** [comment]
同问,按照sample项目中的混淆配置文件进行代码混淆，混淆后不能网络请求!

**Comment by wyouflf** [comment]
发错误信息出来, 检测混淆配置
