### ISSUE TITLE
关于@Event事件绑定和系统时间修改冲突的问题。很奇怪！

### ISSUE THREAD

**Issue by imyyq-star** [wyouflf/xUtils3#542]
你好，我在使用3.1.22版本的时候，通过@Event绑定了btn的事件，然后点击Home键回到桌面，到系统设置中把时间改成昨天，比如今天是5.6，改成5.5，然后返回设置主界面，然后通过菜单键回到app(注意，app只是从后台重新显示出来)，btn事件就失效了，然后我按Home键回到桌面，再把时间改回来，再回去app，事件就恢复了。

后来我以为是旧版本的问题，就升级到3.5.0，发现问题依旧。

再后来以为是系统的问题，我一开始使用的是5.1.1，后来使用7.1.2，这个问题还是有。你可以试一下，百分百必现的。改改日期或分钟数，再按返回键回到设置主页面，再回到app，就会出现。很奇怪的问题。

**Comment by imyyq-star** [comment]
应该是Android本身的问题。已向Google反馈。

**Comment by mehayou** [comment]
这不是Android本身的问题，你去看看源码...笑cry

**Comment by imyyq-star** [comment]
@mehayou 我是发现不用XUtil也会这样，你可以在你的手机上试一下，新建一个项目，不使用XUtil，直接使用setOnClickListener的方式监听按钮，经过以上步骤，会发现点击事件也消失了。

**Comment by mehayou** [comment]
@imyyq-star 我也遇到这个问题，我肯定也测试过啊，是正常的。你看看我提的-->[https://github.com/wyouflf/xUtils3/issues/551](url)

**Comment by imyyq-star** [comment]
@mehayou 你提的问题，我也有提过类似的[https://github.com/wyouflf/xUtils3/issues/423](url)，但是Android原生的setOnClickListener也会有这样的问题就不对了。

**Comment by mehayou** [comment]
@imyyq-star 不知道你是怎么搞出原生的setOnClickListener也不行。。。我一直是可以的。如果你看过源码并且看懂，就不会考虑这个了，因为明显源码是存在问题的。

**Comment by imyyq-star** [comment]
@mehayou 你试一下嘛。很简单的代码。
`
button.setOnClickListener(new View.OnClickListener()
        {
            @Override
            public void onClick(View v)
            {
                Log.i("MainActivity", "onClick: ");
            }
        });
`

再按照我上面提的问题的操作，就会发现点击事件没了。

我没有去看Android系统的点击事件源码和XUtil的源码。这个问题对于我来说影响几乎没有，我是巧合的情况下才发现的。

我的手机是Nexus 6p，系统7.1.2的都有这个问题。

**Comment by GitHubAFeng** [comment]
我也碰到这问题，使用setOnClickListener就OK

**Comment by wyouflf** [comment]
已修复, 谢谢反馈
