### ISSUE TITLE
uxtils3 上传图片失败

### ISSUE THREAD

**Issue by ZSSsongshu** [wyouflf/xUtils3#543]
我用  params.setMultipart(true);params.addBodyParameter("files", file);的方式想要上传一张图片 并且添加 params.addBodyParameter("type", model.getType());params.addBodyParameter("fname", model.getFname());并且采用post请求 ，后在服务端断点后发现  “ type”和“ fname”的值在get中  不在post中  ，而file的值在post中  挺奇怪的 后来我只能用xutils3来解决其他的网络访问问题 ，上传图片还是职能使用 原来的老版本的uxtils 目前项目中着两个库同时存在   望解决

**Comment by WangManAndroid** [comment]
3.0版本是可以上传文件（图片），你可以使用回调监听，如果上传进度为100说明上传完毕，但是，但是，但是：如果后端接收不到你的文件，那你肯定上传失败，很有可能是后端接收文件的函数有问题，我之前就是这样的，以为这个不能上传文件，原来是后端接收文件有问题，心中万匹草泥马奔过。

**Comment by wyouflf** [comment]
更新下试试
