### ISSUE TITLE
HttpClient的这种写法用xutils3怎么写？

### ISSUE THREAD

**Issue by dingzhixiang** [wyouflf/xUtils3#546]
HttpClient httpClient = new DefaultHttpClient();
        
        //CloseableHttpClient  httpClient = HttpClients.createDefault();

        HttpPost httpPost = new HttpPost(url);

        httpPost.setHeader("Content-Encoding", "gzip");
        
        httpPost.addHeader("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
        
        //设置读取时间
        httpClient.getParams().setParameter(CoreConnectionPNames.CONNECTION_TIMEOUT, 60000);
        
        httpClient.getParams().setParameter(CoreConnectionPNames.SO_TIMEOUT, 60000);
        
        try {

            ByteArrayOutputStream originalContent = new ByteArrayOutputStream();

            originalContent.write(message.getBytes(Charset.forName("UTF-8")));

            ByteArrayOutputStream baos = new ByteArrayOutputStream();

            GZIPOutputStream gzipOut = new GZIPOutputStream(baos);

            originalContent.writeTo(gzipOut);

            gzipOut.finish();

            httpPost.setEntity(new ByteArrayEntity(baos.toByteArray()));    

        } catch (Exception e) {

            e.printStackTrace();

       }

        HttpResponse httpResponse = httpClient.execute(httpPost);

**Comment by wyouflf** [comment]
params.setRequestBody(new InputStreamBody...)
