### ISSUE TITLE
超时时间问题

### ISSUE THREAD

**Issue by liaohuyu** [wyouflf/xUtils3#547]
我是这样测试的，用一个没有网络的wifi测试超时，发现超时最低10多秒，高的可达30多秒。然而我设置的是5S超时和读取也是5S。也就是说超时完全没作用啊！java.net.UnknownHostException: Unable to resolve host "XXX": No address associated with hostname。这是很久后才返回的错误，错误竟然不是timeout！

**Comment by liaohuyu** [comment]
@wyouflf

**Comment by tianyalian** [comment]
亲，我也遇到了，和你的问题一模一样，我看源码中HttpTask中并没有使用connectTimeOut和readTimeOut，只能这样了。

**Comment by liaohuyu** [comment]
@tianyalian 那你怎么解决呢的？

**Comment by wang521314** [comment]
你们解决了吗？

**Comment by wyouflf** [comment]
get请求失败默认会重试2次, params.setMaxRetryCount(0)
