### ISSUE TITLE
加载圆形头像时出现方形的背景，安卓5.0以上正常，4.4以下就会出现这个问题，这是为什么啊？

### ISSUE THREAD

**Issue by jhyHenry** [wyouflf/xUtils3#548]

**Comment by a904754642** [comment]
最好别用xutils3的加载头像类，好久没更新了，github上有一直更新的头像组件

**Comment by jiahongyu0529** [comment]
好的，谢谢，我试试

**Comment by jiahongyu0529** [comment]
好像是setCrop（）的问题，我设为true后就好了

**Comment by wenwen0904** [comment]
更新了3.5.0后有这个问题，换回3.4.0没问题

**Comment by wenwen0904** [comment]
并且当从网络和内存加载时没问题，框架把图片缓存到本地后，从本地文件取的时候就会这样

**Comment by xiaoguanghong** [comment]
imageview 的background 设为透明

**Comment by GreatRoader** [comment]
在ImageDecoder.java  589行 将thumbBitmap.compress(supportWebP ? Bitmap.CompressFormat.WEBP : Bitmap.CompressFormat.PNG, 80, out); 更改为thumbBitmap.compress( Bitmap.CompressFormat.PNG, 80, out); 即可

**Comment by wyouflf** [comment]
新版已修复
