### ISSUE TITLE
在 RequestParams 类中 没有选择 http/https

### ISSUE THREAD

**Issue by weikao** [wyouflf/xUtils3#55]
在 RequestParams 类中 没有选择 http/https
HttpURLconnection
HttpsURLconnection

**Comment by wyouflf** [comment]
不用选择, 需要证书时参数设置 sslFactory就可以.

**Comment by weikao** [comment]
但是 在 HttpRequest 类中

connection 只有 是 HttpsURLConnection 才会 setSSLSocketFactory

            if (connection instanceof HttpsURLConnection) {
                SSLSocketFactory sslSocketFactory = params.getSslSocketFactory();
                if (sslSocketFactory != null) {
                    ((HttpsURLConnection) connection).setSSLSocketFactory(sslSocketFactory);
                }
            }

**Comment by weikao** [comment]
3.1.13 感觉 setSslSocketFactory 不起作用

**Comment by weikao** [comment]
搞定了。就是HttpsURLConnection 判断有问题。getSslSocketFactory不起作用。HttpURLConnection可以应付一般的https，双向证书就不行了。因为我只需要https所以把所有的HttpURLConnection都替换了。希望完善。

**Comment by wyouflf** [comment]
源码更新到3.1.14, 以解决一个兼容问题.
