### ISSUE TITLE
ImageLoader抛出异常时引发的问题

### ISSUE THREAD

**Issue by wenwen0904** [wyouflf/xUtils3#552]
当从网络请求回图片时decodeFile失败抛出异常，但请求的状态是200，故导致最终的result为null，并且没有回调来处理此问题。
ImageLoader中的原代码
@Override
    public void onSuccess(Drawable result) {
        if (!validView4Callback(!hasCache)) return;

        if (result != null) {
            setSuccessDrawable4Callback(result);
            if (callback != null) {
                callback.onSuccess(result);
            }
        }
    }
希望在判断中完善等于null的情况处理。个人希望当result==null时触发setErrorDrawable4Callback此方法，将配置的错误图片显示出来。

**Comment by wyouflf** [comment]
新版本已经修复此问题, decode失败会抛出异常.
