### ISSUE TITLE
提交Google APP审核报错Vulnerable classes:  org.xutils.x$Ext$1

### ISSUE THREAD

**Issue by songqilong** [wyouflf/xUtils3#554]
提示内容：
Your app is using an unsafe implementation of HostnameVerifier. Please see this Google Help Center article for details, including the deadline for fixing the vulnerability.
Vulnerable classes:

org.xutils.x$Ext$1

功能正常，但是无法通过审核
This information is intended for developers with app(s) using an unsafe implementation of the HostnameVerifier interface, which accepts all hostnames when establishing an HTTPS connection to a remote host with the setDefaultHostnameVerifier API. This implementation makes the app vulnerable to man-in-the-middle attacks. An attacker can potentially read transmitted data (such as login credentials), and even change the data transmitted on the HTTPS connection.

**Comment by Znetwork** [comment]
Hello, did you solve the problem? I have encountered, try a lot of ways are not resolved it, hope you can share your success method, grateful.你好，您解决了这个问题吗？我也遇到了，尝试很多的方法都没有解决它，望您能够分享下您成功的方法，感激不尽。

**Comment by songqilong** [comment]
It is possible that the HTTP framework causes unsafe factors.I changed the frame in order to pass the normal audit.I use AndroidAnnotations now.

**Comment by wyouflf** [comment]
fixed: https://github.com/wyouflf/xUtils3/commit/f9ad4c87f8bb28056a7260b40f1ff4074d38fb13#diff-0d33dd0a86581dbf118b76b023aafbfa
