### ISSUE TITLE
3.5.0版本图片加载bug反馈

### ISSUE THREAD

**Issue by wenwen0904** [wyouflf/xUtils3#558]
当从本地缓存加载圆形图片时，被切割的部分变成了黑色不是透明，3.4.0版本无问题，请查明修复

**Comment by QXYoung** [comment]
i stick with it,too

**Comment by xiaobaDev** [comment]
rgb8888是透明的，rgb4444是黑色的，你看下

**Comment by wenwen0904** [comment]
rgb的问题？3.5修改了这个默认值吗？之前看的时候印象中默认值是rgb8888，我本身没有去改变这个参数。而且第一次从网络加载的时候还没问题，之后读本地缓存就有问题了，当时猜测是保存本地缓存时出了问题，我还没有好好去查看源码，有空了再仔细研究一下。感谢楼上回答，到时候会额外注意一下rgb的问题

**Comment by baibai2013** [comment]
ARGB_8888 png图也是缓存黑边 求解决

**Comment by baibai2013** [comment]
小米pad 1  安卓版本4.4.4 miui系统 8.5 是有这个问题， 华为的mt9 系统6没有问题ARGB_4444 png图透明区域黑的问题

**Comment by wyouflf** [comment]
试试新版本, 可以不设置Bitmap.config, 有圆角或圆形裁剪是会默认使用ARGB_8888.
