### ISSUE TITLE
安卓4.0.3(API 15 )下兼容性

### ISSUE THREAD

**Issue by anda1982** [wyouflf/xUtils3#56]
数据库操作线程出现死锁，导致进程被强制结束
项目附带的sample程序也重现

**Comment by anda1982** [comment]
使用SDK自带的模拟器(4.0.3)与一台GT-i9300(4.0.4)实体机均出现问题

**Comment by anda1982** [comment]
API 15下 SQLiteClosable没有implements Closeable，导致在SQLiteStatement上使用IOUtil.closeQuietly 出错

**Comment by wyouflf** [comment]
IO密集操作时 sqlite性能明显下降, 尽量在非UI线程操作.

**Comment by anda1982** [comment]
那API 15下这个兼容问题会解决么？现在我是自己修改源代码解决的

**Comment by wyouflf** [comment]
已修改为使用releaseReference()关闭, 稍后更新3.1.14
