### ISSUE TITLE
EOFException

### ISSUE THREAD

**Issue by hxkdidi** [wyouflf/xUtils3#564]
经常出现这个异常

**Comment by tvvbbb** [comment]
这个你是在返回的json反序列化出现的么？

**Comment by hxkdidi** [comment]
是网络请求的过程中出现的，我设置的7s超时，实际上7s之内就会出现这个异常
/**
     * 失败处理
     */
    public void failure(XUtilsRequestCallBack callBack, Throwable ex) {
        if (callBack != null) {
            if (ex instanceof JSONException || ex instanceof JsonParseException || ex instanceof
                    NumberFormatException) {
                callBack.onFailed("数据解析失败,请稍后重试");
            } else if (ex instanceof SocketTimeoutException) {
                callBack.onFailed("网络超时,请稍后重试");
            } else if (ex instanceof EOFException) {
                callBack.onFailed("数据处理错误,请稍后重试");
            } else {
                callBack.onFailed("网络错误,请稍后重试");
            }
        }
    }

**Comment by tvvbbb** [comment]
你会出现那个异常呢？如果进入了这个异常，你谷歌一下应该挺容易解决的吧？

**Comment by hxkdidi** [comment]
EOFException啊，这个也许是框架的问题吧，谷歌上说读取io流缓冲区设置，我查了的，不知道在源码哪里改

**Comment by tvvbbb** [comment]
好的

**Comment by wyouflf** [comment]
https://stackoverflow.com/questions/15411213/android-httpsurlconnection-eofexception
android系统稳定性问题, API 19之前非常容易复现, xUtils已经针对此问题优化, 但不能100%保证, 目前随着升级系统稳定性越来越好.
