### ISSUE TITLE
how to get server time by http request?

### ISSUE THREAD

**Issue by nesger** [wyouflf/xUtils3#573]
hey!
I want to get the server time by http request, how do I do?
Can you help me solve this solution.
Wait for your answer!
Thanks a lot!

**Comment by wyouflf** [comment]
try add the server time in the response headers, then you can get it from the header.

**Comment by wyouflf** [comment]
https://github.com/wyouflf/xUtils3/blob/master/sample/src/main/java/org/xutils/sample/http/JsonResponseParser.java
