### ISSUE TITLE
异步时回调如果出现异常被吃掉 

### ISSUE THREAD

**Issue by asdtiang** [wyouflf/xUtils3#575]
onSuccess里代码如果出现exception，会被吃掉，什么都不打印。
版本3.5.0

**Comment by Eyt** [comment]
好像会在onError 里面打印，你可以试试，我之前好像遇到过。 版本：3.5.0

**Comment by asdtiang** [comment]
![qq 20170807103809](https://user-images.githubusercontent.com/1144419/29010257-80d7855c-7b5c-11e7-8906-d228655af9a1.png)
这里任务出现异常，首先调用了onError，结果onError没有实现，throw出去了，即必须在外面自己捕获，要不然在onError为空，没有自己try的情况下，异常就打印不出来了。这个使用者也有责任，但架构应该处理这种情况好些
