### ISSUE TITLE
org.xutils.ex.FileLockedException: download exists:

### ISSUE THREAD

**Issue by skylele2** [wyouflf/xUtils3#576]
用xutil3下载文件（'org.xutils:xutils:3.3.40'），然后一直报这个错，过一段时间之后再试还是这样，怎么解决？

**Comment by venciallee** [comment]
这个问题的关键是`FileLoader#load(InputStream)`中的` finally {
           IOUtil.closeQuietly(bis)
            IOUtil.closeQuietly(bos);
        }`, IOUtil.closeQuietly(bis)的耗时大概是几百毫秒到几秒, 这时, `processLock`得不到释放, 因此重复点击下载, 会抛出这个异常, 解决办法是把`FileLoader#load(InputStream)`中的`IOUtil.closeQuietly(bis)`删除, 在`FileLoader#load(UriRequest)`的finally加上`IOUtil.closeQuietly(request.getInputStream());`
另外, 还需要解决快速点击导致下载失败, 还需要在`HttpRequest#close`修改成`@Override
    public void close() throws IOException {
        if(!isCancel) {
            isCancel = true;
            if (inputStream != null) {
                IOUtil.closeQuietly(inputStream);
                inputStream = null;
            }
            if (connection != null) {
                connection.disconnect();
                throw new IllegalStateException("connect is cutting down");
                //connection = null;
            }
        }
    }`

**Comment by qiufeng1230** [comment]
将FileLoader.java中的processLock = ProcessLock.tryLock(saveFilePath + "_lock", true);改为processLock = ProcessLock.tryLock(saveFilePath + "_lock", true,2000); cancel的时候有些流没有关闭，给出充足的时间来解除进程锁

**Comment by wyouflf** [comment]
可以在停止下载的时候加个loading, 在onFinish的时候才将重新下载的按钮置为可点击.
针对下载请求可以自己设置params.addHeader("Connection", "close”); 可以更快速的停止.
