### ISSUE TITLE
我想请问一下怎么获得响应头信息啊??在线急等

### ISSUE THREAD

**Issue by azhengyongqin** [wyouflf/xUtils3#579]
因为业务中需要获取请求响应头中的信息..

**Comment by shenqinwei** [comment]
我也想知道，怎样获取响应头里面的数据。业务需要

**Comment by jieatgstdev** [comment]
@azhengyongqin @shenqinwei 怎么获取的？现在知道了么？望指教

**Comment by shenqinwei** [comment]
@jieatgstdev https://www.jianshu.com/p/3f8c4c298b4c

**Comment by azhengyongqin** [comment]
@shenqinwei @jieatgstdev 不好意思 ,已经抛弃这个工具了,当时主要是学习Android的时候用的这个,我现在基本都是用 Okhttp 和 Retrofit2了

**Comment by wyouflf** [comment]
callback实现 {@link org.xutils.http.app.RequestInterceptListener}
或者 ResponseParser 见sample工程代码.
