### ISSUE TITLE
cookie失效

### ISSUE THREAD

**Issue by lu769257351** [wyouflf/xUtils3#580]
你好！我这遇到一个问题是在在登录的时候，服务器返回一个token给APP，APP再用返回的token去获取其他数据，当服务器把token的有效期设置成30天以内的时，token可以正常使用，但是当大于30天就会拿不到我发过去的token，请问这个问题是什么原因造成的？

**Comment by wyouflf** [comment]
cookie里时间是怎么设置的呢, 给一个示例
