### ISSUE TITLE
数据库操作中，更新了数据库，怎么判断某个表是否存在某个字段？

### ISSUE THREAD

**Issue by Sabirjan** [wyouflf/xUtils3#581]
数据库操作中，更新了数据库版本，怎么判断某个表是否存在某个字段？

**Comment by wyouflf** [comment]
可以使用findDbModelFirst方法,在sqlite_master表中查找, sql: 
"select * from sqlite_master where name = tableName and sql like %columnName%"

**Comment by Sabirjan** [comment]
ok,谢谢
