### ISSUE TITLE
POST操作debug模式正常，非debug模式报错，为什么？

### ISSUE THREAD

**Issue by mowang666** [wyouflf/xUtils3#582]
POST操作，JSON格式，debug模式正常，非debug模式报错如下，为什么？

post failed, msg: recvfrom failed: ECONNRESET (Connection reset by peer)
08-24 16:05:02.709 21971-21971/system W/System.err: java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
08-24 16:05:02.709 21971-21971/system W/System.err:     at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:588)
08-24 16:05:02.709 21971-21971/system W/System.err:     at libcore.io.IoBridge.recvfrom(IoBridge.java:552)
08-24 16:05:02.709 21971-21971/system W/System.err:     at java.net.PlainSocketImpl.read(PlainSocketImpl.java:481)
08-24 16:05:02.709 21971-21971/system W/System.err:     at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
08-24 16:05:02.709 21971-21971/system W/System.err:     at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
08-24 16:05:02.709 21971-21971/system W/System.err:     at com.android.okhttp.okio.Okio$2.read(Okio.java:135)
08-24 16:05:02.709 21971-21971/system W/System.err:     at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
08-24 16:05:02.709 21971-21971/system W/System.err:     at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
08-24 16:05:02.709 21971-21971/system W/System.err:     at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
08-24 16:05:02.709 21971-21971/system W/System.err:     at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
08-24 16:05:02.709 21971-21971/system W/System.err:     at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
08-24 16:05:02.709 21971-21971/system W/System.err:     at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
08-24 16:05:02.709 21971-21971/system W/System.err:     at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:905)
08-24 16:05:02.709 21971-21971/system W/System.err:     at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:789)
08-24 16:05:02.709 21971-21971/system W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:443)
08-24 16:05:02.709 21971-21971/system W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
08-24 16:05:02.709 21971-21971/system W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:150)
08-24 16:05:02.709 21971-21971/system W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderFields(HttpURLConnectionImpl.java:210)
08-24 16:05:02.709 21971-21971/system W/System.err:     at org.xutils.http.request.HttpRequest.sendRequest(HttpRequest.java:226)
08-24 16:05:02.709 21971-21971/system W/System.err:     at org.xutils.http.loader.ObjectLoader.load(ObjectLoader.java:115)
08-24 16:05:02.709 21971-21971/system W/System.err:     at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:82)
08-24 16:05:02.710 21971-21971/system W/System.err:     at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:277)
08-24 16:05:02.710 21971-21971/system W/System.err:     at org.xutils.http.HttpTask$RequestWorker.request(HttpTask.java:600)
08-24 16:05:02.710 21971-21971/system W/System.err:     at org.xutils.http.HttpTask.doBackground(HttpTask.java:305)
08-24 16:05:02.710 21971-21971/system W/System.err:     at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
08-24 16:05:02.710 21971-21971/system W/System.err:     at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21)
08-24 16:05:02.710 21971-21971/system W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
08-24 16:05:02.710 21971-21971/system W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
08-24 16:05:02.710 21971-21971/system W/System.err:     at java.lang.Thread.run(Thread.java:818)
08-24 16:05:02.710 21971-21971/system W/System.err: Caused by: **android.system.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)**
08-24 16:05:02.710 21971-21971/system W/System.err:     at libcore.io.Posix.recvfromBytes(Native Method)
08-24 16:05:02.710 21971-21971/system W/System.err:     at libcore.io.Posix.recvfrom(Posix.java:189)
08-24 16:05:02.710 21971-21971/system W/System.err:     at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
08-24 16:05:02.710 21971-21971/system W/System.err:     at libcore.io.IoBridge.recvfrom(IoBridge.java:549)
08-24 16:05:02.710 21971-21971/system W/System.err: 	... 27 more

**Comment by wyouflf** [comment]
看着像混淆的问题, 参考sample工程的混淆配置试试
