### ISSUE TITLE
下载时onLoading不走回调

### ISSUE THREAD

**Issue by ByHSH** [wyouflf/xUtils3#583]
我在下载一个文件的时候,onStarted和onSuccess回调都走了,但是就是不走onLoading方法,我换其他文件的话没有问题,是什么情况导致这个的发生呢?

**Comment by ByHSH** [comment]
需不需要我提供文件来协助找到这个问题呢?

**Comment by slamgo** [comment]
@ByHSH 这个解决了吗？我也遇到了这个问题

**Comment by ByHSH** [comment]
没解决，我是下载的m3u8链接，有部分没有走回调
