### ISSUE TITLE
在部分机型上使用圆角出现黑色区域。

### ISSUE THREAD

**Issue by mirror5821** [wyouflf/xUtils3#587]
使用圆角或者圆形图片时，在部分机型上出现黑色底色，已知机型：锤子1，红米1，vivo部分机型。

**Comment by GreatRoader** [comment]
在ImageDecoder.java 589行 将thumbBitmap.compress(supportWebP ? Bitmap.CompressFormat.WEBP : Bitmap.CompressFormat.PNG, 80, out); 更改为thumbBitmap.compress( Bitmap.CompressFormat.PNG, 80, out); 即可

**Comment by mirror5821** [comment]
谢谢
