### ISSUE TITLE
ImageLoader的clearMemCache不会及时释放Native Heap

### ISSUE THREAD

**Issue by luwei2012** [wyouflf/xUtils3#588]
1.  ImageLoader里面复写的entryRemoved，只是把Java层的drawable对象移除了，但是Bitmap数据是通过decodeStream方法在native层创建的，所以需要手动把Bitmap标致为recycle才会及时释放

2. ImageLoader的clearMemCache也是同样的道理

**Comment by wyouflf** [comment]
建议由系统自动释放
