### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.xutils.db.table.ColumnEntity.isAutoId()' on a null object reference

### ISSUE THREAD

**Issue by tikeyc** [wyouflf/xUtils3#591]
当我创建一个实体类如下：
@Table(name = "loginModel")
public class WRLoginModel {
...
}
如果加了这行代码：@Table(name = "loginModel")我的请求出错。如果不加则请求成功，不报错。
x.http().get(requestParams, new Callback.CacheCallback<String>() {
...
           @Override
            public void onError(Throwable ex, boolean isOnCallback) {
                报错了，从错误信息：
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.xutils.db.table.ColumnEntity.isAutoId()' on a null object reference
            }
}

**Comment by ZHANGfeng-james** [comment]
在我做的项目中，出现上述问题是代码混淆导致的。需要在 proguard-rules.pro 中 -keep 这个类。

**Comment by CharleyCao** [comment]
@ZHANGfeng-james 我也出现了这个问题，但是加了混淆配置貌似也没有用。是我配置错误了吗，请问你时怎么配置的呢？

**Comment by wyouflf** [comment]
参考示例代码的混淆配置
