### ISSUE TITLE
有的图片圆角无效？？？？？？

### ISSUE THREAD

**Issue by HuangJAndroid** [wyouflf/xUtils3#592]

**Comment by HuangJAndroid** [comment]
listview和gridview圆角没有效果

**Comment by wyouflf** [comment]
和view没有关系, 是否公用了imageOptions, 被其他地方修改

**Comment by wyouflf** [comment]
也可能是图片很大没有裁剪，比如图片宽高500，圆角的值只有5， 缩放以后圆角就看不出来了， 建议设置size， 需要裁剪的设置crop
