### ISSUE TITLE
下载异常

### ISSUE THREAD

**Issue by ByHSH** [wyouflf/xUtils3#593]
下载到63.06%就几乎下载变得很慢,几乎不动(不是自身的网络问题),不走onError与onCancelled与onFinished回调,然后还会自动重新下载,附上链接http://106.4.158.132/strmhsnbhemboffbatctznzsafbrrssfpgzfppzc?key=53F8012466F81678066FD9E7B28EDCDC&filelen=1627055573,这是什么情况,请指点去找到解决问题的方法或者产生问题的原因,感激不尽

**Comment by wyouflf** [comment]
设置retry次数, 默认失败后会再重试2次, 下载一部分后变慢检查服务端问题
