### ISSUE TITLE
在华为CAM-AL00手机上自动添加body

### ISSUE THREAD

**Issue by zzy1147** [wyouflf/xUtils3#594]
在华为CAM-AL00手机上自动添加body.
key:serialVersionUID.不知道为什么

**Comment by hjb0924** [comment]
new 完之后，先清除一下 requestParams.clearParams();

**Comment by wyouflf** [comment]
暂时不要添加private static final long serialVersionUID = XXXX; 在你的对象参数上
下个版本会优化
