### ISSUE TITLE
xUtils3下载网络图片，部分机型提示保存失败。

### ISSUE THREAD

**Issue by kakashilw** [wyouflf/xUtils3#596]
String saveImgPathName = "test";
			
		final String fileName = System.currentTimeMillis() + ".jpg";
			
		File tmpFileDir = new File(Environment.getExternalStorageDirectory(), saveImgPathName);
	
		String tmpFilePath = tmpFileDir.getPath()+ "/" + fileName;

		RequestParams params = new RequestParams(imgUrl);
		params.setSaveFilePath(tmpFilePath);
	        params.setAutoResume(false);
	        params.setAutoRename(true);
			
		    Toast.makeText(_context, "正在保存图片...",Toast.LENGTH_SHORT).show();
		    
		    x.http().get(params, new CommonCallback<File>() {
	    	  

	    	    @Override
	            public void onSuccess(File result) {

		        	........省略图片存储到系统相册的步骤..............
		            Toast.makeText(_context, "保存成功!", Toast.LENGTH_SHORT).show();           
		            
		            
	            }

	            @Override
	            public void onError(Throwable ex, boolean isOnCallback) {
	     		 
	     			Toast.makeText(_context,"保存失败!",Toast.LENGTH_SHORT).show();
	    		
	            }

	            @Override
	            public void onCancelled(CancelledException cex) {
	            
	            }

	            @Override
	            public void onFinished() {

	            }
	       });
	       
	       
	       大家好，我们项目中使用了xUtils来保存网络图片，代码如上面所示，
在xiaomi，oppo，vivo等几个机器，andriod5-andirod7都测试，以上代码均没有问题，
不过最近有用户【华为bln-al10 andriod 7.0和 是SAMSUNG SM-9100 andriod 6.0.1】
等反馈保存失败，不知道有遇到过这个问题的吗？

**Comment by wyouflf** [comment]
没有外部存储的权限, 需要主动申请权限
