### ISSUE TITLE
关于多文件上传怎么处理一个key对应多个File文件的问题呢？

### ISSUE THREAD

**Issue by juzhizhang** [wyouflf/xUtils3#597]
服务器提供了一个接收标识，那么该怎么把多个file对象给上传上去呢？

**Comment by wyouflf** [comment]
params.setMultipart(true);
params.addBodyParameter("uploadFile1", new File("/sdcard/test1.txt"));
params.addBodyParameter("uploadFile2", new File("/sdcard/test2.txt"));
