### ISSUE TITLE
一个比较严重的BUG：Post请求抓包时发现发送的参数会接在URL的后面，类似Get请求，Url是有长度限制的，在需要发送很长的数据时会直接报错

### ISSUE THREAD

**Issue by qq453780304** [wyouflf/xUtils3#598]

**Comment by lk6233160** [comment]
看了你这个ISSUES，特意用抓包工具试了下。。。居然真的是这样！

**Comment by wukuiqing49** [comment]
+1

**Comment by yanglin18810778879** [comment]
+1

**Comment by lqb12172** [comment]
bug原因：
在RequestParams的父类的BaseParams中有checkBodyParams()方法：
private synchronized void checkBodyParams() {
      ......
     //主要是这段代码，条件判断为true的时候，将bodyParams的参数，放到get请求的queryStringParams里面
        if (!HttpMethod.permitsRequestBody(method)
                || !TextUtils.isEmpty(bodyContent) || requestBody != null) {
            queryStringParams.addAll(bodyParams);
            bodyParams.clear();
        }
       ......
       }
}
上面的方法在好几个地方被调用，其中之一是toString方法，所以在使用代码打印查看参数的时候，就会触发上面的逻辑
解决方式：
第一步：修改源码，将checkBodyParams() 方法改为：
private synchronized void checkBodyParams() {
      ......
        if (!HttpMethod.permitsRequestBody(method)
               &&( !TextUtils.isEmpty(bodyContent) || requestBody != null)) {
            queryStringParams.addAll(bodyParams);
            bodyParams.clear();
        }
       ......
       }
}
第二步：在创建RequestParams对象的时候同时需要设置post方法，就可以了
RequestParams params = new RequestParams(uri);
params.setMethod(HttpMethod.POST);

**Comment by wyouflf** [comment]
使用post请求将参数添加在body里 addBodyParameter
