### ISSUE TITLE
参数中标点符号转码问题

### ISSUE THREAD

**Issue by Mocaris** [wyouflf/xUtils3#599]
param.addBodyParameter("target1", parseRes[0]);
param.addBodyParameter("target2", parseRes[1]);
两个参数都是String 类型
正常的应该是这样.. 这个是param.toString()的
?function=1&target1=[[[99,122,0.25000000],[99,121,0.26953125],[99,121,0.27734375],[99,121,0.29101563],[99,120,0.29687500],[99,120,0.30273438]....
但是开始请求了,就会转码成这样..,这个是服务器接收到的..
?function=1&target1=%255B%255B%255B99%252C122%252C0.25000000%255D%252C%255B99%252C121%252C0.26953125%255D%252C%255B99%252C121%252C0.27734375%255D%252C%255B99%252C121%252C0.29101563%
这个问题怎么解决,可否能不转码?

**Comment by wyouflf** [comment]
这个是标准的协议格式, 服务端需要做解码
