### ISSUE TITLE
xUtils3中类x为什么用小写？为什么不遵守java规范的命名规则？

### ISSUE THREAD

**Issue by xiejianchao** [wyouflf/xUtils3#60]
是特殊用意，还是只是疏忽了？

**Comment by wyouflf** [comment]
x.后面紧跟几个常用的静态方法, 由于方法名以小写开头, x也小写的话不需要使用shift键, 输入方便快捷.

**Comment by xiejianchao** [comment]
你说的Androd Studio的代码提示吧，这个可以设置的，使其忽略大小写都出提示，不需要使用shift键，如果只是因为这个而使类的命名使用小写实在得不偿失，感觉很别扭，建议规范一下比较好。

**Comment by ifynn** [comment]
@xiejianchao androidR.id内部类就是小写，有时候需要变通。

**Comment by xiejianchao** [comment]
@ifynn 你说的那个是内部静态类，几乎没有其他例子主类名是小写的先例，当然使用上是没有任何问题，只是用起来稍显怪异。
