### ISSUE TITLE
网络请求时候 缓存有个 。tmp后缀  这个后缀怎么去掉

### ISSUE THREAD

**Issue by liupeng110** [wyouflf/xUtils3#600]
网络请求时候 缓存有个 。tmp后缀  这个后缀怎么去掉

**Comment by wyouflf** [comment]
下载完成的文件没有这个后缀, .tmp是正在下载的, 支持断点续传下载.

**Comment by liupeng110** [comment]
还有个超时时间,设置无效。

**Comment by wyouflf** [comment]
设置maxretrycount 0------------------ 原始邮件 ------------------
发件人: "鹏"<notifications@github.com>
发送时间: 2019年8月22日(星期四) 上午10:31
收件人: "wyouflf/xUtils3"<xUtils3@noreply.github.com>;
抄送: "wyouflf"<wyouflf@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [wyouflf/xUtils3] 网络请求时候 缓存有个 。tmp后缀  这个后缀怎么去掉 (#600)



还有个超时时间,设置无效。
 
&mdash;
