### ISSUE TITLE
http同步请求时,框架能不能扩展个处理下异常问题的api

### ISSUE THREAD

**Issue by liupeng110** [wyouflf/xUtils3#607]
正常的同步请求如下：
try{
String str = x.http().getSync(requestParams, String.class);
}catch(){}
这样同步每次都需要加一个try  有很多多余代码
能不能加一个函数  例如下面
String str = x.http().getSyncNull(requestParams, String.class);
请求失败 框架处理异常 直接返回null; 
如果不需要知道具体的错误代码(直接让用户检查网络并重试)
调用时 判断str是否为null 就知道请求成功失败
这样就非常方便

**Comment by liupeng110** [comment]
@wyouflf

**Comment by zhangjilei106787** [comment]
post同步请求可以进行缓存吗
