### ISSUE TITLE
使用put 和delete方法请求的时候报错！请作者帮忙看看

### ISSUE THREAD

**Issue by marren06** [wyouflf/xUtils3#609]
使用delete 和put 请求的时候 传递了参数请求后onError方法打印：Method Not Allowed

下面是log截图：

![qq 20171102233411](https://user-images.githubusercontent.com/17778482/32334806-697ea066-c026-11e7-8807-2fa306f2fd31.png)
![qq 20171102233416](https://user-images.githubusercontent.com/17778482/32334819-6f249a52-c026-11e7-8a7e-163b1fc59a46.png)
请大神看看到底是哪的原因呢？

**Comment by onlyYU** [comment]
这个是因为后台接口没有添加put 和delete方法的支持
