### ISSUE TITLE
HttpRequest里面，这个把"Content-Length"设置为-1，阿里服务器直接报400错误

### ISSUE THREAD

**Issue by maonanyue** [wyouflf/xUtils3#614]
HttpRequest里面，这个把"Content-Length"设置为-1，阿里服务器直接报400错误

```
        //传一个length 等于0的byte数组
        params.addBodyParameter("xxx", new ByteArrayInputStream(new byte[0]),
                "application/octet-stream", String.valueOf(System.currentTimeMillis()));
```

```java  
      public void addStream(InputStream inputStream) {
            if (total.get() == -1L) return;
            long length = InputStreamBody.getInputStreamLength(inputStream);
            if (length > 0) {
                total.addAndGet(length);
            } else {
                total.set(-1L);
            }
        }
```

按[rfc2616](https://tools.ietf.org/html/rfc2616#page-119)的说法，Content-Length应该要大于0才合法。
> Any Content-Length greater than or equal to zero is a valid value.
   Section 4.4 describes how to determine the length of a message-body
   if a Content-Length is not given.

**Comment by wyouflf** [comment]
谢谢反馈, 问题已修复 https://github.com/wyouflf/xUtils3/commit/1f2c99f7785850e32e45501460f5a4f12a8cbb82
