### ISSUE TITLE
使用 x.image().bind()方法可以正常加载图片，使用x.image().loadFile()方式加载图片加载不出来？

### ISSUE THREAD

**Issue by wuxia510** [wyouflf/xUtils3#618]
Viewpager里存放图片。轮播图效果。。。想要对图片进行缓存，所以使用了x.image().loadFile()方法，在  @Override
            public boolean onCache(File result) {
                LogUtils.e(tag, "addImgViewToList--onCache----result-->" + result.getPath());
                if (result != null) {
                    return true;//true相信本地缓存，第二次加载图片将不会请求网络同时onSuccess返回为空
                }
                return false;
            }

但是图片不显示，打印日志
01-10 10:24:38.807 12470-12470/com.silinkeji.silin E/HomeFragment: addImgViewToList--onCache----result-->/storage/emulated/0/Android/data/com.silinkeji.silin/cache/xUtils_img/10e9f731da3429d1247d785bc0d175dc

**Comment by wyouflf** [comment]
自测没问题, 贴上加载逻辑, 或出错日志
