### ISSUE TITLE
imageOptions 设置的图片大小不生效

### ISSUE THREAD

**Issue by JingYaLi** [wyouflf/xUtils3#619]
new ImageOptions.Builder().setSize(width, height).setRadius(DensityUtils.dip2px(context,10)).setFailureDrawableId(R.drawable.load_failed_pic)
                .build()；
imageview设置的是wrap_content

**Comment by wyouflf** [comment]
https://github.com/wyouflf/xUtils3/blob/master/sample/src/main/java/org/xutils/sample/ImageFragment.java

参考示例
