### ISSUE TITLE
批量暂停

### ISSUE THREAD

**Issue by Icando26** [wyouflf/xUtils3#620]
任务2000个 调用stopAllDownload 做批量暂停，卡顿很严重
public void stopAllDownload() {
        for (DownloadInfo downloadInfo : downloadInfoList) {
            Callback.Cancelable cancelable = callbackMap.get(downloadInfo);
            if (cancelable != null) {
                cancelable.cancel();
            }
        }
    }

**Comment by wyouflf** [comment]
可以放在子线程操作
