### ISSUE TITLE
下载的文件url中含有中文导致下载失败

### ISSUE THREAD

**Issue by leavesfallenlord** [wyouflf/xUtils3#623]
你好，在使用xutils下载文件的时候发现如果下载的文件url 中不含中文，则可以正常下载，如果含有中文例如：http://www.xxx.cc/file/新建文档.txt 则会下载失败  报错信息：x_log:HttpRequest.sendRequest(L:249): errorCode: 416, msg: Requested Range Not Satisfiable, result: {"code":"InvalidRange","message":"The requested range cannot be satisfied.","requestId":"a69e37a6-7dea-4f43-82dd-da73b0b81444"}, url: http://这里是域名//file/doc/中文名称+文件格式   还请指教，谢谢。

**Comment by Arcty** [comment]
toUTF-8

**Comment by wyouflf** [comment]
urlencode
