### ISSUE TITLE
数据库   string 不能作为主键么？

### ISSUE THREAD

**Issue by llakcs** [wyouflf/xUtils3#627]
使用xutils3 创建表的设置  

   @Column(name = "Braceletmac",isId = true,autoGen = false)
    private String Braceletmac;

调用创建数据库方法db.saveOrUpdate(t);

提示：org.xutils.ex.DbException: near ")": syntax error (code 1): , while compiling: CREATE TABLE IF NOT EXISTS "brace" ( "Braceletmac"TEXT PRIMARY KEY, )

**Comment by GHYOWEE** [comment]
对

**Comment by skyfouk** [comment]
确实存在主键不能为string的问题。
并且：
当数据库主键非自增，saveOrUpdate没有作用。
![image](https://user-images.githubusercontent.com/7720849/49783977-b88c0900-fd56-11e8-9749-25c5255cbd57.png)

**Comment by pxx11111** [comment]
我复现了你的问题，你应该是数据表只有主键才报错，注解时候注意再注解一个列，就没问题了，楼上说string不能做主键和贴代码的，代码都没看明白就回答了

**Comment by wyouflf** [comment]
string可以做主键，自增主键为空时使用replace语句更新数据。
