### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by EvanEvil** [wyouflf/xUtils3#628]
![error](https://user-images.githubusercontent.com/23189683/37643475-a192065e-2c5b-11e8-82b4-b73e2885aab2.png)

**Comment by EvanEvil** [comment]
下载地址 类似这样:https://www.xxx.com/data/upload/database/维修资料/天津夏利/夏利2000/2001-2005/维修手册/第五章1ABS防抱死系统的维修.doc
在电脑浏览器可以正常下载

**Comment by wyouflf** [comment]
403没有权限, 需要登录才能下载?
