### ISSUE TITLE
java.net.SocketTimeoutException: SSL handshake timed out

### ISSUE THREAD

**Issue by laksg2009** [wyouflf/xUtils3#629]
公司两个WIFI一个不会报这个错,一个有时会有时不会,用GPRS流量的话也会报这个错.有时候过一天三个上网方式都没问题...超级郁闷...............

**Comment by Shyky** [comment]
放弃吧，用retrofit或okhttp

**Comment by laksg2009** [comment]
@Shyky 我翻墙访问就没问题了.估计防火墙这个月更新了.

**Comment by Shyky** [comment]
用retrofit吧，放弃吧

**Comment by laksg2009** [comment]
@Shyky 问题算是解决了.用的是国外的服务器有时被墙有时没问题.所以翻墙请求就不会有这个问题存在了

**Comment by wyouflf** [comment]
@Shyky 防火墙的问题, 用什么都一样, xUtils3用的urlconnecttion, 底层也是okhttp.
