### ISSUE TITLE
根布局改成<merge>  ViewInject 返回 Null

### ISSUE THREAD

**Issue by xiaotd** [wyouflf/xUtils3#631]
根布局改成'\<merge\>'  ViewInject 返回 Null

根布局 使用' \<FrameLayout\>'  ViewInject 返回view

主页面使用'\<include\>' 引用一个通用页面时，如果通用页面的根布局是merge，主页面就无法通过@ViewInject方式

**Comment by wyouflf** [comment]
我测试使用<merge>没有问题, 关键代码逻辑方便贴出来吗, 或者升级新版本试试.
