### ISSUE TITLE
可以断点上传吗？

### ISSUE THREAD

**Issue by TYUpya** [wyouflf/xUtils3#632]
请问可以断点上传大文件吗？不是断点下载、不是断点下载、不是断点下载
请问怎么写？

**Comment by wyouflf** [comment]
http协议不支持断点上传，但可以自己实现，简单实现可以在每次上传前请求服务端返回某个文件的已上传进度，这一步最好加上文件md5或sha256校验，然后创建文件流，定位到已上传位置，将文件流加入上传的body，开始上传
