### ISSUE TITLE
unexpected end of stream on Connection

### ISSUE THREAD

**Issue by Zmingxu** [wyouflf/xUtils3#633]
####进行post传递一个json流，数据一过大就会出现这个问题/x_log:TaskProxy$InternalHandler.handleMessage(L:204): unexpected end of stream on Connection{10.18.101.4:6990, proxy=DIRECT hostAddress=10.18.101.4 cipherSuite=none protocol=http/1.1} (recycle count=0)
请问怎么解决呀

**Comment by wyouflf** [comment]
貌似是服务端主动断开了
