### ISSUE TITLE
不知道 上传要设置成每次传1024个byte?

### ISSUE THREAD

**Issue by yang-mr** [wyouflf/xUtils3#635]
MultipartBody类 

private void writeStreamAndCloseIn(OutputStream out, InputStream in) throws IOException {
        if (out instanceof CounterOutputStream) {
            ((CounterOutputStream) out).addStream(in);
        } else {
            try {
                int len;
                byte[] buf = new byte[1024];
                while ((len = in.read(buf)) >= 0) {
                    out.write(buf, 0, len);
                    current += len;
                    if (callBackHandler != null && !callBackHandler.updateProgress(total, current, false)) {
                        throw new Callback.CancelledException("upload stopped!");
                    }
                }
            } finally {
                IOUtil.closeQuietly(in);
            }
        }
    }
不知道 上传要设置成每次传1024个byte?

**Comment by wyouflf** [comment]
已修改未4096
