### ISSUE TITLE
xUtils3 download exists

### ISSUE THREAD

**Issue by songpeng136** [wyouflf/xUtils3#640]
当循环点击下载和暂停时会出现下载存在(download exists)的提示，怎么解决

**Comment by qiufeng1230** [comment]
将FileLoader.java中的processLock = ProcessLock.tryLock(saveFilePath + "_lock", true);改为processLock = ProcessLock.tryLock(saveFilePath + "_lock", true,2000); cancel的时候有些流没有关闭，给出充足的时间来解除进程锁

**Comment by wyouflf** [comment]
onCancelled的回调后才将重新下载按钮设为enable
