### ISSUE TITLE
注解问题

### ISSUE THREAD

**Issue by LelandLi** [wyouflf/xUtils3#644]
注解点击事件无法使用
复现步骤
1.修改系统时间 (如上午10点改成下午2点)
2.打开app
3.按home键让app进入后台，但是不杀死应用
4.把系统时间改回当前时间
5进入app点击事件无法正常使用

**Comment by LelandLi** [comment]
使用原生的事没有问题的，测试手机小米4A

**Comment by wyouflf** [comment]
有一个防止重复点击的设置问题, 下个版本优化
