### ISSUE TITLE
setDefaultHostnameVerifier 问题，如果用https的话，只设置x.Ext.init(this);而没有 x.Ext.setDefaultHostnameVerifier(new HostnameVerifier()）有什么问题吗

### ISSUE THREAD

**Issue by pxx11111** [wyouflf/xUtils3#648]
版本3.5.0，接口是https，初始化时候只设置 x.Ext.init(this);并没有 x.Ext.setDefaultHostnameVerifier(new HostnameVerifier() {
            @Override
            public boolean verify(String hostname, SSLSession session) {
                return true;
            }
        });

**Comment by wyouflf** [comment]
建议自己设置
