### ISSUE TITLE
网络超时问题 

### ISSUE THREAD

**Issue by yzz598559925** [wyouflf/xUtils3#650]
params.setCacheMaxAge(100);
        params.setCharset(CHARSET);
        params.setConnectTimeout(50000);
        params.setAsJsonContent(true);
        params.setBodyContent(json);
代码设置超时时间为50秒，但是我发现真正的超时时间是30秒，也就是说我如果把超时时间设置为大于30秒的，真正的超时时间是30秒，如果设置超时时间小于30秒的那就没问题 ，有那位大佬遇见过这个问题，能帮忙解答下么，十分感谢了

**Comment by yzz598559925** [comment]
@wyouflf   在么 请问下这个问题是怎么造成的么   请在百忙中抽空看下这个问题  十分感谢

**Comment by wyouflf** [comment]
默认会在重试2次 params.setMaxRetryCount(0)
