### ISSUE TITLE
丢失参数的问题

### ISSUE THREAD

**Issue by zyc2056** [wyouflf/xUtils3#651]
使用PUT,或者Delete 方法时会丢失参数，
RequestParams params = new RequestParams(url);
        params.addHeader("Content-FileType", "application/json");
        params.setAsJsonContent(true);

        if (jsonObject != null)
        {
            if (HttpMethod.GET == method)
            {
                for (Map.Entry<String, Object> entry : jsonObject.entrySet())
                {
                    params.addParameter(entry.getKey(), entry.getValue());
                }
            }
            else if (HttpMethod.POST == method)
            {
                params.setBodyContent(jsonObject.toString());
            }
            else if (HttpMethod.PUT == method)
            {
                params.setBodyContent(jsonObject.toString());
            }
            else if (HttpMethod.DELETE == method)
            {
                for (Map.Entry<String, Object> entry : jsonObject.entrySet())
                {
                    params.addParameter(entry.getKey(), entry.getValue());
                }
            }
        }

        x.http().request(method, params, new Callback.CommonCallback<String>()

断点加在最后一行，发送请求的地方参数就不会丢，加在 HttpMethod.DELETE == method 上或者之前参数就会丢，怀疑是  params.addParameter 方法有问题，是不是add是异步，执行快的话没有添加到params里。求作者修复，两个项目都遇到，问同事，同事也遇到过。感觉问题很严重。

**Comment by wyouflf** [comment]
add不是异步部分HttpMethod不支持body参数, 参数会被添加到queryString中
