### ISSUE TITLE
为什么Db/Selector#or(WhereBuilder）方法返回的Selector没有带T

### ISSUE THREAD

**Issue by zhouzhuo810** [wyouflf/xUtils3#657]

**Comment by wyouflf** [comment]
Selector有带, 其他不需要

**Comment by zhouzhuo810** [comment]
![test](https://user-images.githubusercontent.com/15272555/63483448-0274e380-c4cf-11e9-9004-d91fb962705c.jpg)
我说的这个，你确定没问题吗？
