### ISSUE TITLE
使用数据库，多线程selector时报org.xutils.ex.DbException: Cursor window allocation of 2048 kb failed. 

### ISSUE THREAD

**Issue by PingWei1314** [wyouflf/xUtils3#659]
org.xutils.ex.DbException: Cursor window allocation of 2048 kb failed.     好几个线程查询时

**Comment by Yunqi526** [comment]
org.xutils.ex.DbException: Cursor window allocation of 2048 kb failed.  出现这个出应怎样修改

**Comment by wyouflf** [comment]
系统版本是什么, 操作了很多数据吗, 多大的并发量?

**Comment by ScorpioRen** [comment]
我也是出现了这个，db 是全局静态，长时间运行后出现了这个错误
