### ISSUE TITLE
xUtils3网络请求异常

### ISSUE THREAD

**Issue by HahalongGit** [wyouflf/xUtils3#661]
采用xUtils3的项目，在部分手机中无法请求接口，
采用post请求大致如下：
 RequestParams requestParams = new RequestParams(postUrl);
            requestParams.setAsJsonContent(true);
            requestParams.setBodyContent(json);
            x.http().post(requestParams, commonCallback);
请求的时候直接执行回调到
    public void onError(Throwable ex, boolean isOnCallback) {
                    super.onError(ex, isOnCallback);
// 异常回调执行
}
没有执行正常逻辑的方法： @Override
                public void onSuccess(String result) {
// 正常逻辑
}
onError()的异常信息：StackTrace:[Ljava.lang.StackTraceElement;@10c5692e
采用其他方式请求网络可以成功例如：retrofit2+okhttp3 可以请求到结果

**Comment by wyouflf** [comment]
打印完整的错误信息, ex.printStackTrace()
