### ISSUE TITLE
addBodyParameter

### ISSUE THREAD

**Issue by Haha003** [wyouflf/xUtils3#663]
调用RequestParams.addBodyParameter方法后，
 private final List<KeyValue> bodyParams 没有添加成功 添加到了
private final List<KeyValue> queryStringParams里面
![图片](https://user-images.githubusercontent.com/19590081/54336135-24d41c80-4666-11e9-8e18-90df924a6fc0.png)

**Comment by wyouflf** [comment]
你调用的x.http.get方法而不是post?

**Comment by wyouflf** [comment]
尝试新版本, 已经优化请求之前调用RequestParams.toString引起的参数问题
