### ISSUE TITLE
组件声明报错

### ISSUE THREAD

**Issue by zjianflys** [wyouflf/xUtils3#668]
`<?xml version="1.0" encoding="utf-8"?>
<com.zhy.autolayout.AutoRelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@mipmap/splash">

    <TextView
        android:id="@+id/title"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="170px"
        android:gravity="center"
        android:text="汽车"
        android:textColor="#003399"
        android:textSize="20sp" />

</com.zhy.autolayout.AutoRelativeLayout>`

获取组件
` @ViewInject(R.id.title)
    private TextView title;`

报空指针...

您有遇到过嘛？

**Comment by zjianflys** [comment]
报这个
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference

**Comment by wyouflf** [comment]
注入的代码写在哪里, 是否在调用组件之前

**Comment by zjianflys** [comment]
现在可以了   谢谢...
