### ISSUE TITLE
级联查询功能取消了吗？

### ISSUE THREAD

**Issue by Skqing** [wyouflf/xUtils3#67]
查询List<Child>的时候一并查询出每个Child的Parent现在是怎么实现？

**Comment by wyouflf** [comment]
Parent entity = db.findById(Parent.class, child.parentId);

**Comment by DolphinBoy** [comment]
没看懂！
Parent里面没有定义List<child>啊

**Comment by DolphinBoy** [comment]
怎么解决？

**Comment by DolphinBoy** [comment]
查询List的时候一并查询出每个Child的Parent，咋搞，要自己在get方法里面去查Parent吗？

**Comment by DolphinBoy** [comment]
@Table(name = "child")
public class Child{   
@Column(name = "id", isId = true)
    private int id;

    @Column(name = "name")
    public String name;

    @Column(name = "email")
    private String email;

    @Column(name = "isAdmin")
    private boolean isAdmin;

    @Column(name = "time")
    private Date time;

    @Column(name = "date")
    private java.sql.Date date;

    //查询child把这个Parent也加载出来？
    private Parent parent;

**Comment by wyouflf** [comment]
@Table(name = "child")
public class Child {

    @Column(name = "id", isId = true)
    private int id;

    @Column(name = "name")
    private String name;

    @Column(name = "email")
    private String email;

    @Column(name = "parentId" /*, property = "UNIQUE"//如果是一对一加上唯一约束*/)
    private long parentId; // 外键表id

    // 这个属性被忽略，不存入数据库
    private String willIgnore;

    @Column(name = "text")
    private String text;

    public Parent getParent(DbManager db) throws DbException {
        return db.findById(Parent.class, parentId);
    }

    public long getParentId() {
        return parentId;
    }

    public void setParentId(long parentId) {
        this.parentId = parentId;
    }

   ......
}

**Comment by wyouflf** [comment]
@Table(name = "parent", onCreated = "CREATE UNIQUE INDEX index_name ON parent(name,email)")
public class Parent {

    @Column(name = "id", isId = true)
    private int id;

    @Column(name = "name")
    public String name;

    @Column(name = "email")
    private String email;

    @Column(name = "isAdmin")
    private boolean isAdmin;

    @Column(name = "time")
    private Date time;

    @Column(name = "date")
    private java.sql.Date date;

    public List<Child> getChildren(DbManager db) throws DbException {
        return db.selector(Child.class).where("parentId", "=", this.id).findAll();
    }

    // 一对一
    //public Child getChild(DbManager db) throws DbException {
    //    return db.selector(Child.class).where("parentId", "=", this.id).findFirst();
    //}
    .....
}
