### ISSUE TITLE
post的请求有点问题吧，发送参数到服务器，后台接收不到啊。

### ISSUE THREAD

**Issue by jayliu1989** [wyouflf/xUtils3#671]
post的请求有点问题吧，发送参数到服务器，后台接收不到啊。

_Originally posted by @jicg in https://github.com/wyouflf/xUtils3/issues/191#issuecomment-241235935_

**Comment by jayliu1989** [comment]
后台PHP CI框架

**Comment by yuhuazhu** [comment]
如果接口默认是form-data，设置一下params.setMultipart(true)就可以了

**Comment by jayliu1989** [comment]
谢谢  已经搞定了

在2019年06月24日 23:24，大星啊<notifications@github.com><mailto:notifications@github.com> 写道：

如果接口默认是form-data，设置一下params.setMultipart(true)就可以了
