### ISSUE TITLE
一个偶发的问题

### ISSUE THREAD

**Issue by jyh149129** [wyouflf/xUtils3#673]
![捕获](https://user-images.githubusercontent.com/7726240/62931321-bc45c300-bdf0-11e9-976f-a10cfc1ddb37.JPG)

访问服务器接口，返回json字符串，不是每次都出现，检索了很多资料都没有什么规律，而ios平台却是正常的

**Comment by wyouflf** [comment]
http头格式读取有问题, 如果你不使用cookie, 参数对象#setUseCookie(false), 就不会主动读取http头中的数据, 这个错误就可以避免.

**Comment by jyh149129-new** [comment]
关闭cookie也一样会偶发报错。
在okhttp 上看到了相似的一个issuse
https://github.com/square/okhttp/issues/3662
这个似乎是跟链接复用有关系，尝试将java.net.ProcotolException从请求失败不可重试的名单列表中排除后，测试了几天已经没有再发生这个问题。
https://github.com/wyouflf/xUtils3/blob/8d9b9fc1a9d8ce4da30bd1eb892a0abfd6082b5b/xutils/src/main/java/org/xutils/http/app/HttpRetryHandler.java#L37
