### ISSUE TITLE
想问下作者，数据库降级的监听没有吗

### ISSUE THREAD

**Issue by somannick** [wyouflf/xUtils3#674]

**Comment by somannick** [comment]
if (oldVersion != newVersion) {
            if (oldVersion != 0) {
                DbUpgradeListener upgradeListener = daoConfig.getDbUpgradeListener();
                if (upgradeListener != null) {
                    upgradeListener.onUpgrade(dao, oldVersion, newVersion);
                } else {
                    try {
                        dao.dropDb();
                    } catch (DbException e) {
                        LogUtil.e(e.getMessage(), e);
                    }
                }
            }
            database.setVersion(newVersion);
        }
是升降级都在这个监听里吗？

**Comment by wyouflf** [comment]
是的, 都在这个接口监听
