### ISSUE TITLE
加载assets 下处于文件夹中的图片失败

### ISSUE THREAD

**Issue by ybw486** [wyouflf/xUtils3#679]
![image](https://user-images.githubusercontent.com/9948268/65370395-dc3b9280-dc8a-11e9-85fa-f789b81ec98c.png)
这里把asset 图片的文件夹符号全部替换了 导致根本找不到图片

 @Override
    public InputStream getInputStream() throws IOException {
        if (inputStream == null) {
            Context context = params.getContext();
            **String assetsPath = queryUrl.substring("assets:".length());
            assetsPath = assetsPath.replace("/", "");**
            inputStream = context.getResources().getAssets().open(assetsPath);
            contentLength = inputStream.available();
        }
        return inputStream;
    }****

**Comment by ybw486** [comment]
String assetsPath = queryUrl.replace("assets://","");
应该改成这样。

**Comment by wyouflf** [comment]
谢谢反馈, 马上更新

**Comment by wyouflf** [comment]
已修复, 请使用3.7.3版本
