### ISSUE TITLE
Sample中JsonDemoParams.Java和JsonParamsBuilder.Java可以优化

### ISSUE THREAD

**Issue by weikaiyun1990** [wyouflf/xUtils3#681]
1. JsonDemoParams.Java文件有无效的import文件 
2. JsonParamsBuilder.Java中有命名错误的地方，应该是SERVER_A和SERVER_B  现在写成了SEEVER_A和SEEVER_B

**Comment by wyouflf** [comment]
谢谢反馈, 更新了demo
