### ISSUE TITLE
非 SDK 接口限制

### ISSUE THREAD

**Issue by lyl155** [wyouflf/xUtils3#683]
Reflection greylist-max-p Landroid/widget/ImageView;->mMaxWidth
use(s):
 Lorg/xutils/image/ImageOptions;->optimizeMaxSize(Landroid/
widget/ImageView;)V
 Lorg/xutils/image/ImageOptions;->optimizeMaxSize(Landroid/
widget/ImageView;)V
 Lorg/xutils/image/ImageOptions;->optimizeMaxSize(Landroid/
widget/ImageView;)V
 Lorg/xutils/image/ImageOptions;->optimizeMaxSize(Landroid/
widget/ImageView;)V

**Comment by wyouflf** [comment]
感谢反馈, 3.8.5版本修复
