### ISSUE TITLE
请教groupby怎么用？一定要用DbModelSelector么？

### ISSUE THREAD

**Issue by caik13** [wyouflf/xUtils3#688]
看源码发现groupby 返回的是DbModelSelector，用DbModelSelector最后返回的数据类型就要是 DbModel类型的，我只是想做一个普通查询然后groupby去一下重复，返回的DbModel使用很麻烦啊，有其他方法么？

**Comment by caik13** [comment]
不懂作者为啥要这么做，不过我自己修改了Selector的代码，加上了groupby。

**Comment by wyouflf** [comment]
select返回Javabean形式的对象，groupby之后一般会有新的字段产生
