### ISSUE TITLE
org.xutils.image.ImageOptions无法扩展的问题

### ISSUE THREAD

**Issue by luanpao888** [wyouflf/xUtils3#69]
有需求更改ImageOptions.ScaleType
但是ImageOptions.DEFAULT单例且final特性，导致无法拓展

**Comment by wyouflf** [comment]
可以扩展ImageOptions.Builder
#########################
public class CustomImageOptions extends ImageOptions {

    protected YlImageOptions() {
    }

    public static class Builder extends ImageOptions.Builder {

        public Builder(ImageSize size) {
            super();
            this.setSize(size);
        }

        @Override
        protected void newImageOptions() {
            options = new YlImageOptions();
        }

        public void setSize(ImageSize size) {
            super.setSize(size.Width, size.Height);
        }
    }
}


.........

ImageOptions options = new CustomImageOptions.Builder().....build();
.........

**Comment by luanpao888** [comment]
咦 谢谢拉~
没注意到ImageOptions.Builder

**Comment by kanfRUI** [comment]
我想问一下这个框架，上传大文件时有无断点续传的？还有进度条显示？比如上传一个2g的视频文件，如何加上断点续传？希望解答一下
