### ISSUE TITLE
加载gif图片 展示效果不流畅

### ISSUE THREAD

**Issue by Lucklyheart** [wyouflf/xUtils3#691]
示例代码：
 public static void setCircleImg(ImageView imgView,String url){
        
        ImageOptions circleOptions=new ImageOptions.Builder()
                .setIgnoreGif(false)
                .build();
        x.image().bind(imgView, url,circleOptions);

    }

**Comment by Lucklyheart** [comment]
而且
    private static ImageOptions circleOptions=new ImageOptions.Builder()
            .setIgnoreGif(false)
            .setSize(100,100)
            .build();
加载相同gif图片地址，图片老刷新闪烁

**Comment by Lucklyheart** [comment]
将库down下后剔除了image和view注解模块，感觉还不错

**Comment by wyouflf** [comment]
试试最新demo里页面加载了很多gif图, 没有感觉明显的卡顿

**Comment by Lucklyheart** [comment]
好的 感谢作者的回复

**Comment by Lucklyheart** [comment]
新版本动态图加载效果很nice，堪比glide，力挺！
