### ISSUE TITLE
x.image.load图片不显示

### ISSUE THREAD

**Issue by grassy** [wyouflf/xUtils3#697]
这两天把xutils从3.8.3升级到3.8.8之后，有一个地方使用x.image.load照片不显示，点击图片预览图片又可以显示。
![image](https://user-images.githubusercontent.com/4166381/80295315-7d03aa80-87a4-11ea-8e1e-df3f6aa6ae91.png)
![image](https://user-images.githubusercontent.com/4166381/80295328-8d1b8a00-87a4-11ea-8b28-3a4a1b754f61.png)

不显示的代码：为了调试，加了callback，打印的日志是sucess
![image](https://user-images.githubusercontent.com/4166381/80295393-edaac700-87a4-11ea-9ef4-418765b7808f.png)

正常显示的代码:
![image](https://user-images.githubusercontent.com/4166381/80295412-0a46ff00-87a5-11ea-8f0d-c710c9a0f723.png)

**Comment by wyouflf** [comment]
谢谢反馈, 我自测没有发现异常, 我再看看尽快给你回复

**Comment by grassy** [comment]
> 谢谢反馈, 我自测没有发现异常, 我再看看尽快给你回复

您可以试一下，在一个界面是用GridView显示一组照片，然后点击预览照片。我这边试了很多次。我刚刚开始以为是我的域名被劫持导致的，所以换了网络上的照片测试，一样的结果哦。

**Comment by wyouflf** [comment]
抱歉, 最近太忙没来的急处理, 我尽快处理好回复你

**Comment by wyouflf** [comment]
链接: https://pan.baidu.com/s/1OFizjTi72koL89s_wn0C9A 提取码: vyse

试试这个测试版的aar能不能解决你的问题, 如果可以我就更新下
