### ISSUE TITLE
About handle event when database was created.

### ISSUE THREAD

**Issue by mrhuythien** [wyouflf/xUtils3#70]
DbManager.DaoConfig should be has callback (onCreate) when database create. Sometime we need do something after database created.

**Comment by wyouflf** [comment]
If you want to execute some sql scripts when table created, you can add "onCreate" property for @Table.

@Table(name = "parent", onCreated = "CREATE UNIQUE INDEX index_name ON parent(name,email)")

example:
https://github.com/wyouflf/xUtils3/blob/master/sample/src/main/java/org/xutils/sample/db/Parent.java
