### ISSUE TITLE
org.xutils.db.Selector org.xutils.DbManager.selector(java.lang.Class)

### ISSUE THREAD

**Issue by yanzhonghui** [wyouflf/xUtils3#717]
java.lang.NullPointerException: Attempt to invoke interface method 'org.xutils.db.Selector org.xutils.DbManager.selector(java.lang.Class)' on a null object reference

**Comment by XueFeiXia** [comment]
if you bean class changed,you need upgrad you XutilsDb version number (手动滑稽)

**Comment by yanzhonghui** [comment]
> if you bean class changed,you need upgrad you XutilsDb version number (手动滑稽)

oh, thanks! (fuck ur mom)
