### ISSUE TITLE
DB的问题如何判断表是否存在

### ISSUE THREAD

**Issue by cekowu** [wyouflf/xUtils3#73]
Xutil 增加orm 数据库：
   集成xutil 数据库这块，可能是应用发布了几个版本之后才修改集成的，这时数据库的表已经存在手上，
这时希望有方法判断某些表是否存在

**Comment by wyouflf** [comment]
TableEntity.get(db, tableClass).tableIsExist();

**Comment by cekowu** [comment]
谢谢

**Comment by 494739635** [comment]
TableEntity.get(db, tableClass).createEntity();是否就是创建数据库表?
TableEntity这个类是否就是用于 通过实体类获取该类对应的表所在的数据库信息？

**Comment by MarnonLee** [comment]
db.getTable(T.class).tableIsExist()

**Comment by wolipengbo** [comment]
谢谢，我也在找这个方法
