### ISSUE TITLE
发现了一个大bug

### ISSUE THREAD

**Issue by xiyangyang8110** [wyouflf/xUtils3#732]
`RequestParams params1 = new RequestParams(Constant.serviceClassId+classificationId);`
这种方式最后自动加&
debug跟踪发现问题出在
[https://img-blog.csdnimg.cn/060936cfc55646e29e217497b9adfdc8.png?x-oss-process=image/watermark,type_d3F5LXplbmhlaQ,shadow_50,text_Q1NETiBAeGl5YW5neWFuZzgxMTA=,size_20,color_FFFFFF,t_70,g_se,x_16](url)

**Comment by jyh149129** [comment]
特殊格式是需要你自定义的，这个算什么bug。。。

**Comment by xiyangyang8110** [comment]
前两天已经修改了，开心、
![RRD% 1HK`4FQHSWG_ZTSS97](https://user-images.githubusercontent.com/17593784/164632455-80d65ab6-5519-4d6f-8ea9-ede5dc7291b4.png)
