### ISSUE TITLE
有没有办法在Callback.CommonCallback<T>里的泛型中放List？

### ISSUE THREAD

**Issue by awq14789** [wyouflf/xUtils3#75]
用httpget获取了一个json数组，有没有办法使用Callback.CommonCallback<List<User>>来直接获取这个被转化的List?
泛型用User会提示java.util.ArrayList cannot be cast to User，但是换成List就会提示not found @HttpResponse from java.util.List

**Comment by wyouflf** [comment]
更新到 3.1.17 看这个示例代码:
https://github.com/wyouflf/xUtils3/blob/master/sample/src/main/java/org/xutils/sample/http/JsonResponseParser.java

https://github.com/wyouflf/xUtils3/blob/master/sample/src/main/java/org/xutils/sample/http/BaiduResponse.java

https://github.com/wyouflf/xUtils3/blob/master/sample/src/main/java/org/xutils/sample/HttpFragment.java
