### ISSUE TITLE
数据库插入List型数据失败的问题反馈

### ISSUE THREAD

**Issue by klpchan** [wyouflf/xUtils3#76]
你好，最近在研究你的xutils3库使用，发现了一个数据库插入List失败问题（Always），感觉可能是插入过快导致唯一性索引相同的问题，取消唯一性索引可正常操作，有时间可关注下：
测试示例
                db = initDaoConfig(); //按照xutils3的github上sample配置
                
                parents = new ArrayList<Parent>();

                for (int i = 0; i < 5; i++) {
                    parents.add(i, createParent());
//                    db.saveBindingId(parents.get(i)); 可以成功

                }
                
//              db.saveBindingId(parents); //出现Warning信息，如下，且5条数据均插入失败

    private Parent createParent() {
        Parent parent = new Parent();
        parent.name = "klp" + System.currentTimeMillis();
        parent.setAdmin(true);
        parent.setEmail("klpchan@qq.com" + System.currentTimeMillis());
        parent.setTime(new Date());
        parent.setDate(new java.sql.Date(new Date().getTime()));
        return parent;
    }

测试机型：三星S5,4.4.2	
出现频率：always
每次插入People类的ArrayList数据时均失败，log如下：

12-18 21:12:32.669: I/KlpXutisDB:DbManagerImpl.createTableIfNotExist(L:465)(6593): Create table sqlInfo is CREATE TABLE IF NOT EXISTS "parent" ( "id" INTEGER PRIMARY KEY AUTOINCREMENT, "date" INTEGER ,"email" TEXT ,"time" INTEGER ,"name" TEXT ,"isAdmin" INTEGER  )
12-18 21:12:32.669: I/KlpXutisDB:DbManagerImpl.execNonQuery(L:568)(6593): execNonQuery sqlInfo is CREATE TABLE IF NOT EXISTS "parent" ( "id" INTEGER PRIMARY KEY AUTOINCREMENT, "date" INTEGER ,"email" TEXT ,"time" INTEGER ,"name" TEXT ,"isAdmin" INTEGER  )
12-18 21:12:32.669: I/KlpXutisDB:DbManagerImpl.execNonQuery(L:568)(6593): execNonQuery sqlInfo is INSERT INTO "parent" ("date","email","time","name","isAdmin") VALUES (?,?,?,?,?)
12-18 21:12:32.669: I/KlpXutisDB:DbManagerImpl.execNonQuery(L:568)(6593): execNonQuery sqlInfo is INSERT INTO "parent" ("date","email","time","name","isAdmin") VALUES (?,?,?,?,?)
12-18 21:12:32.679: W/System.err(6593): org.xutils.ex.DbException: columns name, email are not unique (code 19)
12-18 21:12:32.679: W/System.err(6593): 	at org.xutils.db.DbManagerImpl.execNonQuery(DbManagerImpl.java:574)
12-18 21:12:32.679: W/System.err(6593): 	at org.xutils.db.DbManagerImpl.saveBindingIdWithoutTransaction(DbManagerImpl.java:429)
12-18 21:12:32.679: W/System.err(6593): 	at org.xutils.db.DbManagerImpl.saveBindingId(DbManagerImpl.java:196)
12-18 21:12:32.679: W/System.err(6593): 	at com.xutils.klpsample.MainDBSampleActivity.onClick(MainDBSampleActivity.java:92)
12-18 21:12:32.679: W/System.err(6593): 	at android.view.View.performClick(View.java:4637)
12-18 21:12:32.679: W/System.err(6593): 	at android.view.View$PerformClick.run(View.java:19422)
12-18 21:12:32.679: W/System.err(6593): 	at android.os.Handler.handleCallback(Handler.java:733)
12-18 21:12:32.679: W/System.err(6593): 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-18 21:12:32.679: W/System.err(6593): 	at android.os.Looper.loop(Looper.java:136)
12-18 21:12:32.679: W/System.err(6593): 	at android.app.ActivityThread.main(ActivityThread.java:5586)
12-18 21:12:32.679: W/System.err(6593): 	at java.lang.reflect.Method.invokeNative(Native Method)
12-18 21:12:32.689: W/System.err(6593): 	at java.lang.reflect.Method.invoke(Method.java:515)
12-18 21:12:32.689: W/System.err(6593): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
12-18 21:12:32.689: W/System.err(6593): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
12-18 21:12:32.689: W/System.err(6593): 	at dalvik.system.NativeStart.main(Native Method)
12-18 21:12:32.689: W/System.err(6593): Caused by: android.database.sqlite.SQLiteConstraintException: columns name, email are not unique (code 19)
12-18 21:12:32.689: W/System.err(6593): 	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
12-18 21:12:32.689: W/System.err(6593): 	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:745)
12-18 21:12:32.689: W/System.err(6593): 	at android.database.sqlite.SQLiteSession.execute(SQLiteSession.java:619)
12-18 21:12:32.689: W/System.err(6593): 	at android.database.sqlite.SQLiteStatement.execute(SQLiteStatement.java:44)
12-18 21:12:32.689: W/System.err(6593): 	at org.xutils.db.DbManagerImpl.execNonQuery(DbManagerImpl.java:572)
12-18 21:12:32.689: W/System.err(6593): 	... 14 more

**Comment by wyouflf** [comment]
表结构变化了, 没有配置升级接口?

**Comment by klpchan** [comment]
不是，发生在第一次运行app时，后来发现应该是唯一性索引的问题，插入list时遍历很快，导致前两条记录name 和 email 一样了。
