### ISSUE TITLE
加载图片遇到oom

### ISSUE THREAD

**Issue by lifetin** [wyouflf/xUtils3#77]
原图是300,或是250,用的是imageView

imageOptions = new ImageOptions.Builder().setSize(0, 0)
.setImageScaleType(ImageView.ScaleType.CENTER_CROP)
        .setLoadingDrawable(context.getResources().getDrawable(R.drawable.default_pic))
        .setFailureDrawable(context.getResources().getDrawable(R.drawable.default_pic))
        .setFadeIn(true)
        .build();

这样设置的也会oom.不知该如何解决?
在6群中找 超人不会飞 

![image](https://cloud.githubusercontent.com/assets/10474968/11916564/a2f777bc-a716-11e5-892d-a5f2ed34020e.png)

**Comment by wyouflf** [comment]
检查是否有activity, view等引用的内存泄露.

**Comment by wyouflf** [comment]
注意重用convertView, imageOptions.setSize( w, h)也尽量加上合适的值, 或者在xml里声明 maxWidth 和 maxHeight.
