### ISSUE TITLE
最低兼容到4.0是个问题

### ISSUE THREAD

**Issue by niushu** [wyouflf/xUtils3#8]
现在还有很多2.3的用户

**Comment by bacy** [comment]
是的，作者是否考虑往下兼容，是哪部分功能导致2.3无法兼容呢？

**Comment by wyouflf** [comment]
目前的源码是可以兼容2.3的, 只是不保证后期维护时继续兼容.

**Comment by cxbiao** [comment]
没有很多2.3的手机呀！

**Comment by wyouflf** [comment]
2.3手机越来越少了, 高德地图等很多app现在都从4.0开始兼容...

**Comment by bacy** [comment]
然而老板不听，只要市场有1%的占有率，就必须兼容

**Comment by cxbiao** [comment]
@bacy 
哪你们直接用urlconnection封装就好了，这很容易

**Comment by wyouflf** [comment]
留一个稳定版给2.3用, 之后升级不再给兼容2.3的版本升级. 现在很多大公司都开始这样做了.

2.3的用户不经常使用手机, 应用装在他的手机里没有太大的意义.

**Comment by wujun1206** [comment]
留名关注中....

**Comment by lizhidu** [comment]
nnnn

**Comment by kimver** [comment]
兼容2.3的话，势必会损失一些特性，为了照顾这些冥顽不化的老古董真不值，支持不兼容

**Comment by xiejianchao** [comment]
2.3完全可以忽略，完全没必要再做任何兼容，即便你是亿级用户的app也应该放弃支持，何况你的app ？早在很一年前，很多产品都已经不再支持2.3版本的用户了，兼容2.3太耗费精力，也不值得，这部分用户毫无价值。

**Comment by bacy** [comment]
微信 qq应该都支持2.3

**Comment by Harris-wu** [comment]
大公司的app都不支持2.3了，我们自然也不用继续支持了嘛

**Comment by kimver** [comment]
微信早就不支持了2.3了，QQ估计很快也就不支持了

**Comment by john-jianxiaohu** [comment]
就不支持 怎么地吧

**Comment by cxbiao** [comment]
此问题已关闭，不要争论了！

**Comment by NitroXenon** [comment]
@niushu 你应该不会还在用 2.3 吧?  现在 2.3 都没人用了，很多机型都可以升级 >4.0 ，兼容 2.3 没必要吧

**Comment by Apples0609** [comment]
都是国内开发者争论这个。。。

**Comment by Allen-Cai** [comment]
就不支持2.3，怎么滴

**Comment by niushu** [comment]
淡定
我们的app领域比较垂直，有部分2.3的活跃用户，我们不能不管。
不过前两个月我已经计划提高minSdkVersion了，默默的在最新版本改成了『4.0』。
以前的用户让他们用旧版本就好了，后台的更新通知也不会干扰他们了。

**Comment by Carpten** [comment]
居然还有人在讨论是否支持2.3，请问2.3是什么

**Comment by Androidshilei** [comment]
应该直接5.0以上，搞那么多兼容包，搞毛线兼容

**Comment by 1240643122** [comment]
这个下载怎么没有找到download了
x.http().get
是不是这样下载

**Comment by 1240643122** [comment]
这么长时间都没人理。。。不过我早都找到了

**Comment by leveychen** [comment]
直接从API 19 开始  偷笑~

**Comment by jockxu** [comment]
只要QQ 微信 淘宝 最低支持4.0   绝对没有人会用4.0以下的手机了。 就用这个了 4.0以下的用户不用管了

**Comment by binbinqq86** [comment]
2.3的确可以忽略了。。。

**Comment by Fan-Dev** [comment]
android 3.0的也全线放弃兼容了？

**Comment by CCC2016** [comment]
微信，支付宝 ＡＰＩ最低支持是 Level 15。
