### ISSUE TITLE
HTTP请求返回值中，如何获取htt的head信息

### ISSUE THREAD

**Issue by yunzhongyu** [wyouflf/xUtils3#80]
与服务器的交互，很多东西是通过head进行传递的，
3.0版本中，http请求回调中，如何获取服务器端返回的head信息？
在线等，谢谢！

**Comment by wyouflf** [comment]
请求Header获取: 参考
https://github.com/wyouflf/xUtils3/blob/master/xutils/src/main/java/org/xutils/http/app/InterceptRequestListener.java

README和示例代码的注释里有介绍.
