### ISSUE TITLE
DB使用注解标明Column，那如果我项目里面类属性非常多，那不是非常麻烦？

### ISSUE THREAD

**Issue by zhuxiujia** [wyouflf/xUtils3#85]
DB使用注解标明Column，那如果我项目里面类属性非常多，那不是非常麻烦？可不可以这样，其他默认是Column，使用注解标明某个类属性成员是不写入数据库和标明某个是id就够了。

**Comment by wyouflf** [comment]
不这样做项目编译混淆的配置会比较麻烦.

**Comment by winnershili** [comment]
用代码生成器 一下就全搞定了! 很方便
