### ISSUE TITLE
sample问题反馈

### ISSUE THREAD

**Issue by h55l55** [wyouflf/xUtils3#86]
DbManager.DaoConfig daoConfig = new DbManager.DaoConfig().setDbName("test");
DBFragment中，开始数据库初始化时候，test应该为test.db，否则会报如下异常：
Failed to open database '/sdcard/test'.

**Comment by wyouflf** [comment]
那只是个示例, 是不是因为你的sdcard上存在名为 /sdcard/test 的文件, 但它不是数据库文件.

**Comment by h55l55** [comment]
不是，改成test.db就可以正常了，包括换个目录也是，不加后缀名都会报那个错误
