### ISSUE TITLE
Callback.CommonCallback 的CallBack没有onStart()开始回调

### ISSUE THREAD

**Issue by zhuxiujia** [wyouflf/xUtils3#88]
Callback.CommonCallback 的CallBack没有onStart()方法的开始回调（2.x版本的xutils是有的），请问http的任务调度顺序是不是先进先出的？因为假设app需要显示加载对话框，有多个任务请求的时候，会导致对话框没有及时开启。

**Comment by wyouflf** [comment]
在发请求的前一行显示Loading对话框, onFinish的时候关闭.

或者使用Callback.ProgressCallback.

Callback接口可以组合使用.

**Comment by tsyandroid** [comment]
代码中，能体现一下吗

**Comment by wyouflf** [comment]
showProgress();

x.http().get(params, new Callback.xxxCallback<ResultType>(){

.........

onFinished() {
    dismissProgress();
}

})

**Comment by tsyandroid** [comment]
谢谢
