### ISSUE TITLE
下载文件问题

### ISSUE THREAD

**Issue by ehaahe** [wyouflf/xUtils3#89]
下载文件时必须自己定义downloadmanager么？还是有什么简便方法？

**Comment by taixjgg** [comment]
+1

**Comment by duolanmeng** [comment]
我也想问这个问题 =_=

**Comment by duolanmeng** [comment]
下载文件的方法，作者在readME当中有提到：
Callback.Cancelable cancelable
       = x.http().get(params,
       /**
        * 1. callback的泛型:
        * callback参数默认支持的泛型类型参见{@link org.xutils.http.loader.LoaderFactory},
        * 例如: 指定泛型为File则可实现文件下载, 使用params.setSaveFilePath(path)指定文件保存的全路径.
        * 默认支持断点续传(采用了文件锁和尾端校验续传文件的一致性).
        * 其他常用类型可以自己在LoaderFactory中注册,
        * 也可以使用{@link org.xutils.http.annotation.HttpResponse}
        * 将注解HttpResponse加到自定义返回值类型上, 实现自定义ResponseParser接口来统一转换.
        * 如果返回值是json形式, 那么利用第三方的json工具将十分容易定义自己的ResponseParser.
        * 如示例代码{@link org.xutils.sample.http.BaiduResponse}, 可直接使用BaiduResponse作为
        * callback的泛型.
        *
