### ISSUE TITLE
Http访问在某些机型上会出现奇怪的java.io.EOFException异常

### ISSUE THREAD

**Issue by chencan89** [wyouflf/xUtils3#93]
一直比较喜欢楼主的xUtils库，本次新做项目，打算换掉原来的xUtils2的库，用新版xUtils3，结果使用中发现了一个奇怪的 EOFException 异常。

我的网络访问代码如下：
        x.http().request(method, requestParams, new Callback.CommonCallback<JSONObject>() {
            @Override
            public void onSuccess(JSONObject jsonObject) {
                Log.v("Http cancelled", jsonObject.toString());
            }

            @Override
            public void onError(Throwable throwable, boolean b) {
                Log.e("Http cancelled", e.toString());
            }

            @Override
            public void onCancelled(CancelledException e) {
                Log.v("Http cancelled", e.toString());
            }

            @Override
            public void onFinished() {
            }
        });
在发起请求的时候第一次总是正常的，如果在30秒内，发起第二次请求也是正常的。但是当闲置时间超过30秒，再此发起请求，必然抛出 java.io.EOFException。抛出该异常后，再次发起网络请求，又正常了。如果30秒后，再请求，又抛出 java.io.EOFException。
怀疑是xUtils3的库与我的测试机（华为G610，4.2.2版）不兼容，换用小米Note和三星果然正常，每次访问均返回成功。
但是华为的测试机在其它项目xUtils2中测试，从没出现问题。果断换回xUtils2的库，测试果然每次访问均成功。
==============================================================================
如此看来xUtils3的库确实有问题，为了方便修改调试，下载了一份楼主的源码，直接放入测试项目中，
分析了一下网络发送的代码，终于在org.xutils.http.request.HttpRequest中发现了问题。改类的sendRequest函数中有以下代码：
                   long contentLength = body.getContentLength();
                    if (contentLength < 0) {
                        connection.setChunkedStreamingMode(256 * 1024);
                    } else {
                        if (contentLength < Integer.MAX_VALUE) {
                            connection.setFixedLengthStreamingMode((int) contentLength);
                        } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
                            connection.setFixedLengthStreamingMode(contentLength);
                        } else {
                            connection.setChunkedStreamingMode(256 * 1024);
                        }
                    }
将代码 connection.setFixedLengthStreamingMode((int) contentLength); 注释掉，问题果然不在出现了。
问题虽然解决了，但并不想直接引入楼主的源码，也不想使用原来的xUtils2，好纠结！希望楼主可以尽快更新此问题。谢谢！

**Comment by wyouflf** [comment]
今晚修复, 明天更新, 这个是Android 4.4之前google实现的HttpUrlConnection的bug.
xUtils 3.1.20之后的版本修复此问题.

**Comment by wyouflf** [comment]
更新到3.1.26以彻底解决次问题

**Comment by gxp3635** [comment]
华为荣耀3x  4.2.2系统还存在这个问题，xUtils-3.3.34版本
