### ISSUE TITLE
麻烦看下这是个什么错误？

### ISSUE THREAD

**Issue by ehaahe** [wyouflf/xUtils3#96]
![image](https://cloud.githubusercontent.com/assets/9740081/12005179/1dbc673c-abd1-11e5-9d0f-6fa96fcbd17f.png)

**Comment by ehaahe** [comment]
感觉像是热编译的问题，我用的as版本2.0.4

**Comment by pickyourself** [comment]
没有调用x.Ext.init(app)  ?

**Comment by ehaahe** [comment]
调用了的，但是安装后第一次启动报这样的异常，之后就可以正常运行了

**Comment by wyouflf** [comment]
没有在manifest里声明你的自定义Application?

**Comment by ehaahe** [comment]
声明了的

**Comment by ehaahe** [comment]
![qq 20151228144651](https://cloud.githubusercontent.com/assets/9740081/12015120/bb2e1bbc-ad72-11e5-9cab-b5936fcf4e90.png)

**Comment by wyouflf** [comment]
安装后第一次启动报这样的异常, 是系统dex缓存的问题, 主要集中在MUI V5的系统上吧.

**Comment by ehaahe** [comment]
我用的5太子，反倒是我的小米note上的miui v7没出现这种问题
