### ISSUE TITLE
请问xUtils3怎样在断网后读取网络缓存的图片啊！

### ISSUE THREAD

**Issue by xihacode** [wyouflf/xUtils3#97]
请问xUtils3怎样在断网后读取网络缓存的图片啊！

**Comment by wyouflf** [comment]
有url就可以使用x.image().bind(...) 或 x.image().loadDrawabe(....) 或 x.image().loadFile(....)

**Comment by niit-qd** [comment]
@wyouflf 
我发现，断网后，就无法加载url图片了。
设备本地不是应该有文件缓存吗？
另外，是否可以在图片缓存中加入一个数据库，用于记录远程url对应的那个图片文件的本地下载路径（当然，还有下载结果，日期-设置过期时间，等信息）。
还有，用户往往希望把图片保存到本地，能否提供一个util来实现？例如，如果是内存资源，可以直接把内存资源保存成文件，如果有本地（远程）文件，可以直接进行文件拷贝。

比如说，微信中，离线的时候依然可以读取朋友圈中的图片（以获取url的前面几条信息），估计采用的就是数据库&本地缓存的方式。

**Comment by wyouflf** [comment]
@niit-qd 已支持缓存过期
