### ISSUE TITLE
应用跳转问题

### ISSUE THREAD

**Issue by ehaahe** [wyouflf/xUtils3#99]
第一个异步请求完成时调用第二个异步请求，第二个异步请求成功时打开另一个activity，为什么我每次到最后都不跳转activity呢？
已经抓包看过了，前两次请求都获取到了正确的数据，就只是activity不跳转
直接用的x.http().xxx异步方法，没有自己开asyntask，没有自己开线程
之前在2.x.x的时候可以成功跳转，不知道为什么一到3就不自动跳转了

**Comment by wyouflf** [comment]
自己调试一下错误信息
